Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3153.18
  t4-priority-dkp: 2995.51
  t5-lottery-dkp: 4398.45
  t5-priority-dkp: 2230.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Phoenix-Wing Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2686.8
  t4-priority-dkp: 3361.22
  t5-lottery-dkp: -9792.81
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 21.25
  t4-priority-dkp: 21.25
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Tsunami Talisman
  rank: Core Raider
  t4-lottery-dkp: 1971.77
  t4-priority-dkp: 3359.68
  t5-lottery-dkp: 5841.49
  t5-priority-dkp: 5738.37
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3248.33
  t4-priority-dkp: 3372.66
  t5-lottery-dkp: 2231.38
  t5-priority-dkp: 5797.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Gloves of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1803.72
  t4-priority-dkp: 3366.7
  t5-lottery-dkp: 3213.02
  t5-priority-dkp: 6792.52
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3054.74
  t4-priority-dkp: 3038.26
  t5-lottery-dkp: 5674.92
  t5-priority-dkp: 6696.04
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 571.43
  t5-priority-dkp: 571.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  - Pit Lord's Satchel
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Fang of the Leviathan
  - Mindstorm Wristbands
  rank: Reserve Raider
  t4-lottery-dkp: 2404.95
  t4-priority-dkp: 2782.09
  t5-lottery-dkp: 993.0
  t5-priority-dkp: 6121.05
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3348.87
  t4-priority-dkp: 2928.96
  t5-lottery-dkp: 2082.59
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Thalassian Wildercloak
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2984.6
  t4-priority-dkp: 3205.32
  t5-lottery-dkp: 893.61
  t5-priority-dkp: 6837.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 214.17
  t4-priority-dkp: 252.93
  t5-lottery-dkp: 178.4
  t5-priority-dkp: 210.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3327.08
  t4-priority-dkp: 2250.62
  t5-lottery-dkp: 4325.42
  t5-priority-dkp: 6868.48
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3372.66
  t4-priority-dkp: 2071.27
  t5-lottery-dkp: 3161.79
  t5-priority-dkp: 6915.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2383.98
  t4-priority-dkp: 2563.57
  t5-lottery-dkp: 2875.58
  t5-priority-dkp: 4161.22
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1530.71
  t4-priority-dkp: 3327.08
  t5-lottery-dkp: 3932.78
  t5-priority-dkp: 3957.24
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 2640.92
  t4-priority-dkp: 1858.2
  t5-lottery-dkp: 1863.77
  t5-priority-dkp: 6193.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Luminescent Rod of the Naaru
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3310.1
  t4-priority-dkp: 3141.06
  t5-lottery-dkp: 3064.37
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 3372.66
  t4-priority-dkp: 2949.92
  t5-lottery-dkp: 6514.22
  t5-priority-dkp: 6000.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Ring of Endless Coils
  priority-lootconfig:
  - Mindstorm Wristbands
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 3194.56
  t4-priority-dkp: 1947.02
  t5-lottery-dkp: 3882.56
  t5-priority-dkp: 4950.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3248.33
  t4-priority-dkp: 3372.66
  t5-lottery-dkp: 3411.38
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 177.12
  t5-priority-dkp: 177.12
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Mindstorm Wristbands
  - The Nexus Key
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3082.22
  t4-priority-dkp: 3358.94
  t5-lottery-dkp: 2572.15
  t5-priority-dkp: 6972.52
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2767.19
  t4-priority-dkp: 3319.03
  t5-lottery-dkp: -83.46
  t5-priority-dkp: 6045.4
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mekanina:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0
  t4-priority-dkp: 0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Pit Lord's Satchel
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3194.2
  t4-priority-dkp: 2831.1
  t5-lottery-dkp: 6828.76
  t5-priority-dkp: 5528.75
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2266.01
  t4-priority-dkp: 1855.74
  t5-lottery-dkp: 4499.65
  t5-priority-dkp: 6899.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2148.32
  t4-priority-dkp: 2148.32
  t5-lottery-dkp: 452.81
  t5-priority-dkp: 452.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 362.33
  t4-priority-dkp: 362.33
  t5-lottery-dkp: 2477.25
  t5-priority-dkp: 2477.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2708.47
  t4-priority-dkp: 3261.51
  t5-lottery-dkp: 416.93
  t5-priority-dkp: 6491.13
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 544.97
  t4-priority-dkp: 590.57
  t5-lottery-dkp: 621.61
  t5-priority-dkp: 659.52
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Dragonspine Trophy
  - Helm of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 2782.09
  t4-priority-dkp: 2782.09
  t5-lottery-dkp: 381.16
  t5-priority-dkp: 4728.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2866.76
  t4-priority-dkp: 2635.15
  t5-lottery-dkp: 1611.72
  t5-priority-dkp: 3883.82
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 2074.99
  t4-priority-dkp: 2758.54
  t5-lottery-dkp: 2919.44
  t5-priority-dkp: 5277.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 1672.66
  t4-priority-dkp: 2981.79
  t5-lottery-dkp: 2311.43
  t5-priority-dkp: 6583.7
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 1869.42
  t4-priority-dkp: 1869.42
  t5-lottery-dkp: 3217.23
  t5-priority-dkp: 3217.23
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 3089.22
  t4-priority-dkp: 3303.59
  t5-lottery-dkp: 5513.04
  t5-priority-dkp: 6165.54
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 1180.0
  t5-priority-dkp: 1180.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2968.42
  t4-priority-dkp: 2758.54
  t5-lottery-dkp: 3146.13
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2650.16
  t4-priority-dkp: 3372.66
  t5-lottery-dkp: -960.24
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3248.33
  t4-priority-dkp: 3372.66
  t5-lottery-dkp: 2231.38
  t5-priority-dkp: 5797.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3137.22
  t4-priority-dkp: 3361.22
  t5-lottery-dkp: 6781.16
  t5-priority-dkp: 6958.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3372.66
  t4-priority-dkp: 3100.18
  t5-lottery-dkp: 3076.14
  t5-priority-dkp: 5749.2
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3051.64
  t4-priority-dkp: 2650.16
  t5-lottery-dkp: 6709.94
  t5-priority-dkp: 6977.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
