Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Helm of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2675.3
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 4522.05
  t5-priority-dkp: 1392.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - Royal Gauntlets of Silvermoon
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1220.51
  t4-priority-dkp: 3324.31
  t5-lottery-dkp: -6052.81
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 66.29
  t4-priority-dkp: 66.29
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Leggings of the Fallen Champion
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 2420.31
  t4-priority-dkp: 3319.47
  t5-lottery-dkp: 1549.38
  t5-priority-dkp: 5059.08
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2382.15
  t4-priority-dkp: 2769.98
  t5-lottery-dkp: 444.83
  t5-priority-dkp: 3912.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2745.64
  t4-priority-dkp: 3341.37
  t5-lottery-dkp: 3352.68
  t5-priority-dkp: 5077.51
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2368.22
  t4-priority-dkp: 2316.83
  t5-lottery-dkp: 1029.81
  t5-priority-dkp: 4215.05
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 1517.77
  t4-priority-dkp: 1517.77
  t5-lottery-dkp: 2421.42
  t5-priority-dkp: 2421.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3285.74
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 3180.92
  t5-priority-dkp: 4942.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Shoulderpads of the Stranger
  - Thalassian Wildercloak
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2149.44
  t4-priority-dkp: 2837.98
  t5-lottery-dkp: -435.89
  t5-priority-dkp: 4657.719999999999
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 668.1
  t4-priority-dkp: 789.0
  t5-lottery-dkp: 556.49
  t5-priority-dkp: 657.34
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3217.75
  t4-priority-dkp: 2952.06
  t5-lottery-dkp: 4974.610000000001
  t5-priority-dkp: 4752.940000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Chestguard of the Fallen Champion
  - Gronn-Stitched Girdle
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 3128.37
  t5-lottery-dkp: 5092.87
  t5-priority-dkp: 4899.860000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 1659.98
  t4-priority-dkp: 3089.87
  t5-lottery-dkp: 3647.87
  t5-priority-dkp: 4867.610000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2121.72
  t4-priority-dkp: 3217.75
  t5-lottery-dkp: 1205.02
  t5-priority-dkp: 974.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Ring of Endless Coils
  - Sextant of Unstable Currents
  - Vestments of the Sea-Witch
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 1077.41
  t4-priority-dkp: 2467.19
  t5-lottery-dkp: 3504.21
  t5-priority-dkp: 5001.23
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3164.84
  t4-priority-dkp: 2637.48
  t5-lottery-dkp: 162.17
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Verdant Sphere
  priority-lootconfig:
  - Ring of Endless Coils
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 3217.75
  t5-lottery-dkp: 3647.87
  t5-priority-dkp: 2046.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Fathomstone
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2804.39
  t4-priority-dkp: 3192.65
  t5-lottery-dkp: 4630.08
  t5-priority-dkp: 4953.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Bracers of Eradication
  - Fang of Vashj
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2972.15
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 1624.83
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 552.5
  t5-priority-dkp: 552.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Endless Coils
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2453.96
  t4-priority-dkp: 3317.19
  t5-lottery-dkp: 2892.76
  t5-priority-dkp: 5077.51
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Fang of the Leviathan
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Royal Cloak of the Sunstriders
  - Royal Gauntlets of Silvermoon
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 1471.28
  t4-priority-dkp: 3192.65
  t5-lottery-dkp: -2124.09
  t5-priority-dkp: 4953.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - 'Pattern: Boots of Blasting'
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2803.27
  t4-priority-dkp: 1670.64
  t5-lottery-dkp: 4629.05
  t5-priority-dkp: 4518.48
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Rod of the Sun King
  - Serpent Spine Longbow
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2432.96
  t4-priority-dkp: 3068.88
  t5-lottery-dkp: 620.35
  t5-priority-dkp: 4850.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 280.5
  t5-priority-dkp: 280.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 340.0
  t5-priority-dkp: 340.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Phoenix-Ring of Rebirth
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3203.78
  t4-priority-dkp: 3013.25
  t5-lottery-dkp: 4962.83
  t5-priority-dkp: 3575.88
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1699.97
  t4-priority-dkp: 1842.21
  t5-lottery-dkp: 1939.06
  t5-priority-dkp: 2057.32
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  priority-lootconfig:
  - Dragonspine Trophy
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 1517.77
  t4-priority-dkp: 1517.77
  t5-lottery-dkp: 2421.42
  t5-priority-dkp: 2421.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 330.0
  t5-priority-dkp: 330.0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Aegis of the Vindicator
  - Chestguard of the Vanquished Champion
  - Sunhawk Leggings
  - Verdant Sphere
  priority-lootconfig:
  - Eye of Gruul
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1963.51
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 2203.21
  t5-priority-dkp: 4812.37
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig:
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 3317.19
  t5-lottery-dkp: 3864.62
  t5-priority-dkp: 3864.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 5092.87
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Band of Al'ar
  - Pendant of the Lost Ages
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  priority-lootconfig:
  - Soul-Eater's Handwraps
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 2475.81
  t4-priority-dkp: 3144.49
  t5-lottery-dkp: 4356.190000000001
  t5-priority-dkp: 4913.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2098.98
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 3198.89
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Bloodsea Brigand's Vest
  - Chestguard of the Fallen Champion
  - Magtheridon's Head
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 1647.87
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2382.15
  t4-priority-dkp: 2769.98
  t5-lottery-dkp: 444.83
  t5-priority-dkp: 3912.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2625.55
  t4-priority-dkp: 3324.31
  t5-lottery-dkp: 4480.58
  t5-priority-dkp: 5033.48
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Sunshower Light Cloak
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3359.98
  t4-priority-dkp: 2509.98
  t5-lottery-dkp: 1692.87
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2358.6
  t4-priority-dkp: 3359.98
  t5-lottery-dkp: 4258.4
  t5-priority-dkp: 5092.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
