Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: -302.23
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Aldori Legacy Defender
  - Leggings of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 615.37
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 466.05
  t4-priority-dkp: 466.05
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Bladespire Warbands
  - Chestguard of the Fallen Champion
  - Girdle of the Endless Pit
  - Leggings of the Fallen Champion
  - Pauldrons of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1575.0
  t4-priority-dkp: 1575.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Bladespire Warbands
  - Chestguard of the Fallen Defender
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1192.31
  t4-priority-dkp: 1728.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: -908.5
  t4-priority-dkp: 927.77
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1337.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Gronn-Stitched Girdle
  - Pauldrons of the Fallen Champion
  - Pit Lord's Satchel
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1337.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig:
  - Bladespire Warbands
  - Girdle of the Endless Pit
  priority-lootconfig:
  - Gauntlets of Martial Perfection
  rank: Core Raider
  t4-lottery-dkp: 725.0
  t4-priority-dkp: 1575.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1245.74
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Eye of Magtheridon
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Belt of Divine Inspiration
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1137.38
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Chestguard of the Fallen Hero
  - Eredar Wand of Obliteration
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Core Raider
  t4-lottery-dkp: 395.74
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Eredar Wand of Obliteration
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1009.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 487.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Leggings of the Fallen Champion
  - Pauldrons of the Fallen Champion
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 1384.07
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 761.6
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinasa:
  class: Priest
  lottery-lootconfig:
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 1728.98
  t4-priority-dkp: 1728.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kromlek:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Krumonx:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  - Pauldrons of the Fallen Champion
  priority-lootconfig:
  - Chestguard of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mitchendo:
  class: Shaman
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Pauldrons of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 697.66
  t4-priority-dkp: 1337.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mlg:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1137.38
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eye of Magtheridon
  - Magtheridon's Head
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 1245.74
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Gauntlets of Martial Perfection
  - Girdle of the Endless Pit
  - Leggings of the Fallen Defender
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1006.48
  t4-priority-dkp: 1728.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pikachau:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 261.78
  t4-priority-dkp: 261.78
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 761.6
  t4-priority-dkp: 1337.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Paladin
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Schroumpf:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1137.38
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekjr:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  - Magtheridon's Head
  - Pauldrons of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: -252.4
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnackypacky:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1580.89
  t4-priority-dkp: 1580.89
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shran:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 466.05
  t4-priority-dkp: 466.05
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Skypola:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 261.78
  t4-priority-dkp: 261.78
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 1728.98
  t4-priority-dkp: 1728.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Pit Lord's Satchel
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 523.25
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thejudge:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Leggings of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 240.59
  t4-priority-dkp: 1358.37
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Girdle of the Endless Pit
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: -204.5
  t4-priority-dkp: 1781.57
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
