Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2686.64
  t4-priority-dkp: 2429.91
  t5-lottery-dkp: 2039.25
  t5-priority-dkp: 2862.31
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Mallet of the Tides
  - Phoenix-Wing Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1927.22
  t4-priority-dkp: 3025.41
  t5-lottery-dkp: -11512.81
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 34.6
  t4-priority-dkp: 34.6
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1939.39
  t4-priority-dkp: 3022.9
  t5-lottery-dkp: 4389.0
  t5-priority-dkp: 4221.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2841.59
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 2200.14
  t5-priority-dkp: 5238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1873.35
  t4-priority-dkp: 3034.32
  t5-lottery-dkp: 402.08
  t5-priority-dkp: 6230.7
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 2526.34
  t4-priority-dkp: 2499.51
  t5-lottery-dkp: 4117.780000000001
  t5-priority-dkp: 5780.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  - Pit Lord's Satchel
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Reserve Raider
  t4-lottery-dkp: 1468.27
  t4-priority-dkp: 2082.39
  t5-lottery-dkp: 4844.219999999999
  t5-priority-dkp: 4844.219999999999
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Pauldrons of the Vanquished Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3005.29
  t4-priority-dkp: 2321.54
  t5-lottery-dkp: 645.73
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2412.13
  t4-priority-dkp: 2771.55
  t5-lottery-dkp: 1938.49
  t5-priority-dkp: 6011.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 348.75
  t4-priority-dkp: 411.86
  t5-lottery-dkp: 290.5
  t5-priority-dkp: 343.14
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2969.8
  t4-priority-dkp: 2216.98
  t5-lottery-dkp: 5177.0
  t5-priority-dkp: 6061.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Magtheridon's Head
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 2309.01
  t5-lottery-dkp: 4793.73
  t5-priority-dkp: 6137.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1434.13
  t4-priority-dkp: 2903.04
  t5-lottery-dkp: -401.4100000000001
  t5-priority-dkp: 4421.139999999999
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Pit Lord's Satchel
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 2397.65
  t4-priority-dkp: 2969.8
  t5-lottery-dkp: 1281.0
  t5-priority-dkp: 4088.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Gauntlets of the Sun King
  - Helm of the Vanquished Hero
  - Velvet Boots of the Guardian
  priority-lootconfig:
  - Pit Lord's Satchel
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 1852.52
  t4-priority-dkp: 2577.99
  t5-lottery-dkp: -1735.57
  t5-priority-dkp: 4962.639999999999
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2942.17
  t4-priority-dkp: 2666.89
  t5-lottery-dkp: 2219.87
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 2355.67
  t5-lottery-dkp: 5484.43
  t5-priority-dkp: 4648.440000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - Helm of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 2754.02
  t4-priority-dkp: 2106.69
  t5-lottery-dkp: 4552.15
  t5-priority-dkp: 4937.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Fang of Vashj
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2841.59
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 3200.14
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 288.41
  t5-priority-dkp: 288.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Mindstorm Wristbands
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2571.1
  t4-priority-dkp: 3021.7
  t5-lottery-dkp: 5090.26
  t5-priority-dkp: 6230.7
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2058.13
  t4-priority-dkp: 2956.69
  t5-lottery-dkp: 415.9100000000001
  t5-priority-dkp: 4721.04
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Pit Lord's Satchel
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2753.43
  t4-priority-dkp: 2162.19
  t5-lottery-dkp: 5996.61
  t5-priority-dkp: 3879.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2058.63
  t4-priority-dkp: 2390.58
  t5-lottery-dkp: 2204.04
  t5-priority-dkp: 6112.06
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1050.4
  t4-priority-dkp: 1050.4
  t5-lottery-dkp: 349.09
  t5-priority-dkp: 349.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 2853.79
  t5-priority-dkp: 2853.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2962.51
  t4-priority-dkp: 2863.04
  t5-lottery-dkp: 1580.85
  t5-priority-dkp: 5446.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 887.39
  t4-priority-dkp: 961.65
  t5-lottery-dkp: 1012.2
  t5-priority-dkp: 1073.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Vambraces of Ending
  priority-lootconfig:
  - Dragonspine Trophy
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 2082.39
  t4-priority-dkp: 2082.39
  t5-lottery-dkp: 1229.22
  t5-priority-dkp: 4929.219999999999
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 172.26
  t5-priority-dkp: 172.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Eye of Gruul
  - Helm of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Aegis of the Vindicator
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2315.07
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 1983.87
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 2407.57
  t5-lottery-dkp: 1897.57
  t5-priority-dkp: 5597.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 5238.73
  t5-priority-dkp: 5238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 2582.5
  t4-priority-dkp: 2931.56
  t5-lottery-dkp: 3854.18
  t5-priority-dkp: 4916.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2385.79
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 0.07000000000005002
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Band of the Ranger-General
  - Leggings of the Vanquished Champion
  - Magtheridon's Head
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 1725.55
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2841.59
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 2200.14
  t5-priority-dkp: 5238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2660.66
  t4-priority-dkp: 3025.41
  t5-lottery-dkp: 5919.11
  t5-priority-dkp: 6207.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3044.04
  t4-priority-dkp: 2600.34
  t5-lottery-dkp: -113.9000000000001
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2521.31
  t4-priority-dkp: 3044.04
  t5-lottery-dkp: 5803.13
  t5-priority-dkp: 6238.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
