Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 1884.83
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 2420.52
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Ancestral Ring of Conquest
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Serpentshrine Shuriken
  - Shuriken of Negation
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1868.91
  t4-priority-dkp: 2941.65
  t5-lottery-dkp: -1592.81
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 107.94
  t4-priority-dkp: 107.94
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Gloves of the Searing Grip
  - Leggings of the Fallen Champion
  - Pendant of the Perilous
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 1469.62
  t4-priority-dkp: 2933.75
  t5-lottery-dkp: -1925.43
  t5-priority-dkp: 3294.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Fallen Defender
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1999.38
  t4-priority-dkp: 2969.42
  t5-lottery-dkp: 516.39
  t5-priority-dkp: 3324.99
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2345.52
  t4-priority-dkp: 2261.84
  t5-lottery-dkp: 804.82
  t5-priority-dkp: 2734.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2878.83
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3249.13
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Shoulderpads of the Stranger
  - Thalassian Wildercloak
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2412.65
  t4-priority-dkp: 2149.73
  t5-lottery-dkp: 860.67
  t5-priority-dkp: 2641.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1087.88
  t4-priority-dkp: 1284.76
  t5-lottery-dkp: 906.14
  t5-priority-dkp: 1070.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2768.12
  t4-priority-dkp: 2335.49
  t5-lottery-dkp: 3157.44
  t5-priority-dkp: 2796.48
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2622.59
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 3035.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2559.9
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 2983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Leggings of the Vanquished Hero
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 983.42
  t4-priority-dkp: 2768.12
  t5-lottery-dkp: -330.56
  t5-priority-dkp: 3157.44
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Verdant Sphere
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 2295.37
  t4-priority-dkp: 2930.05
  t5-lottery-dkp: 763.14
  t5-priority-dkp: 3200.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2681.96
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3084.91
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - Velvet Boots of the Guardian
  priority-lootconfig:
  - Mindstorm Wristbands
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2768.12
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 1157.44
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2095.04
  t4-priority-dkp: 2727.25
  t5-lottery-dkp: 2596.42
  t5-priority-dkp: 3123.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Bracers of Eradication
  - Fang of Vashj
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2368.21
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 2823.99
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Sextant of Unstable Currents
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1524.42
  t4-priority-dkp: 2930.05
  t5-lottery-dkp: 2120.42
  t5-priority-dkp: 3324.99
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Seventh Ring of the Tirisfalen
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 2277.23
  t4-priority-dkp: 2727.25
  t5-lottery-dkp: 2748.13
  t5-priority-dkp: 3123.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2093.21
  t4-priority-dkp: 1877.25
  t5-lottery-dkp: 2594.75
  t5-priority-dkp: 2414.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Pauldrons of the Vanquished Defender
  - Pendant of the Perilous
  - Serpent Spine Longbow
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Rod of the Sun King
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 1490.23
  t4-priority-dkp: 2525.72
  t5-lottery-dkp: 2092.08
  t5-priority-dkp: 2954.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Phoenix-Ring of Rebirth
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2745.36
  t4-priority-dkp: 2435.13
  t5-lottery-dkp: 3138.26
  t5-priority-dkp: 879.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2768.12
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3157.44
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Girdle of Fallen Stars
  - Sunhawk Leggings
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 725.8
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 1454.37
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Cord of Screaming Terrors
  - Helm of the Vanquished Defender
  - Magtheridon's Head
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2930.05
  t5-lottery-dkp: 1350.0
  t5-priority-dkp: 1350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Band of Al'ar
  - Pendant of the Lost Ages
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  priority-lootconfig:
  - Soul-Eater's Handwraps
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 1560.0
  t4-priority-dkp: 2648.84
  t5-lottery-dkp: 2150.43
  t5-priority-dkp: 3057.4
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Fallen Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2122.87
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 2618.92
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Chestguard of the Fallen Champion
  - Gloves of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1803.83
  t4-priority-dkp: 2941.65
  t5-lottery-dkp: 2353.0
  t5-priority-dkp: 3253.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2999.73
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 3350.0
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Girdle of the Endless Pit
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1369.15
  t4-priority-dkp: 2999.73
  t5-lottery-dkp: 1991.21
  t5-priority-dkp: 3350.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
