Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Band of the Ranger-General
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3064.94
  t4-priority-dkp: 3051.17
  t5-lottery-dkp: 5315.14
  t5-priority-dkp: 5670.76
  t6-lottery-dkp: 1377.03
  t6-priority-dkp: 5176.72
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Eternium Shell Bracers
  - Leggings of the Vanquished Defender
  - Praetorian's Legguards
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3024.2
  t4-priority-dkp: 3083.11
  t5-lottery-dkp: -452.81
  t5-priority-dkp: 5331.11
  t6-lottery-dkp: -18297.0
  t6-priority-dkp: 4273.35
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 446.99
  t4-priority-dkp: 446.99
  t5-lottery-dkp: 725.85
  t5-priority-dkp: 725.85
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2819.5
  t4-priority-dkp: 3082.97
  t5-lottery-dkp: 5496.16
  t5-priority-dkp: 5977.17
  t6-lottery-dkp: 5363.26
  t6-priority-dkp: 5353.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2541.54
  t4-priority-dkp: 3083.11
  t5-lottery-dkp: 3448.22
  t5-priority-dkp: 6083.75
  t6-lottery-dkp: 1980.27
  t6-priority-dkp: 5925.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Helm of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2947.05
  t4-priority-dkp: 3083.59
  t5-lottery-dkp: 5566.77
  t5-priority-dkp: 6084.99
  t6-lottery-dkp: 2854.23
  t6-priority-dkp: 5415.15
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 2867.19
  t4-priority-dkp: 2865.75
  t5-lottery-dkp: 3514.82
  t5-priority-dkp: 5930.33
  t6-lottery-dkp: 6460.88
  t6-priority-dkp: 7243.73
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 49.92
  t5-priority-dkp: 49.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 2829.22
  t4-priority-dkp: 2792.54
  t5-lottery-dkp: 5452.29
  t5-priority-dkp: 5843.61
  t6-lottery-dkp: 4736.28
  t6-priority-dkp: 5787.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Madness of the Betrayer
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3050.21
  t4-priority-dkp: 3069.49
  t5-lottery-dkp: 3467.81
  t5-priority-dkp: 6073.24
  t6-lottery-dkp: 3091.86
  t6-priority-dkp: 5684.87
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 18.71
  t4-priority-dkp: 22.09
  t5-lottery-dkp: 15.58
  t5-priority-dkp: 18.41
  t6-lottery-dkp: 9.02
  t6-priority-dkp: 10.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3080.13
  t4-priority-dkp: 2986.09
  t5-lottery-dkp: 5853.75
  t5-priority-dkp: 4858.37
  t6-lottery-dkp: 4969.45
  t6-priority-dkp: 6551.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 896.07
  t4-priority-dkp: 896.07
  t5-lottery-dkp: 39.56
  t5-priority-dkp: 39.56
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3084.11
  t4-priority-dkp: 2970.43
  t5-lottery-dkp: 2082.12
  t5-priority-dkp: 3986.27
  t6-lottery-dkp: 4258.96
  t6-priority-dkp: 5696.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Royal Cloak of the Sunstriders
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2622.49
  t4-priority-dkp: 3013.44
  t5-lottery-dkp: 4647.74
  t5-priority-dkp: 5991.8
  t6-lottery-dkp: -2570.1
  t6-priority-dkp: 7116.21
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3078.64
  t4-priority-dkp: 3063.88
  t5-lottery-dkp: 3970.37
  t5-priority-dkp: 4887.63
  t6-lottery-dkp: 2746.53
  t6-priority-dkp: 7257.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Leggings of Channeled Elements
  - Leggings of the Vanquished Champion
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Ring of Ancient Knowledge
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3084.11
  t4-priority-dkp: 2433.06
  t5-lottery-dkp: 2655.7
  t5-priority-dkp: 5365.52
  t6-lottery-dkp: 3413.8
  t6-priority-dkp: 5512.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 530.5
  t4-priority-dkp: 530.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2538.05
  t4-priority-dkp: 2429.06
  t5-lottery-dkp: 5480.38
  t5-priority-dkp: 5573.65
  t6-lottery-dkp: 3511.87
  t6-priority-dkp: 5632.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2775.82
  t4-priority-dkp: 2683.91
  t5-lottery-dkp: 4529.09
  t5-priority-dkp: 5082.42
  t6-lottery-dkp: 4782.64
  t6-priority-dkp: 7257.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Pauldrons of the Forgotten Protector
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 3058.74
  t4-priority-dkp: 3082.92
  t5-lottery-dkp: 5700.59
  t5-priority-dkp: 5991.8
  t6-lottery-dkp: 3916.03
  t6-priority-dkp: 3247.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Anetheron's Noose
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2099.41
  t4-priority-dkp: 3032.52
  t5-lottery-dkp: 5098.24
  t5-priority-dkp: 3747.45
  t6-lottery-dkp: 2964.65
  t6-priority-dkp: 6618.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  rank: Core Raider
  t4-lottery-dkp: 2799.6
  t4-priority-dkp: 3079.42
  t5-lottery-dkp: 3548.88
  t5-priority-dkp: 5249.7
  t6-lottery-dkp: 8.2
  t6-priority-dkp: 1053.09
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1171.81
  t4-priority-dkp: 1171.81
  t5-lottery-dkp: 3196.19
  t5-priority-dkp: 3196.19
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2771.09
  t4-priority-dkp: 2533.83
  t5-lottery-dkp: 5787.94
  t5-priority-dkp: 4160.55
  t6-lottery-dkp: 2982.79
  t6-priority-dkp: 6750.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Choker of Serrated Blades
  - Deadly Cuffs
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 1910.95
  t4-priority-dkp: 1875.12
  t5-lottery-dkp: 1517.96
  t5-priority-dkp: 4173.38
  t6-lottery-dkp: -335.33
  t6-priority-dkp: 6819.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2621.49
  t4-priority-dkp: 2524.87
  t5-lottery-dkp: 1769.8
  t5-priority-dkp: 3388.33
  t6-lottery-dkp: 3620.12
  t6-priority-dkp: 4842.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pudsey:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Shroud of the Highborne
  - Sunshower Light Cloak
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3026.09
  t4-priority-dkp: 3074.4
  t5-lottery-dkp: 5512.33
  t5-priority-dkp: 5516.64
  t6-lottery-dkp: 2928.94
  t6-priority-dkp: 6930.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 427.4
  t4-priority-dkp: 427.4
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 71.33
  t4-priority-dkp: 71.33
  t5-lottery-dkp: 263.15
  t5-priority-dkp: 263.15
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 2311.77
  t4-priority-dkp: 2508.65
  t5-lottery-dkp: 5032.48
  t5-priority-dkp: 4849.21
  t6-lottery-dkp: 3387.94
  t6-priority-dkp: 2564.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 362.33
  t4-priority-dkp: 362.33
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 337.77
  t6-priority-dkp: 337.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2562.1
  t4-priority-dkp: 3060.31
  t5-lottery-dkp: 5539.08
  t5-priority-dkp: 5931.64
  t6-lottery-dkp: -383.0
  t6-priority-dkp: 7195.94
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2970.75
  t4-priority-dkp: 3030.46
  t5-lottery-dkp: 4352.09
  t5-priority-dkp: 5079.09
  t6-lottery-dkp: 5428.89
  t6-priority-dkp: 5211.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - The Skull of Gul'dan
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2935.61
  t4-priority-dkp: 2729.39
  t5-lottery-dkp: 5677.81
  t5-priority-dkp: 5991.8
  t6-lottery-dkp: 1745.08
  t6-priority-dkp: 7238.11
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 163.3
  t4-priority-dkp: 163.3
  t5-lottery-dkp: 281.04
  t5-priority-dkp: 281.04
  t6-lottery-dkp: 163.09
  t6-priority-dkp: 161.76
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Channeled Elements
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Slippers of the Seacaller
  - Tempest of Chaos
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 1742.62
  t4-priority-dkp: 2789.49
  t5-lottery-dkp: 4532.44
  t5-priority-dkp: 5578.98
  t6-lottery-dkp: 6369.67
  t6-priority-dkp: 4416.19
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Botanist's Gloves of Growth
  rank: Core Raider
  t4-lottery-dkp: 3048.8
  t4-priority-dkp: 3030.46
  t5-lottery-dkp: 2864.79
  t5-priority-dkp: 5559.11
  t6-lottery-dkp: 5047.9
  t6-priority-dkp: 5388.68
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2118.03
  t4-priority-dkp: 2118.03
  t5-lottery-dkp: 2815.11
  t5-priority-dkp: 2815.11
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Pauldrons of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2647.25
  t4-priority-dkp: 2789.49
  t5-lottery-dkp: -714.0
  t5-priority-dkp: 5475.91
  t6-lottery-dkp: 3939.52
  t6-priority-dkp: 6906.66
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2498.98
  t4-priority-dkp: 2916.77
  t5-lottery-dkp: 2553.53
  t5-priority-dkp: 6085.42
  t6-lottery-dkp: 4498.46
  t6-priority-dkp: 5415.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Ring of Deceitful Intent
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 2541.54
  t4-priority-dkp: 3083.11
  t5-lottery-dkp: 3448.22
  t5-priority-dkp: 6083.75
  t6-lottery-dkp: 1980.27
  t6-priority-dkp: 5925.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Madness of the Betrayer
  priority-lootconfig:
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2249.9
  t4-priority-dkp: 2214.84
  t5-lottery-dkp: 6062.06
  t5-priority-dkp: 4640.42
  t6-lottery-dkp: 2540.28
  t6-priority-dkp: 3376.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
