Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Infamy
  - Boundless Agony
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Cursed Vision of Sargeras
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Leggings of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  - Stormrage Signet Ring
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Bristleblitz Striker
  - Madness of the Betrayer
  rank: Core Raider
  t4-lottery-dkp: 3282.38
  t4-priority-dkp: 3231.83
  t5-lottery-dkp: 5574.84
  t5-priority-dkp: 4879.89
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3132.87
  t4-priority-dkp: 3349.07
  t5-lottery-dkp: -4712.81
  t5-priority-dkp: 6401.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1050.4
  t4-priority-dkp: 1050.4
  t5-lottery-dkp: 1483.78
  t5-priority-dkp: 1483.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of Devastation
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Shadowmoon Destroyer's Drape
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Dreadboots of the Legion
  rank: Core Raider
  t4-lottery-dkp: 2381.63
  t4-priority-dkp: 3348.57
  t5-lottery-dkp: 4239.14
  t5-priority-dkp: 6004.38
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Dragonspine Trophy
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2849.77
  t4-priority-dkp: 3350.82
  t5-lottery-dkp: 4498.23
  t5-priority-dkp: 6400.02
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3250.82
  t4-priority-dkp: 3245.53
  t5-lottery-dkp: 5984.04
  t5-priority-dkp: 6311.39
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 183.19
  t5-priority-dkp: 183.19
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: -260.95
  t4-priority-dkp: 3163.41
  t5-lottery-dkp: 2778.8
  t5-priority-dkp: 4682.06
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2417.33
  t4-priority-dkp: 2282.73
  t5-lottery-dkp: 4078.13
  t5-priority-dkp: 5514.2
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Bow-stitched Leggings
  - Fists of Mukoa
  - Madness of the Betrayer
  - Midnight Chestguard
  - Rod of the Sun King
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3228.33
  t4-priority-dkp: 3299.09
  t5-lottery-dkp: 4451.27
  t5-priority-dkp: 6356.89
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 68.65
  t4-priority-dkp: 81.09
  t5-lottery-dkp: 57.2
  t5-priority-dkp: 67.55
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Nexus Key
  priority-lootconfig:
  - The Skull of Gul'dan
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 3338.12
  t4-priority-dkp: 2993.04
  t5-lottery-dkp: 5551.42
  t5-priority-dkp: 4666.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3352.73
  t4-priority-dkp: 2935.53
  t5-lottery-dkp: 3478.4
  t5-priority-dkp: 4936.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Eye of Magtheridon
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2658.64
  t4-priority-dkp: 3093.36
  t5-lottery-dkp: 1125.54
  t5-priority-dkp: 5498.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Luminescent Rod of the Naaru
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3332.68
  t4-priority-dkp: 3278.48
  t5-lottery-dkp: 5147.16
  t5-priority-dkp: 6401.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3352.73
  t4-priority-dkp: 3217.21
  t5-lottery-dkp: 5309.13
  t5-priority-dkp: 3759.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 3295.64
  t4-priority-dkp: 2895.7
  t5-lottery-dkp: 4181.2
  t5-priority-dkp: 4523.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2811.38
  t4-priority-dkp: 2474.08
  t5-lottery-dkp: 4370.99
  t5-priority-dkp: 6401.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3259.63
  t4-priority-dkp: 3348.34
  t5-lottery-dkp: 4989.36
  t5-priority-dkp: 6400.02
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Antonidas's Aegis of Rapt Concentration
  - Boots of the Resilient
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - Hammer of Judgement
  - Phoenix-Wing Cloak
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2308.63
  t4-priority-dkp: 3335.54
  t5-lottery-dkp: 1861.06
  t5-priority-dkp: 6102.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Verdant Sphere
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Vestments of the Sea-Witch
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2794.03
  t4-priority-dkp: 1923.32
  t5-lottery-dkp: 5309.92
  t5-priority-dkp: 5937.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2635.64
  t4-priority-dkp: 2504.11
  t5-lottery-dkp: 2870.43
  t5-priority-dkp: 6376.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2698.45
  t4-priority-dkp: 2698.45
  t5-lottery-dkp: 145.16
  t5-priority-dkp: 145.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Sunshower Light Cloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3139.81
  t4-priority-dkp: 3317.11
  t5-lottery-dkp: 4298.45
  t5-priority-dkp: 4314.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1568.47
  t4-priority-dkp: 1568.47
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 261.78
  t4-priority-dkp: 261.78
  t5-lottery-dkp: 965.71
  t5-priority-dkp: 965.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Gloves of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Don Alejandro's Money Belt
  - Dragonspine Trophy
  - Insidious Bands
  rank: Reserve Raider
  t4-lottery-dkp: 1648.63
  t4-priority-dkp: 2371.13
  t5-lottery-dkp: 3399.57
  t5-priority-dkp: 2726.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Crystal Spire of Karabor
  - Memento of Tyrande
  priority-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2936.73
  t4-priority-dkp: 3155.86
  t5-lottery-dkp: 3169.28
  t5-priority-dkp: 5102.33
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  rank: Core Raider
  t4-lottery-dkp: 2807.75
  t4-priority-dkp: 3227.43
  t5-lottery-dkp: 4905.78
  t5-priority-dkp: 6275.38
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 599.29
  t4-priority-dkp: 599.29
  t5-lottery-dkp: 1031.37
  t5-priority-dkp: 1031.37
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 1549.03
  t4-priority-dkp: 2271.53
  t5-lottery-dkp: 3055.36
  t5-priority-dkp: 4543.08
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Belt of Primal Majesty
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Crystal Spire of Karabor
  - Leggings of Eternity
  - Memento of Tyrande
  - Scepter of Purification
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3223.15
  t4-priority-dkp: 3155.86
  t5-lottery-dkp: 2245.12
  t5-priority-dkp: 4470.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Bracers of Martyrdom
  - Chestguard of the Forgotten Conqueror
  - Chestguard of the Vanquished Defender
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 1749.53
  t4-priority-dkp: 2271.53
  t5-lottery-dkp: -974.0
  t5-priority-dkp: 4164.8
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Talon of Azshara
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3121.11
  t4-priority-dkp: 2738.61
  t5-lottery-dkp: 2574.39
  t5-priority-dkp: 6401.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Thalassian Wildercloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3277.27
  t4-priority-dkp: 3349.07
  t5-lottery-dkp: 2962.26
  t5-priority-dkp: 6395.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3352.73
  t4-priority-dkp: 3265.38
  t5-lottery-dkp: 4396.63
  t5-priority-dkp: 6007.86
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Forgotten Protector
  - Cursed Vision of Sargeras
  - Dreadboots of the Legion
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 1697.93
  t4-priority-dkp: 1569.23
  t5-lottery-dkp: 6315.85
  t5-priority-dkp: 6401.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
