Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 1558.41
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Ancestral Ring of Conquest
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Frayed Tether of the Drowned
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Serpentshrine Shuriken
  - Seventh Ring of the Tirisfalen
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1532.48
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 175.77
  t4-priority-dkp: 175.77
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Gloves of the Searing Grip
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pendant of the Perilous
  - Razor-Scale Battlecloak
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 2266.4
  t4-priority-dkp: 3266.4
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1744.93
  t4-priority-dkp: 3324.48
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2308.56
  t4-priority-dkp: 2172.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3176.97
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Rod of the Sun King
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2417.87
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig:
  - Girdle of the Endless Pit
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1771.43
  t4-priority-dkp: 2092.01
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2996.7
  t4-priority-dkp: 2292.23
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 2759.72
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 2657.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Fathomstone
  - Gauntlets of the Sun King
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - Serpent-Coil Braid
  - Velvet Boots of the Guardian
  - Verdant Sphere
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 2443.55
  t4-priority-dkp: 2996.7
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3403.38
  t4-priority-dkp: 3082.79
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2856.4
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Ring of Endless Coils
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 2996.7
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 1900.69
  t4-priority-dkp: 2930.14
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2345.51
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Pauldrons of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3324.48
  t4-priority-dkp: 3324.48
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinyonga:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2734.48
  t4-priority-dkp: 2734.48
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kromlek:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Krumonx:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Aldori Legacy Defender
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 2930.14
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mitchendo:
  class: Shaman
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Pauldrons of the Fallen Champion
  rank: Social Member
  t4-lottery-dkp: 485.64
  t4-priority-dkp: 727.1
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mlg:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2759.72
  t4-priority-dkp: 3101.36
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 1897.72
  t4-priority-dkp: 2930.14
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 915.86
  t4-priority-dkp: 2601.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pikachau:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 98.73
  t4-priority-dkp: 98.73
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2959.64
  t4-priority-dkp: 2454.47
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2996.7
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Paladin
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Schroumpf:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1221.25
  t4-priority-dkp: 1493.73
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Girdle of Fallen Stars
  - Magtheridon's Head
  - Sunhawk Leggings
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1055.2
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnackypacky:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2366.26
  t4-priority-dkp: 2366.26
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shran:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 175.77
  t4-priority-dkp: 175.77
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Skypola:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 98.73
  t4-priority-dkp: 98.73
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Band of Al'ar
  - Pendant of the Lost Ages
  - Royal Cloak of the Sunstriders
  priority-lootconfig:
  - Soul-Eater's Handwraps
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 1029.48
  t4-priority-dkp: 2802.47
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Girdle of Zaetar
  - Grove-Bands of Remulos
  - Helm of the Vanquished Defender
  - Orca-Hide Boots
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1946.01
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Tenfour:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 116.15
  t4-priority-dkp: 116.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thejudge:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 116.15
  t4-priority-dkp: 116.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1426.51
  t4-priority-dkp: 3184.7
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3373.84
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2102.8
  t4-priority-dkp: 3373.84
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
