Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boneweave Girdle
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Endless Nightmares
  - Insidious Bands
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3417.81
  t4-priority-dkp: 3413.39
  t5-lottery-dkp: 3050.8
  t5-priority-dkp: 2523.66
  t6-lottery-dkp: 4992.09
  t6-priority-dkp: 10219.9
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Borderland Fortress Grips
  - Bulwark of Azzinoth
  - Chestguard of the Forgotten Protector
  - Collar of the Pit Lord
  - Crimson Paragon's Cover
  - Crown of Anasterian
  - Dragonscale-Encrusted Longblade
  - Felfury Legplates
  - Ring of Hardened Resolve
  - Steely Naaru Sliver
  priority-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 3404.76
  t4-priority-dkp: 3423.64
  t5-lottery-dkp: 314.31
  t5-priority-dkp: 3055.91
  t6-lottery-dkp: -13237.0
  t6-priority-dkp: 8087.92
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 143.29
  t4-priority-dkp: 143.29
  t5-lottery-dkp: 232.69
  t5-priority-dkp: 232.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2749.13
  t4-priority-dkp: 2389.89
  t5-lottery-dkp: 3108.84
  t5-priority-dkp: 3263.03
  t6-lottery-dkp: 7106.21
  t6-priority-dkp: 10276.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2660.02
  t4-priority-dkp: 2833.64
  t5-lottery-dkp: 2452.31
  t5-priority-dkp: 3297.2
  t6-lottery-dkp: 1983.06
  t6-priority-dkp: 8694.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3380.02
  t4-priority-dkp: 3423.8
  t5-lottery-dkp: 2490.31
  t5-priority-dkp: 3297.6
  t6-lottery-dkp: 8513.630000000001
  t6-priority-dkp: 9164.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1900.58
  t4-priority-dkp: 1900.12
  t5-lottery-dkp: 2473.67
  t5-priority-dkp: 3248.01
  t6-lottery-dkp: 5007.18
  t6-priority-dkp: 5258.14
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3342.25
  t4-priority-dkp: 3330.49
  t5-lottery-dkp: 2571.2
  t5-priority-dkp: 2696.64
  t6-lottery-dkp: 8512.689999999999
  t6-priority-dkp: 7007.26
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Choker of Endless Nightmares
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Mantle of the Golden Forest
  - Mounting Vengeance
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3413.09
  t4-priority-dkp: 3419.28
  t5-lottery-dkp: 2458.59
  t5-priority-dkp: 3293.83
  t6-lottery-dkp: 9551.54
  t6-priority-dkp: 10382.8
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 6.0
  t4-priority-dkp: 7.08
  t5-lottery-dkp: 4.99
  t5-priority-dkp: 5.9
  t6-lottery-dkp: 2.89
  t6-priority-dkp: 3.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demacian:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3422.68
  t4-priority-dkp: 3392.54
  t5-lottery-dkp: 3223.48
  t5-priority-dkp: 2904.37
  t6-lottery-dkp: 421.54
  t6-priority-dkp: 10660.52
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 287.26
  t4-priority-dkp: 287.26
  t5-lottery-dkp: 12.69
  t5-priority-dkp: 12.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Belt of the Forgotten Vanquisher
  - Boots of the Forgotten Vanquisher
  - Bracers of the Forgotten Vanquisher
  - Cloak of Unforgivable Sin
  - 'Design: Hard Khorium Choker'
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Hand of the Deceiver
  rank: Core Raider
  t4-lottery-dkp: 3423.95
  t4-priority-dkp: 3387.51
  t5-lottery-dkp: 1126.96
  t5-priority-dkp: 2624.8
  t6-lottery-dkp: 7758.19
  t6-priority-dkp: 10386.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3275.97
  t4-priority-dkp: 3401.3
  t5-lottery-dkp: 2836.85
  t5-priority-dkp: 3267.73
  t6-lottery-dkp: 1924.73
  t6-priority-dkp: 10841.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hipon:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3422.21
  t4-priority-dkp: 3417.47
  t5-lottery-dkp: 2619.7
  t5-priority-dkp: 2913.76
  t6-lottery-dkp: 2748.13
  t6-priority-dkp: 9044.66
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Siphon of the Nathrezim
  - Siphon of the Nathrezim
  priority-lootconfig:
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3423.95
  t4-priority-dkp: 3215.24
  t5-lottery-dkp: 2198.25
  t5-priority-dkp: 3066.95
  t6-lottery-dkp: 8693.02
  t6-priority-dkp: 9195.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 170.07
  t4-priority-dkp: 170.07
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3248.9
  t4-priority-dkp: 3213.96
  t5-lottery-dkp: 3103.77
  t5-priority-dkp: 3133.67
  t6-lottery-dkp: 3012.13
  t6-priority-dkp: 8410.08
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3325.13
  t4-priority-dkp: 3295.66
  t5-lottery-dkp: 2798.81
  t5-priority-dkp: 2976.2
  t6-lottery-dkp: 10093.56
  t6-priority-dkp: 10887.04
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Ring of Ancient Knowledge
  - Ring of Omnipotence
  - Tattered Cape of Antonidas
  priority-lootconfig:
  - Shifting Naaru Sliver
  - Sunflare
  rank: Core Raider
  t4-lottery-dkp: 3415.82
  t4-priority-dkp: 3423.57
  t5-lottery-dkp: 2205.76
  t5-priority-dkp: 2299.11
  t6-lottery-dkp: 8484.64
  t6-priority-dkp: 8270.369999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3108.29
  t4-priority-dkp: 3407.42
  t5-lottery-dkp: 2981.26
  t5-priority-dkp: 2548.23
  t6-lottery-dkp: 6381.53
  t6-priority-dkp: 9116.130000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - 'Design: Pendant of Sunfire'
  - Girdle of Mighty Resolve
  - Helm of Burning Righteousness
  - Heroic Judicator's Chestguard
  - Legplates of the Holy Juggernaut
  - Pauldrons of Perseverance
  - Sword Breaker's Bulwark
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Belt of the Forgotten Conqueror
  - Bracers of the Forgotten Conqueror
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3332.75
  t4-priority-dkp: 3422.45
  t5-lottery-dkp: 2484.58
  t5-priority-dkp: 3029.82
  t6-lottery-dkp: 6012.99
  t6-priority-dkp: 7566.84
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 1739.65
  t4-priority-dkp: 1739.65
  t5-lottery-dkp: 1847.94
  t5-priority-dkp: 1847.94
  t6-lottery-dkp: 920.57
  t6-priority-dkp: 920.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3323.62
  t4-priority-dkp: 3247.55
  t5-lottery-dkp: 3202.38
  t5-priority-dkp: 2680.67
  t6-lottery-dkp: 4544.98
  t6-priority-dkp: 9393.3
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3047.87
  t4-priority-dkp: 3036.38
  t5-lottery-dkp: 1571.73
  t5-priority-dkp: 2422.99
  t6-lottery-dkp: 7320.09
  t6-priority-dkp: 9615.09
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2408.86
  t4-priority-dkp: 2377.88
  t5-lottery-dkp: 957.92
  t5-priority-dkp: 2231.08
  t6-lottery-dkp: 5094.21
  t6-priority-dkp: 7328.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3405.35
  t4-priority-dkp: 3420.85
  t5-lottery-dkp: 3114.02
  t5-priority-dkp: 3115.39
  t6-lottery-dkp: 5377.719999999999
  t6-priority-dkp: 10782.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Reminosc:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 137.01
  t4-priority-dkp: 137.01
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 22.86
  t4-priority-dkp: 22.86
  t5-lottery-dkp: 84.36
  t5-priority-dkp: 84.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Black Bow of the Betrayer
  - Cursed Vision of Sargeras
  priority-lootconfig:
  - Insidious Bands
  - Shadowmaster's Boots
  rank: Reserve Raider
  t4-lottery-dkp: 3176.37
  t4-priority-dkp: 2389.48
  t5-lottery-dkp: 2960.18
  t5-priority-dkp: 2901.43
  t6-lottery-dkp: 6517.22
  t6-priority-dkp: 9382.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 116.15
  t4-priority-dkp: 116.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 682.88
  t6-priority-dkp: 682.88
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3256.61
  t4-priority-dkp: 3416.33
  t5-lottery-dkp: 3122.59
  t5-priority-dkp: 3248.44
  t6-lottery-dkp: 5029.190000000001
  t6-priority-dkp: 10867.22
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2296.11
  t4-priority-dkp: 2315.26
  t5-lottery-dkp: 2742.07
  t5-priority-dkp: 2975.14
  t6-lottery-dkp: 6892.34
  t6-priority-dkp: 6221.17
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3376.35
  t4-priority-dkp: 3310.25
  t5-lottery-dkp: 3167.07
  t5-priority-dkp: 3267.73
  t6-lottery-dkp: 6952.3
  t6-priority-dkp: 8352.98
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 52.35
  t4-priority-dkp: 52.35
  t5-lottery-dkp: 90.09
  t5-priority-dkp: 90.09
  t6-lottery-dkp: 52.28
  t6-priority-dkp: 51.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solljus:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 362.33
  t4-priority-dkp: 362.33
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2403.91
  t4-priority-dkp: 2739.51
  t5-lottery-dkp: 2799.88
  t5-priority-dkp: 2381.09
  t6-lottery-dkp: 1276.15
  t6-priority-dkp: 10365.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Book of Highborne Hymns
  - Breeches of Natural Aggression
  - Cover of Ursol the Wise
  - Crystal Spire of Karabor
  - Memento of Tyrande
  - Spaulders of Reclamation
  - Tranquil Majesty Wraps
  priority-lootconfig:
  - Hammer of Sanctification
  rank: Core Raider
  t4-lottery-dkp: 3412.63
  t4-priority-dkp: 3406.76
  t5-lottery-dkp: 2265.28
  t5-priority-dkp: 3129.01
  t6-lottery-dkp: 10178.6
  t6-priority-dkp: 9156.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1352.44
  t4-priority-dkp: 1352.44
  t5-lottery-dkp: 2249.35
  t5-priority-dkp: 2249.35
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3283.91
  t4-priority-dkp: 3329.51
  t5-lottery-dkp: 1118.0
  t5-priority-dkp: 3102.34
  t6-lottery-dkp: 1924.6
  t6-priority-dkp: 10774.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Venatir:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Murumasa
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2915.8
  t4-priority-dkp: 3370.31
  t5-lottery-dkp: 390.67
  t5-priority-dkp: 3297.74
  t6-lottery-dkp: 7834.97
  t6-priority-dkp: 9334.68
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Insignia
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3250.02
  t4-priority-dkp: 3423.64
  t5-lottery-dkp: 2452.31
  t5-priority-dkp: 3297.2
  t6-lottery-dkp: 3748.06
  t6-priority-dkp: 10459.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
