Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3172.36
  t4-priority-dkp: 3163.9
  t5-lottery-dkp: 5844.38
  t5-priority-dkp: 4834.53
  t6-lottery-dkp: 1918.12
  t6-priority-dkp: 8403.54
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3147.35
  t4-priority-dkp: 3183.52
  t5-lottery-dkp: 602.13
  t5-priority-dkp: 5854.18
  t6-lottery-dkp: -17637.0
  t6-priority-dkp: 7848.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 274.51
  t4-priority-dkp: 274.51
  t5-lottery-dkp: 445.76
  t5-priority-dkp: 445.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3021.63
  t4-priority-dkp: 2333.44
  t5-lottery-dkp: 5955.55
  t5-priority-dkp: 6250.94
  t6-lottery-dkp: 5968.11
  t6-priority-dkp: 8511.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2850.93
  t4-priority-dkp: 3183.52
  t5-lottery-dkp: 4697.86
  t5-priority-dkp: 6316.4
  t6-lottery-dkp: 2525.53
  t6-priority-dkp: 7498.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3099.97
  t4-priority-dkp: 3183.82
  t5-lottery-dkp: 4770.66
  t5-priority-dkp: 6317.16
  t6-lottery-dkp: 5134.88
  t6-priority-dkp: 6382.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 3050.92
  t4-priority-dkp: 3050.04
  t5-lottery-dkp: 4738.76
  t5-priority-dkp: 6222.18
  t6-lottery-dkp: 7827.18
  t6-priority-dkp: 8307.95
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3027.61
  t4-priority-dkp: 3005.08
  t5-lottery-dkp: 4925.61
  t5-priority-dkp: 5165.93
  t6-lottery-dkp: 5133.07
  t6-priority-dkp: 8778.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3163.32
  t4-priority-dkp: 3175.16
  t5-lottery-dkp: 4709.88
  t5-priority-dkp: 6309.94
  t6-lottery-dkp: 7123.18
  t6-priority-dkp: 8715.61
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 11.49
  t4-priority-dkp: 13.57
  t5-lottery-dkp: 9.56
  t5-priority-dkp: 11.3
  t6-lottery-dkp: 5.54
  t6-priority-dkp: 6.43
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3181.69
  t4-priority-dkp: 3123.95
  t5-lottery-dkp: 6175.16
  t5-priority-dkp: 5563.86
  t6-lottery-dkp: 3941.26
  t6-priority-dkp: 9247.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 550.3
  t4-priority-dkp: 550.3
  t5-lottery-dkp: 24.3
  t5-priority-dkp: 24.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3184.13
  t4-priority-dkp: 3114.32
  t5-lottery-dkp: 2158.9
  t5-priority-dkp: 5028.29
  t6-lottery-dkp: 7839.93
  t6-priority-dkp: 8723.02
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2900.65
  t4-priority-dkp: 3140.73
  t5-lottery-dkp: 5434.51
  t5-priority-dkp: 6259.94
  t6-lottery-dkp: 945.9100000000001
  t6-priority-dkp: 9594.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3180.78
  t4-priority-dkp: 3171.72
  t5-lottery-dkp: 5018.52
  t5-priority-dkp: 5581.84
  t6-lottery-dkp: -931.27
  t6-priority-dkp: 9681.58
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Sextant of Unstable Currents
  rank: Core Raider
  t4-lottery-dkp: 3184.13
  t4-priority-dkp: 2784.31
  t5-lottery-dkp: 4211.15
  t5-priority-dkp: 5875.32
  t6-lottery-dkp: 5478.52
  t6-priority-dkp: 6442.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 325.8
  t4-priority-dkp: 325.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2848.78
  t4-priority-dkp: 2781.85
  t5-lottery-dkp: 5945.85
  t5-priority-dkp: 6003.13
  t6-lottery-dkp: 342.79
  t6-priority-dkp: 4936.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2994.81
  t4-priority-dkp: 2938.36
  t5-lottery-dkp: 5361.65
  t5-priority-dkp: 5701.46
  t6-lottery-dkp: 8161.53
  t6-priority-dkp: 9681.58
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3168.56
  t4-priority-dkp: 3183.4
  t5-lottery-dkp: 4225.54
  t5-priority-dkp: 4404.39
  t6-lottery-dkp: 5079.33
  t6-priority-dkp: 4668.860000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2579.41
  t4-priority-dkp: 3152.45
  t5-lottery-dkp: 5711.17
  t5-priority-dkp: 4881.62
  t6-lottery-dkp: 5202.68
  t6-priority-dkp: 6289.07
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3009.42
  t4-priority-dkp: 3181.26
  t5-lottery-dkp: 4759.68
  t5-priority-dkp: 5804.18
  t6-lottery-dkp: 5229.43
  t6-priority-dkp: 3321.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1508.25
  t4-priority-dkp: 1508.25
  t5-lottery-dkp: 3540.08
  t5-priority-dkp: 3540.08
  t6-lottery-dkp: 254.86
  t6-priority-dkp: 254.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 2991.91
  t4-priority-dkp: 2846.2
  t5-lottery-dkp: 6134.74
  t5-priority-dkp: 5135.32
  t6-lottery-dkp: 5213.83
  t6-priority-dkp: 6820.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2463.67
  t4-priority-dkp: 2441.67
  t5-lottery-dkp: 3010.94
  t5-priority-dkp: 4641.69
  t6-lottery-dkp: 2848.44
  t6-priority-dkp: 7244.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2706.51
  t4-priority-dkp: 2647.17
  t5-lottery-dkp: 1835.07
  t5-priority-dkp: 4274.05
  t6-lottery-dkp: 5503.69
  t6-priority-dkp: 6254.32
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3148.51
  t4-priority-dkp: 3178.18
  t5-lottery-dkp: 5965.48
  t5-priority-dkp: 5968.12
  t6-lottery-dkp: 2656.87
  t6-priority-dkp: 9480.380000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 262.48
  t4-priority-dkp: 262.48
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 43.81
  t4-priority-dkp: 43.81
  t5-lottery-dkp: 161.61
  t5-priority-dkp: 161.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 2709.83
  t4-priority-dkp: 2830.73
  t5-lottery-dkp: 5670.79
  t5-priority-dkp: 5558.24
  t6-lottery-dkp: 5462.64
  t6-priority-dkp: 6799.62
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 222.51
  t4-priority-dkp: 222.51
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 1308.18
  t6-priority-dkp: 1308.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2863.56
  t4-priority-dkp: 3169.52
  t5-lottery-dkp: 5981.91
  t5-priority-dkp: 6222.99
  t6-lottery-dkp: 4989.18
  t6-priority-dkp: 9643.6
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shroud of the Highborne
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3114.52
  t4-priority-dkp: 3151.19
  t5-lottery-dkp: 5252.95
  t5-priority-dkp: 5699.42
  t6-lottery-dkp: 5558.41
  t6-priority-dkp: 8424.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3092.94
  t4-priority-dkp: 2966.3
  t5-lottery-dkp: 6067.1
  t5-priority-dkp: 6259.94
  t6-lottery-dkp: 6296.09
  t6-priority-dkp: 7827.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 100.29
  t4-priority-dkp: 100.29
  t5-lottery-dkp: 172.59
  t5-priority-dkp: 172.59
  t6-lottery-dkp: 100.16
  t6-priority-dkp: 99.35
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2360.3
  t4-priority-dkp: 3003.2
  t5-lottery-dkp: 5363.7
  t5-priority-dkp: 4561.41
  t6-lottery-dkp: 622.55
  t6-priority-dkp: 8683.15
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3162.45
  t4-priority-dkp: 3151.19
  t5-lottery-dkp: 4339.56
  t5-priority-dkp: 5994.2
  t6-lottery-dkp: 8324.43
  t6-priority-dkp: 6366.22
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2590.85
  t4-priority-dkp: 2590.85
  t5-lottery-dkp: 4309.04
  t5-priority-dkp: 4309.04
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2915.85
  t4-priority-dkp: 3003.2
  t5-lottery-dkp: 2141.73
  t5-priority-dkp: 5943.11
  t6-lottery-dkp: 743.8399999999999
  t6-priority-dkp: 9465.939999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2210.67
  t4-priority-dkp: 3081.37
  t5-lottery-dkp: 748.4
  t5-priority-dkp: 6317.43
  t6-lottery-dkp: 7987.01
  t6-priority-dkp: 6707.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 2850.93
  t4-priority-dkp: 3183.52
  t5-lottery-dkp: 4697.86
  t5-priority-dkp: 6316.4
  t6-lottery-dkp: 890.53
  t6-priority-dkp: 8863.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Tsunami Talisman
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2170.32
  t4-priority-dkp: 2148.79
  t5-lottery-dkp: 5876.81
  t5-priority-dkp: 5003.75
  t6-lottery-dkp: 6784.45
  t6-priority-dkp: 4298.09
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
