Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3654.94
  t4-priority-dkp: 3641.17
  t5-lottery-dkp: 6495.14
  t5-priority-dkp: 4850.76
  t6-lottery-dkp: 142.03
  t6-priority-dkp: 6941.72
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Eternium Shell Bracers
  - Leggings of the Vanquished Defender
  - Praetorian's Legguards
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3614.2
  t4-priority-dkp: 3673.11
  t5-lottery-dkp: 727.19
  t5-priority-dkp: 6511.11
  t6-lottery-dkp: -16532.0
  t6-priority-dkp: 6038.35
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 446.99
  t4-priority-dkp: 446.99
  t5-lottery-dkp: 725.85
  t5-priority-dkp: 725.85
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3409.5
  t4-priority-dkp: 3672.97
  t5-lottery-dkp: 6676.16
  t5-priority-dkp: 7157.17
  t6-lottery-dkp: 7128.26
  t6-priority-dkp: 7118.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2541.54
  t4-priority-dkp: 3083.11
  t5-lottery-dkp: 3448.22
  t5-priority-dkp: 6083.75
  t6-lottery-dkp: 1980.27
  t6-priority-dkp: 5925.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3537.05
  t4-priority-dkp: 3673.59
  t5-lottery-dkp: 4746.77
  t5-priority-dkp: 7264.99
  t6-lottery-dkp: 1619.23
  t6-priority-dkp: 7180.15
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 3457.19
  t4-priority-dkp: 3455.75
  t5-lottery-dkp: 4694.82
  t5-priority-dkp: 7110.33
  t6-lottery-dkp: 8225.880000000001
  t6-priority-dkp: 9008.73
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 49.92
  t5-priority-dkp: 49.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3419.22
  t4-priority-dkp: 3382.54
  t5-lottery-dkp: 6632.29
  t5-priority-dkp: 7023.61
  t6-lottery-dkp: 6501.28
  t6-priority-dkp: 7552.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Madness of the Betrayer
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3640.21
  t4-priority-dkp: 3659.49
  t5-lottery-dkp: 4647.81
  t5-priority-dkp: 7253.24
  t6-lottery-dkp: 4856.86
  t6-priority-dkp: 7449.87
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 18.71
  t4-priority-dkp: 22.09
  t5-lottery-dkp: 15.58
  t5-priority-dkp: 18.41
  t6-lottery-dkp: 9.02
  t6-priority-dkp: 10.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3670.13
  t4-priority-dkp: 3576.09
  t5-lottery-dkp: 7033.75
  t5-priority-dkp: 6038.37
  t6-lottery-dkp: 6734.45
  t6-priority-dkp: 8316.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 896.07
  t4-priority-dkp: 896.07
  t5-lottery-dkp: 39.56
  t5-priority-dkp: 39.56
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3674.11
  t4-priority-dkp: 3560.43
  t5-lottery-dkp: 3262.12
  t5-priority-dkp: 5166.27
  t6-lottery-dkp: 6023.96
  t6-priority-dkp: 7461.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Royal Cloak of the Sunstriders
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3212.49
  t4-priority-dkp: 3603.44
  t5-lottery-dkp: 5827.74
  t5-priority-dkp: 7171.8
  t6-lottery-dkp: -805.0999999999999
  t6-priority-dkp: 8881.21
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3668.64
  t4-priority-dkp: 3653.88
  t5-lottery-dkp: 5150.37
  t5-priority-dkp: 6067.63
  t6-lottery-dkp: 1511.53
  t6-priority-dkp: 9022.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Leggings of the Vanquished Champion
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Ring of Ancient Knowledge
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3674.11
  t4-priority-dkp: 3023.06
  t5-lottery-dkp: 3835.7
  t5-priority-dkp: 6545.52
  t6-lottery-dkp: 2178.8
  t6-priority-dkp: 7277.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 530.5
  t4-priority-dkp: 530.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  rank: Core Raider
  t4-lottery-dkp: 3128.05
  t4-priority-dkp: 3019.06
  t5-lottery-dkp: 6660.38
  t5-priority-dkp: 6753.65
  t6-lottery-dkp: 5276.87
  t6-priority-dkp: 7397.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3365.82
  t4-priority-dkp: 3273.91
  t5-lottery-dkp: 5709.09
  t5-priority-dkp: 6262.42
  t6-lottery-dkp: 6547.64
  t6-priority-dkp: 9022.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Pauldrons of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 3648.74
  t4-priority-dkp: 3672.92
  t5-lottery-dkp: 6880.59
  t5-priority-dkp: 7171.8
  t6-lottery-dkp: 5681.03
  t6-priority-dkp: 5012.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2689.41
  t4-priority-dkp: 3622.52
  t5-lottery-dkp: 6278.24
  t5-priority-dkp: 4927.45
  t6-lottery-dkp: 1729.65
  t6-priority-dkp: 8383.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  rank: Core Raider
  t4-lottery-dkp: 3389.6
  t4-priority-dkp: 3669.42
  t5-lottery-dkp: 4728.88
  t5-priority-dkp: 6429.7
  t6-lottery-dkp: 1773.2
  t6-priority-dkp: 2818.09
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1761.81
  t4-priority-dkp: 1761.81
  t5-lottery-dkp: 4376.190000000001
  t5-priority-dkp: 4376.190000000001
  t6-lottery-dkp: 415.0
  t6-priority-dkp: 415.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3361.09
  t4-priority-dkp: 3123.83
  t5-lottery-dkp: 6967.94
  t5-priority-dkp: 5340.55
  t6-lottery-dkp: 1747.79
  t6-priority-dkp: 8515.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Choker of Serrated Blades
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 2500.95
  t4-priority-dkp: 2465.12
  t5-lottery-dkp: 2697.96
  t5-priority-dkp: 5353.38
  t6-lottery-dkp: 1429.67
  t6-priority-dkp: 8584.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2621.49
  t4-priority-dkp: 2524.87
  t5-lottery-dkp: 1769.8
  t5-priority-dkp: 3388.33
  t6-lottery-dkp: 3620.12
  t6-priority-dkp: 4842.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pudsey:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Shroud of the Highborne
  - Sunshower Light Cloak
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3616.09
  t4-priority-dkp: 3664.4
  t5-lottery-dkp: 6692.33
  t5-priority-dkp: 6696.64
  t6-lottery-dkp: 4693.94
  t6-priority-dkp: 8695.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 427.4
  t4-priority-dkp: 427.4
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 71.33
  t4-priority-dkp: 71.33
  t5-lottery-dkp: 263.15
  t5-priority-dkp: 263.15
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 2901.77
  t4-priority-dkp: 3098.65
  t5-lottery-dkp: 6212.48
  t5-priority-dkp: 6029.21
  t6-lottery-dkp: 2152.94
  t6-priority-dkp: 4329.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 362.33
  t4-priority-dkp: 362.33
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 337.77
  t6-priority-dkp: 337.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3152.1
  t4-priority-dkp: 3650.31
  t5-lottery-dkp: 6719.08
  t5-priority-dkp: 7111.64
  t6-lottery-dkp: 1382.0
  t6-priority-dkp: 8960.94
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3560.75
  t4-priority-dkp: 3620.46
  t5-lottery-dkp: 5532.09
  t5-priority-dkp: 6259.09
  t6-lottery-dkp: 7193.89
  t6-priority-dkp: 6976.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3525.61
  t4-priority-dkp: 3319.39
  t5-lottery-dkp: 6857.81
  t5-priority-dkp: 7171.8
  t6-lottery-dkp: 3510.08
  t6-priority-dkp: 6003.11
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 163.3
  t4-priority-dkp: 163.3
  t5-lottery-dkp: 281.04
  t5-priority-dkp: 281.04
  t6-lottery-dkp: 163.09
  t6-priority-dkp: 161.76
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of Channeled Elements
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  - Tempest of Chaos
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2332.62
  t4-priority-dkp: 3379.49
  t5-lottery-dkp: 5712.44
  t5-priority-dkp: 6758.98
  t6-lottery-dkp: 2134.67
  t6-priority-dkp: 6181.19
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Botanist's Gloves of Growth
  rank: Core Raider
  t4-lottery-dkp: 3638.8
  t4-priority-dkp: 3620.46
  t5-lottery-dkp: 4044.79
  t5-priority-dkp: 6739.11
  t6-lottery-dkp: 6812.9
  t6-priority-dkp: 7153.68
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2708.03
  t4-priority-dkp: 2708.03
  t5-lottery-dkp: 3995.11
  t5-priority-dkp: 3995.11
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Pauldrons of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3237.25
  t4-priority-dkp: 3379.49
  t5-lottery-dkp: 466.0
  t5-priority-dkp: 6655.91
  t6-lottery-dkp: 5704.52
  t6-priority-dkp: 8671.66
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2088.98
  t4-priority-dkp: 3506.77
  t5-lottery-dkp: 3733.53
  t5-priority-dkp: 7265.42
  t6-lottery-dkp: 6263.46
  t6-priority-dkp: 4180.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Ring of Deceitful Intent
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 3131.54
  t4-priority-dkp: 3673.11
  t5-lottery-dkp: 4628.219999999999
  t5-priority-dkp: 7263.75
  t6-lottery-dkp: 3745.27
  t6-priority-dkp: 7690.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2839.9
  t4-priority-dkp: 2804.84
  t5-lottery-dkp: 7242.06
  t5-priority-dkp: 5820.42
  t6-lottery-dkp: 4305.280000000001
  t6-priority-dkp: 5141.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
