Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3696.7
  t4-priority-dkp: 3684.99
  t5-lottery-dkp: 6700.87
  t5-priority-dkp: 5303.15
  t6-lottery-dkp: -1114.27
  t6-priority-dkp: 7665.46
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  - Eternium Shell Bracers
  - Leggings of the Vanquished Defender
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3662.07
  t4-priority-dkp: 3712.14
  t5-lottery-dkp: 1798.11
  t5-priority-dkp: 6714.44
  t6-lottery-dkp: -17767.0
  t6-priority-dkp: 6897.6
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 379.94
  t4-priority-dkp: 379.94
  t5-lottery-dkp: 616.97
  t5-priority-dkp: 616.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3488.07
  t4-priority-dkp: 3712.02
  t5-lottery-dkp: 6854.74
  t5-priority-dkp: 7263.59
  t6-lottery-dkp: 7824.02
  t6-priority-dkp: 7815.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2661.81
  t4-priority-dkp: 3122.14
  t5-lottery-dkp: 3933.99
  t5-priority-dkp: 6174.19
  t6-lottery-dkp: 3183.48
  t6-priority-dkp: 6537.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3596.49
  t4-priority-dkp: 3712.55
  t5-lottery-dkp: 5214.75
  t5-priority-dkp: 7355.24
  t6-lottery-dkp: 3141.35
  t6-priority-dkp: 4868.13
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 3528.61
  t4-priority-dkp: 3527.39
  t5-lottery-dkp: 5170.6
  t5-priority-dkp: 7223.78
  t6-lottery-dkp: 8757.0
  t6-priority-dkp: 9422.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 42.43
  t5-priority-dkp: 42.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3496.34
  t4-priority-dkp: 3465.16
  t5-lottery-dkp: 6817.45
  t5-priority-dkp: 7150.07
  t6-lottery-dkp: 7291.09
  t6-priority-dkp: 8184.53
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3684.18
  t4-priority-dkp: 3700.57
  t5-lottery-dkp: 5130.639999999999
  t5-priority-dkp: 7345.25
  t6-lottery-dkp: 5893.33
  t6-priority-dkp: 8097.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 15.9
  t4-priority-dkp: 18.78
  t5-lottery-dkp: 13.24
  t5-priority-dkp: 15.65
  t6-lottery-dkp: 7.67
  t6-priority-dkp: 8.9
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3709.61
  t4-priority-dkp: 3629.68
  t5-lottery-dkp: 7158.69
  t5-priority-dkp: 6312.61
  t6-lottery-dkp: 1489.28
  t6-priority-dkp: 8833.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 761.66
  t4-priority-dkp: 761.66
  t5-lottery-dkp: 33.63
  t5-priority-dkp: 33.63
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3712.99
  t4-priority-dkp: 3616.37
  t5-lottery-dkp: 3952.8
  t5-priority-dkp: 5571.33
  t6-lottery-dkp: 6885.37
  t6-priority-dkp: 8107.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Royal Cloak of the Sunstriders
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3320.62
  t4-priority-dkp: 3652.92
  t5-lottery-dkp: 6133.58
  t5-priority-dkp: 7276.03
  t6-lottery-dkp: 959.9
  t6-priority-dkp: 9314.03
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3708.34
  t4-priority-dkp: 3695.8
  t5-lottery-dkp: 5557.81
  t5-priority-dkp: 6337.49
  t6-lottery-dkp: 3049.8
  t6-priority-dkp: 9434.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Leggings of the Vanquished Champion
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3712.99
  t4-priority-dkp: 3159.6
  t5-lottery-dkp: 4440.34
  t5-priority-dkp: 6743.69
  t6-lottery-dkp: 3616.98
  t6-priority-dkp: 4950.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 450.93
  t4-priority-dkp: 450.93
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  rank: Core Raider
  t4-lottery-dkp: 3248.84
  t4-priority-dkp: 3156.2
  t5-lottery-dkp: 6841.32
  t5-priority-dkp: 6920.6
  t6-lottery-dkp: 250.34
  t6-priority-dkp: 8052.46
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3450.95
  t4-priority-dkp: 3372.82
  t5-lottery-dkp: 6032.73
  t5-priority-dkp: 6503.06
  t6-lottery-dkp: 7330.49
  t6-priority-dkp: 9434.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kines:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0
  t4-priority-dkp: 0
  t5-lottery-dkp: 1180.0
  t5-priority-dkp: 1180.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Pauldrons of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 3691.43
  t4-priority-dkp: 3711.98
  t5-lottery-dkp: 5848.5
  t5-priority-dkp: 6096.03
  t6-lottery-dkp: 6593.88
  t6-priority-dkp: 6025.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2876.0
  t4-priority-dkp: 3669.14
  t5-lottery-dkp: 6516.5
  t5-priority-dkp: 5368.33
  t6-lottery-dkp: 3235.2
  t6-priority-dkp: 8891.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  rank: Core Raider
  t4-lottery-dkp: 3471.16
  t4-priority-dkp: 3709.01
  t5-lottery-dkp: 5199.55
  t5-priority-dkp: 6645.24
  t6-lottery-dkp: 3272.22
  t6-priority-dkp: 4160.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2087.54
  t4-priority-dkp: 2087.54
  t5-lottery-dkp: 4899.76
  t5-priority-dkp: 4899.76
  t6-lottery-dkp: 352.75
  t6-priority-dkp: 352.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3446.93
  t4-priority-dkp: 3245.26
  t5-lottery-dkp: 7102.75
  t5-priority-dkp: 5719.47
  t6-lottery-dkp: 3250.62
  t6-priority-dkp: 9003.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2715.81
  t4-priority-dkp: 2685.35
  t5-lottery-dkp: 3473.27
  t5-priority-dkp: 5730.37
  t6-lottery-dkp: -19.77999999999997
  t6-priority-dkp: 6061.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2654.54
  t4-priority-dkp: 2572.41
  t5-lottery-dkp: 2356.88
  t5-priority-dkp: 3732.63
  t6-lottery-dkp: 4352.31
  t6-priority-dkp: 5391.24
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Helm of the Forgotten Protector
  - Sunshower Light Cloak
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3663.68
  t4-priority-dkp: 3704.74
  t5-lottery-dkp: 6868.48
  t5-priority-dkp: 6872.14
  t6-lottery-dkp: -245.15
  t6-priority-dkp: 9155.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 363.29
  t4-priority-dkp: 363.29
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 60.63
  t4-priority-dkp: 60.63
  t5-lottery-dkp: 223.68
  t5-priority-dkp: 223.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 3056.5
  t4-priority-dkp: 3223.85
  t5-lottery-dkp: 6460.61
  t5-priority-dkp: 6304.83
  t6-lottery-dkp: 3595.0
  t6-priority-dkp: 5445.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 987.1
  t6-priority-dkp: 987.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3269.28
  t4-priority-dkp: 3692.76
  t5-lottery-dkp: 6891.22
  t5-priority-dkp: 7224.89
  t6-lottery-dkp: 2939.7
  t6-priority-dkp: 9381.8
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3616.64
  t4-priority-dkp: 3667.39
  t5-lottery-dkp: 5882.28
  t5-priority-dkp: 6500.23
  t6-lottery-dkp: 7879.81
  t6-priority-dkp: 7695.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3586.77
  t4-priority-dkp: 3411.48
  t5-lottery-dkp: 7009.14
  t5-priority-dkp: 7276.03
  t6-lottery-dkp: 4748.57
  t6-priority-dkp: 6867.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 138.81
  t4-priority-dkp: 138.81
  t5-lottery-dkp: 238.88
  t5-priority-dkp: 238.88
  t6-lottery-dkp: 138.63
  t6-priority-dkp: 137.5
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2572.73
  t4-priority-dkp: 3462.57
  t5-lottery-dkp: 6035.57
  t5-priority-dkp: 4925.13
  t6-lottery-dkp: 579.47
  t6-priority-dkp: 7019.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3682.98
  t4-priority-dkp: 3667.39
  t5-lottery-dkp: 4618.07
  t5-priority-dkp: 6908.24
  t6-lottery-dkp: 7555.96
  t6-priority-dkp: 4845.63
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2891.83
  t4-priority-dkp: 2891.83
  t5-lottery-dkp: 4575.84
  t5-priority-dkp: 4575.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3341.66
  t4-priority-dkp: 3462.57
  t5-lottery-dkp: 1576.1
  t5-priority-dkp: 6837.52
  t6-lottery-dkp: -2386.16
  t6-priority-dkp: 9135.91
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2365.63
  t4-priority-dkp: 3570.75
  t5-lottery-dkp: 4353.5
  t5-priority-dkp: 7355.61
  t6-lottery-dkp: 7088.94
  t6-priority-dkp: 5318.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Madness of the Betrayer
  - Ring of Deceitful Intent
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 3251.81
  t4-priority-dkp: 3712.14
  t5-lottery-dkp: 5113.99
  t5-priority-dkp: 7354.19
  t6-lottery-dkp: 4948.48
  t6-priority-dkp: 8302.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3003.91
  t4-priority-dkp: 2974.11
  t5-lottery-dkp: 6745.75
  t5-priority-dkp: 5537.36
  t6-lottery-dkp: 5424.49
  t6-priority-dkp: 6135.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
