Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3762.36
  t4-priority-dkp: 3753.9
  t5-lottery-dkp: 5844.38
  t5-priority-dkp: 4834.53
  t6-lottery-dkp: 2318.12
  t6-priority-dkp: 8803.54
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3737.35
  t4-priority-dkp: 3773.52
  t5-lottery-dkp: 602.13
  t5-priority-dkp: 5854.18
  t6-lottery-dkp: -17237.0
  t6-priority-dkp: 8248.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 274.51
  t4-priority-dkp: 274.51
  t5-lottery-dkp: 445.76
  t5-priority-dkp: 445.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3611.63
  t4-priority-dkp: 2923.44
  t5-lottery-dkp: 5955.55
  t5-priority-dkp: 6250.94
  t6-lottery-dkp: 6368.11
  t6-priority-dkp: 8911.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2850.93
  t4-priority-dkp: 3183.52
  t5-lottery-dkp: 4697.86
  t5-priority-dkp: 6316.4
  t6-lottery-dkp: 2525.53
  t6-priority-dkp: 7498.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3689.97
  t4-priority-dkp: 3773.82
  t5-lottery-dkp: 4770.66
  t5-priority-dkp: 6317.16
  t6-lottery-dkp: 5534.88
  t6-priority-dkp: 6782.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 3640.92
  t4-priority-dkp: 3640.04
  t5-lottery-dkp: 4738.76
  t5-priority-dkp: 6222.18
  t6-lottery-dkp: 9592.18
  t6-priority-dkp: 10072.95
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3617.61
  t4-priority-dkp: 3595.08
  t5-lottery-dkp: 4925.61
  t5-priority-dkp: 5165.93
  t6-lottery-dkp: 5533.07
  t6-priority-dkp: 6178.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3753.32
  t4-priority-dkp: 3765.16
  t5-lottery-dkp: 4709.88
  t5-priority-dkp: 6309.94
  t6-lottery-dkp: 7523.18
  t6-priority-dkp: 9115.61
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 11.49
  t4-priority-dkp: 13.57
  t5-lottery-dkp: 9.56
  t5-priority-dkp: 11.3
  t6-lottery-dkp: 5.54
  t6-priority-dkp: 6.43
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3771.69
  t4-priority-dkp: 3713.95
  t5-lottery-dkp: 6175.16
  t5-priority-dkp: 5563.86
  t6-lottery-dkp: 4341.26
  t6-priority-dkp: 9647.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 550.3
  t4-priority-dkp: 550.3
  t5-lottery-dkp: 24.3
  t5-priority-dkp: 24.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3774.13
  t4-priority-dkp: 3704.32
  t5-lottery-dkp: 2158.9
  t5-priority-dkp: 5028.29
  t6-lottery-dkp: 8239.93
  t6-priority-dkp: 9123.02
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3490.65
  t4-priority-dkp: 3730.73
  t5-lottery-dkp: 5434.51
  t5-priority-dkp: 6259.94
  t6-lottery-dkp: 1345.91
  t6-priority-dkp: 9994.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Scepter of Purification
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3770.78
  t4-priority-dkp: 3761.72
  t5-lottery-dkp: 5018.52
  t5-priority-dkp: 5581.84
  t6-lottery-dkp: -531.27
  t6-priority-dkp: 10081.58
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3774.13
  t4-priority-dkp: 3374.31
  t5-lottery-dkp: 4211.15
  t5-priority-dkp: 5875.32
  t6-lottery-dkp: 5878.52
  t6-priority-dkp: 6842.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 325.8
  t4-priority-dkp: 325.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3438.78
  t4-priority-dkp: 3371.85
  t5-lottery-dkp: 5945.85
  t5-priority-dkp: 6003.13
  t6-lottery-dkp: 742.79
  t6-priority-dkp: 5336.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3584.81
  t4-priority-dkp: 3528.36
  t5-lottery-dkp: 5361.65
  t5-priority-dkp: 5701.46
  t6-lottery-dkp: 8561.529999999999
  t6-priority-dkp: 10081.58
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3758.56
  t4-priority-dkp: 3773.4
  t5-lottery-dkp: 4225.54
  t5-priority-dkp: 4404.39
  t6-lottery-dkp: 5479.33
  t6-priority-dkp: 5068.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3169.41
  t4-priority-dkp: 3742.45
  t5-lottery-dkp: 5711.17
  t5-priority-dkp: 4881.62
  t6-lottery-dkp: 5602.68
  t6-priority-dkp: 6689.07
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3599.42
  t4-priority-dkp: 3771.26
  t5-lottery-dkp: 4759.68
  t5-priority-dkp: 5804.18
  t6-lottery-dkp: 5629.43
  t6-priority-dkp: 3721.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1508.25
  t4-priority-dkp: 1508.25
  t5-lottery-dkp: 3540.08
  t5-priority-dkp: 3540.08
  t6-lottery-dkp: 254.86
  t6-priority-dkp: 254.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3581.91
  t4-priority-dkp: 3436.2
  t5-lottery-dkp: 6134.74
  t5-priority-dkp: 5135.32
  t6-lottery-dkp: 5613.83
  t6-priority-dkp: 7220.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3053.67
  t4-priority-dkp: 3031.67
  t5-lottery-dkp: 3010.94
  t5-priority-dkp: 4641.69
  t6-lottery-dkp: 3248.44
  t6-priority-dkp: 7644.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2706.51
  t4-priority-dkp: 2647.17
  t5-lottery-dkp: 1835.07
  t5-priority-dkp: 4274.05
  t6-lottery-dkp: 5503.69
  t6-priority-dkp: 6254.32
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3738.51
  t4-priority-dkp: 3768.18
  t5-lottery-dkp: 5965.48
  t5-priority-dkp: 5968.12
  t6-lottery-dkp: 3056.87
  t6-priority-dkp: 9880.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 262.48
  t4-priority-dkp: 262.48
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 43.81
  t4-priority-dkp: 43.81
  t5-lottery-dkp: 161.61
  t5-priority-dkp: 161.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 3299.83
  t4-priority-dkp: 3420.73
  t5-lottery-dkp: 5670.79
  t5-priority-dkp: 5558.24
  t6-lottery-dkp: 5862.64
  t6-priority-dkp: 7199.62
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 222.51
  t4-priority-dkp: 222.51
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 1308.18
  t6-priority-dkp: 1308.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3453.56
  t4-priority-dkp: 3759.52
  t5-lottery-dkp: 5981.91
  t5-priority-dkp: 6222.99
  t6-lottery-dkp: 2389.18
  t6-priority-dkp: 10043.6
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shroud of the Highborne
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3704.52
  t4-priority-dkp: 3741.19
  t5-lottery-dkp: 5252.95
  t5-priority-dkp: 5699.42
  t6-lottery-dkp: 5958.41
  t6-priority-dkp: 8824.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3682.94
  t4-priority-dkp: 3556.3
  t5-lottery-dkp: 6067.1
  t5-priority-dkp: 6259.94
  t6-lottery-dkp: 6696.09
  t6-priority-dkp: 5227.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 100.29
  t4-priority-dkp: 100.29
  t5-lottery-dkp: 172.59
  t5-priority-dkp: 172.59
  t6-lottery-dkp: 100.16
  t6-priority-dkp: 99.35
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2950.3
  t4-priority-dkp: 3593.2
  t5-lottery-dkp: 5363.7
  t5-priority-dkp: 4561.41
  t6-lottery-dkp: 1022.55
  t6-priority-dkp: 9083.15
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3752.45
  t4-priority-dkp: 3741.19
  t5-lottery-dkp: 4339.56
  t5-priority-dkp: 5994.2
  t6-lottery-dkp: 8724.43
  t6-priority-dkp: 6766.22
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2590.85
  t4-priority-dkp: 2590.85
  t5-lottery-dkp: 4309.04
  t5-priority-dkp: 4309.04
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Gloves of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3505.85
  t4-priority-dkp: 3593.2
  t5-lottery-dkp: 2141.73
  t5-priority-dkp: 5943.11
  t6-lottery-dkp: -1856.16
  t6-priority-dkp: 9865.94
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Insidious Bands
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2800.67
  t4-priority-dkp: 3671.37
  t5-lottery-dkp: 748.4
  t5-priority-dkp: 6317.43
  t6-lottery-dkp: 8387.01
  t6-priority-dkp: 7107.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 3440.93
  t4-priority-dkp: 3773.52
  t5-lottery-dkp: 4697.86
  t5-priority-dkp: 6316.4
  t6-lottery-dkp: 1290.53
  t6-priority-dkp: 9263.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2760.32
  t4-priority-dkp: 2738.79
  t5-lottery-dkp: 5876.81
  t5-priority-dkp: 5003.75
  t6-lottery-dkp: 4184.45
  t6-priority-dkp: 4698.09
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
