Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3670.14
  t4-priority-dkp: 3451.92
  t5-lottery-dkp: 3066.36
  t5-priority-dkp: 65.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Phoenix-Wing Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3024.64
  t4-priority-dkp: 3958.1
  t5-lottery-dkp: -12152.81
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 29.41
  t4-priority-dkp: 29.41
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Tsunami Talisman
  rank: Core Raider
  t4-lottery-dkp: 2034.98
  t4-priority-dkp: 3955.97
  t5-lottery-dkp: 5063.65
  t5-priority-dkp: 4920.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2916.85
  t4-priority-dkp: 3088.93
  t5-lottery-dkp: 2873.12
  t5-priority-dkp: 5455.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Girdle of the Endless Pit
  - Gloves of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2978.85
  t4-priority-dkp: 3965.67
  t5-lottery-dkp: 1674.77
  t5-priority-dkp: 6629.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3533.89
  t4-priority-dkp: 3511.08
  t5-lottery-dkp: 4833.11
  t5-priority-dkp: 6246.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 330.0
  t5-priority-dkp: 330.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  - Pit Lord's Satchel
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Reserve Raider
  t4-lottery-dkp: 2634.53
  t4-priority-dkp: 3156.53
  t5-lottery-dkp: 5450.59
  t5-priority-dkp: 5450.59
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3941.0
  t4-priority-dkp: 3359.81
  t5-lottery-dkp: -118.13
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 3436.81
  t4-priority-dkp: 3742.32
  t5-lottery-dkp: 2980.72
  t5-priority-dkp: 6442.83
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 296.44
  t4-priority-dkp: 350.08
  t5-lottery-dkp: 246.92
  t5-priority-dkp: 291.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3910.83
  t4-priority-dkp: 2420.93
  t5-lottery-dkp: 5733.45
  t5-priority-dkp: 6485.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Leggings of the Vanquished Champion
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Magtheridon's Head
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3973.93
  t4-priority-dkp: 3349.16
  t5-lottery-dkp: 3707.67
  t5-priority-dkp: 6550.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2605.51
  t4-priority-dkp: 2854.08
  t5-lottery-dkp: 958.59
  t5-priority-dkp: 5090.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 1424.5
  t4-priority-dkp: 3910.83
  t5-lottery-dkp: 2421.85
  t5-priority-dkp: 4808.63
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Gauntlets of the Sun King
  - Helm of the Vanquished Hero
  - Velvet Boots of the Guardian
  priority-lootconfig:
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 2961.14
  t4-priority-dkp: 1877.79
  t5-lottery-dkp: -375.5700000000001
  t5-priority-dkp: 5551.24
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3887.34
  t4-priority-dkp: 3653.36
  t5-lottery-dkp: 1219.89
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 3973.93
  t4-priority-dkp: 3388.82
  t5-lottery-dkp: 5994.77
  t5-priority-dkp: 5284.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 3727.42
  t4-priority-dkp: 3177.19
  t5-lottery-dkp: 2352.33
  t5-priority-dkp: 3830.12
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Fang of Vashj
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3801.85
  t4-priority-dkp: 3973.93
  t5-lottery-dkp: 4053.12
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 245.15
  t5-priority-dkp: 245.15
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Mindstorm Wristbands
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3571.93
  t4-priority-dkp: 3954.94
  t5-lottery-dkp: 5659.72
  t5-priority-dkp: 6629.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 3135.91
  t4-priority-dkp: 3899.69
  t5-lottery-dkp: -313.48
  t5-priority-dkp: 5345.88
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Pit Lord's Satchel
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3726.92
  t4-priority-dkp: 3224.36
  t5-lottery-dkp: 6430.12
  t5-priority-dkp: 4630.8
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3136.34
  t4-priority-dkp: 2568.49
  t5-lottery-dkp: 3206.43
  t5-priority-dkp: 6528.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2279.34
  t4-priority-dkp: 2279.34
  t5-lottery-dkp: 626.73
  t5-priority-dkp: 626.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 3428.72
  t5-priority-dkp: 3428.72
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3054.63
  t4-priority-dkp: 3820.08
  t5-lottery-dkp: 2676.72
  t5-priority-dkp: 5962.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 754.28
  t4-priority-dkp: 817.4
  t5-lottery-dkp: 860.37
  t5-priority-dkp: 912.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  priority-lootconfig:
  - Dragonspine Trophy
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 3156.53
  t4-priority-dkp: 3156.53
  t5-lottery-dkp: 2377.84
  t5-priority-dkp: 3522.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 146.42
  t5-priority-dkp: 146.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Eye of Gruul
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3354.31
  t4-priority-dkp: 3123.93
  t5-lottery-dkp: 1019.29
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  - Pit Lord's Satchel
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3973.93
  t4-priority-dkp: 3432.93
  t5-lottery-dkp: 2945.93
  t5-priority-dkp: 6090.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 2587.43
  t4-priority-dkp: 2587.43
  t5-lottery-dkp: 4452.92
  t5-priority-dkp: 4452.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 3581.62
  t4-priority-dkp: 3878.33
  t5-lottery-dkp: 4609.05
  t5-priority-dkp: 5512.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3414.42
  t4-priority-dkp: 3123.93
  t5-lottery-dkp: 1333.06
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Leggings of the Vanquished Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2973.93
  t4-priority-dkp: 3973.93
  t5-lottery-dkp: 799.72
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2916.85
  t4-priority-dkp: 3088.93
  t5-lottery-dkp: 2873.12
  t5-priority-dkp: 5455.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Helm of the Vanquished Defender
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3648.06
  t4-priority-dkp: 3958.1
  t5-lottery-dkp: 6364.24
  t5-priority-dkp: 6609.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3973.93
  t4-priority-dkp: 3596.79
  t5-lottery-dkp: 1236.18
  t5-priority-dkp: 4935.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3529.61
  t4-priority-dkp: 2973.93
  t5-lottery-dkp: 6265.66
  t5-priority-dkp: 6635.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
