Abjection:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Infamy
  - Boundless Agony
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Cursed Vision of Sargeras
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Leggings of the Forgotten Protector
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  - Stormrage Signet Ring
  - Thalassian Wildercloak
  priority-lootconfig:
  - Bristleblitz Striker
  rank: Core Raider
  t4-lottery-dkp: 3889.29
  t4-priority-dkp: 3852.78
  t5-lottery-dkp: 5618.37
  t5-priority-dkp: 6561.27
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Band of the Abyssal Lord
  - Bulwark of Azzinoth
  - Chestguard of the Forgotten Protector
  - Eternium Shell Bracers
  - Faceplate of the Impenetrable
  - Gauntlets of Enforcement
  - Leggings of the Forgotten Protector
  - Legionkiller
  - Myrmidon's Treads
  - Pauldrons of the Forgotten Protector
  - Pendant of Titans
  - Pepe's Shroud of Pacification
  - Ring of Deceitful Intent
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3781.27
  t4-priority-dkp: 3937.48
  t5-lottery-dkp: -3172.81
  t5-priority-dkp: 5660.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1185.19
  t4-priority-dkp: 1185.19
  t5-lottery-dkp: 1924.58
  t5-priority-dkp: 1924.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of Devastation
  - Band of the Ranger-General
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Shadowmoon Destroyer's Drape
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Dreadboots of the Legion
  rank: Core Raider
  t4-lottery-dkp: 3238.51
  t4-priority-dkp: 3937.11
  t5-lottery-dkp: 6098.33
  t5-priority-dkp: 7373.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Cataclysm's Edge
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Leggings of Divine Retribution
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3576.73
  t4-priority-dkp: 3938.74
  t5-lottery-dkp: 6285.52
  t5-priority-dkp: 7659.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Helm of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3364.99
  t4-priority-dkp: 3361.17
  t5-lottery-dkp: 3959.02
  t5-priority-dkp: 7595.53
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 132.35
  t5-priority-dkp: 132.35
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Chestguard of the Forgotten Vanquisher
  - Gloves of the Forgotten Vanquisher
  - Leggings of the Forgotten Vanquisher
  - Pauldrons of the Forgotten Vanquisher
  - Stormrage Signet Ring
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Blade of Infamy
  - Cursed Vision of Sargeras
  - Insidious Bands
  rank: Core Raider
  t4-lottery-dkp: 3264.3
  t4-priority-dkp: 3167.05
  t5-lottery-dkp: 5982.0
  t5-priority-dkp: 7019.56
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Bow-stitched Leggings
  - Fists of Mukoa
  - Madness of the Betrayer
  - Midnight Chestguard
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3850.24
  t4-priority-dkp: 3901.37
  t5-lottery-dkp: 4551.59
  t5-priority-dkp: 7628.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 49.6
  t4-priority-dkp: 58.59
  t5-lottery-dkp: 41.33
  t5-priority-dkp: 48.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Nexus Key
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3929.57
  t4-priority-dkp: 3680.24
  t5-lottery-dkp: 7046.45
  t5-priority-dkp: 4407.22
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Don Alejandro's Money Belt
  - Leggings of the Forgotten Vanquisher
  - Ring of Deceitful Intent
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Helm of the Forgotten Vanquisher
  rank: Core Raider
  t4-lottery-dkp: 3940.12
  t4-priority-dkp: 3638.69
  t5-lottery-dkp: 5548.69
  t5-priority-dkp: 6602.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Devastation
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  - Waistwrap of Infinity
  priority-lootconfig:
  - Ring of Ancient Knowledge
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2716.14
  t4-priority-dkp: 3752.73
  t5-lottery-dkp: 3848.75
  t5-priority-dkp: 7008.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Crystal Spire of Karabor
  - Earring of Soulful Meditation
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Lightfathom Scepter
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3925.64
  t4-priority-dkp: 3886.48
  t5-lottery-dkp: 5309.38
  t5-priority-dkp: 7660.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3940.12
  t4-priority-dkp: 3842.21
  t5-lottery-dkp: 6871.4
  t5-priority-dkp: 5751.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Captured Storms
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 3308.87
  t4-priority-dkp: 3019.91
  t5-lottery-dkp: 6056.47
  t5-priority-dkp: 6303.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3122.72
  t4-priority-dkp: 2879.02
  t5-lottery-dkp: 6193.59
  t5-priority-dkp: 7660.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Gloves of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - The Nexus Key
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3872.86
  t4-priority-dkp: 3936.95
  t5-lottery-dkp: 6640.37
  t5-priority-dkp: 7659.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cuffs of Devastation
  - Leggings of the Forgotten Vanquisher
  - Slippers of the Seacaller
  - Waistwrap of Infinity
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 1329.24
  t4-priority-dkp: 3803.34
  t5-lottery-dkp: 5043.23
  t5-priority-dkp: 4718.34
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Antonidas's Aegis of Rapt Concentration
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - Hammer of Judgement
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  rank: Core Raider
  t4-lottery-dkp: 3185.76
  t4-priority-dkp: 3927.7
  t5-lottery-dkp: 935.16
  t5-priority-dkp: 5444.83
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3110.19
  t4-priority-dkp: 2481.1
  t5-lottery-dkp: 6871.97
  t5-priority-dkp: 5325.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Deadly Cuffs
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  - Unstoppable Aggressor's Ring
  priority-lootconfig:
  - Dragonspine Trophy
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 2920.52
  t4-priority-dkp: 2825.49
  t5-lottery-dkp: 3109.44
  t5-priority-dkp: 5642.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2375.9
  t4-priority-dkp: 2375.9
  t5-lottery-dkp: 104.88
  t5-priority-dkp: 104.88
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pudsey:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shroud of the Highborne
  - Sunshower Light Cloak
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3786.29
  t4-priority-dkp: 3914.38
  t5-lottery-dkp: 6141.18
  t5-priority-dkp: 6152.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1133.22
  t4-priority-dkp: 1133.22
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 189.13
  t4-priority-dkp: 189.13
  t5-lottery-dkp: 697.72
  t5-priority-dkp: 697.72
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  priority-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Dragonspine Trophy
  - Madness of the Betrayer
  rank: Reserve Raider
  t4-lottery-dkp: 2708.91
  t4-priority-dkp: 3230.92
  t5-lottery-dkp: 5491.74
  t5-priority-dkp: 5005.780000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Eye of Gruul
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Nadina's Pendant of Purity
  - Pauldrons of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3940.12
  t4-priority-dkp: 3877.01
  t5-lottery-dkp: 6212.12
  t5-priority-dkp: 7376.23
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3639.56
  t4-priority-dkp: 3797.88
  t5-lottery-dkp: 5325.36
  t5-priority-dkp: 6721.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Forgotten Vanquisher
  - Helm of the Forgotten Vanquisher
  - Leggings of Channeled Elements
  - Pauldrons of the Forgotten Vanquisher
  - Slippers of the Seacaller
  - The Skull of Gul'dan
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3546.38
  t4-priority-dkp: 2999.6
  t5-lottery-dkp: 6579.97
  t5-priority-dkp: 7569.51
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 432.99
  t4-priority-dkp: 432.99
  t5-lottery-dkp: 745.16
  t5-priority-dkp: 745.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2636.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 3543.05
  t5-priority-dkp: 6317.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Belt of Primal Majesty
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Crystal Spire of Karabor
  - Leggings of Eternity
  - Memento of Tyrande
  - Scepter of Purification
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3846.5
  t4-priority-dkp: 3797.88
  t5-lottery-dkp: 4657.65
  t5-priority-dkp: 6265.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1378.6
  t4-priority-dkp: 1378.6
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Bracers of Martyrdom
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  priority-lootconfig:
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2781.81
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: -3434.0
  t5-priority-dkp: 6044.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Infamy
  - Blade of Savagery
  - Insidious Bands
  - Stormrage Signet Ring
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3772.77
  t4-priority-dkp: 3496.42
  t5-lottery-dkp: 4895.55
  t5-priority-dkp: 7660.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Forgotten Vanquisher
  - Gloves of the Forgotten Vanquisher
  - Leggings of the Forgotten Vanquisher
  - Pauldrons of the Forgotten Vanquisher
  rank: Core Raider
  t4-lottery-dkp: 3885.6
  t4-priority-dkp: 3937.48
  t5-lottery-dkp: 5175.780000000001
  t5-priority-dkp: 7656.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Forgotten Protector
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 1728.25
  t4-priority-dkp: 1635.27
  t5-lottery-dkp: 7598.75
  t5-priority-dkp: 7660.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
