Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2570.75
  t4-priority-dkp: 2268.72
  t5-lottery-dkp: 42.65
  t5-priority-dkp: 1010.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - Royal Gauntlets of Silvermoon
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1677.32
  t4-priority-dkp: 2969.31
  t5-lottery-dkp: -7692.81
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 40.71
  t4-priority-dkp: 40.71
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 1691.64
  t4-priority-dkp: 2966.35
  t5-lottery-dkp: 2807.06
  t5-priority-dkp: 4962.46
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2753.05
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 1408.4
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Fallen Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2613.94
  t4-priority-dkp: 2979.79
  t5-lottery-dkp: 2469.51
  t5-priority-dkp: 4973.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 2382.16
  t4-priority-dkp: 2350.6
  t5-lottery-dkp: 2487.98
  t5-priority-dkp: 4444.11
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  - Pit Lord's Satchel
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Reserve Raider
  t4-lottery-dkp: 1137.38
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 3342.61
  t5-priority-dkp: 3342.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Gloves of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2945.63
  t4-priority-dkp: 2141.22
  t5-lottery-dkp: 756.15
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2247.8
  t4-priority-dkp: 2670.65
  t5-lottery-dkp: -75.89
  t5-priority-dkp: 4715.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 410.29
  t4-priority-dkp: 484.54
  t5-lottery-dkp: 341.76
  t5-priority-dkp: 403.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2903.88
  t4-priority-dkp: 2018.21
  t5-lottery-dkp: 4910.59
  t5-priority-dkp: 4774.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Magtheridon's Head
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2126.48
  t5-lottery-dkp: 3283.21
  t5-priority-dkp: 4864.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 1097.21
  t4-priority-dkp: 2825.34
  t5-lottery-dkp: -581.41
  t5-priority-dkp: 4844.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Pit Lord's Satchel
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 2230.77
  t4-priority-dkp: 2903.88
  t5-lottery-dkp: 1150.59
  t5-priority-dkp: 2454.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  priority-lootconfig:
  - Pit Lord's Satchel
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 1589.44
  t4-priority-dkp: 2442.93
  t5-lottery-dkp: 2307.57
  t5-priority-dkp: 3481.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2871.38
  t4-priority-dkp: 2547.52
  t5-lottery-dkp: 255.14
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2181.38
  t5-lottery-dkp: 4095.8
  t5-priority-dkp: 3112.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2650.02
  t4-priority-dkp: 2888.46
  t5-lottery-dkp: 2999.0
  t5-priority-dkp: 3452.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Fang of Vashj
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2753.05
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 1408.4
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 339.3
  t5-priority-dkp: 339.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Mindstorm Wristbands
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2434.82
  t4-priority-dkp: 2964.94
  t5-lottery-dkp: 3632.07
  t5-priority-dkp: 4973.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 1831.33
  t4-priority-dkp: 2888.46
  t5-lottery-dkp: -1764.09
  t5-priority-dkp: 3197.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - Pit Lord's Satchel
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2649.33
  t4-priority-dkp: 1953.75
  t5-lottery-dkp: 4698.37
  t5-priority-dkp: 2207.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Rod of the Sun King
  - Serpent Spine Longbow
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2421.92
  t4-priority-dkp: 2812.45
  t5-lottery-dkp: 2236.52
  t5-priority-dkp: 4834.19
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1235.76
  t4-priority-dkp: 1235.76
  t5-lottery-dkp: 410.69
  t5-priority-dkp: 410.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 1400.93
  t5-priority-dkp: 1400.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2895.3
  t4-priority-dkp: 2778.28
  t5-lottery-dkp: 1503.35
  t5-priority-dkp: 4051.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1043.99
  t4-priority-dkp: 1131.35
  t5-lottery-dkp: 1190.82
  t5-priority-dkp: 1263.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  priority-lootconfig:
  - Dragonspine Trophy
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 3342.61
  t5-priority-dkp: 3342.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 202.66
  t5-priority-dkp: 202.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Lightfathom Scepter
  - Helm of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Aegis of the Vindicator
  - Eye of Gruul
  rank: Core Raider
  t4-lottery-dkp: 2133.61
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: -22.51
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2242.44
  t5-lottery-dkp: 4228.91
  t5-priority-dkp: 4228.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 4983.21
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 2448.23
  t4-priority-dkp: 2858.89
  t5-lottery-dkp: 4530.8
  t5-priority-dkp: 3427.85
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2216.81
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 3820.07
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Band of the Ranger-General
  - Leggings of the Vanquished Champion
  - Magtheridon's Head
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: -326.41
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2753.05
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 1408.4
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2540.19
  t4-priority-dkp: 2969.31
  t5-lottery-dkp: 4607.19
  t5-priority-dkp: 4946.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2991.22
  t4-priority-dkp: 2469.22
  t5-lottery-dkp: -293.9
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2376.25
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 4470.74
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
