Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boneweave Girdle
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Endless Nightmares
  - Insidious Bands
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3326.84
  t4-priority-dkp: 3321.64
  t5-lottery-dkp: 3589.18
  t5-priority-dkp: 2969.01
  t6-lottery-dkp: 3796.58
  t6-priority-dkp: 9946.94
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Cataclysm's Edge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3311.48
  t4-priority-dkp: 3333.69
  t5-lottery-dkp: 369.78
  t5-priority-dkp: 3595.19
  t6-lottery-dkp: -12002.0
  t6-priority-dkp: 7438.73
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 168.58
  t4-priority-dkp: 168.58
  t5-lottery-dkp: 273.75
  t5-priority-dkp: 273.75
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3234.27
  t4-priority-dkp: 2811.63
  t5-lottery-dkp: 3657.46
  t5-priority-dkp: 3838.86
  t6-lottery-dkp: 6283.78
  t6-priority-dkp: 10013.44
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2539.43
  t4-priority-dkp: 2743.69
  t5-lottery-dkp: 2885.07
  t5-priority-dkp: 3879.06
  t6-lottery-dkp: 3228.01
  t6-priority-dkp: 8124.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3282.38
  t4-priority-dkp: 3333.88
  t5-lottery-dkp: 2929.78
  t5-priority-dkp: 3879.53
  t6-lottery-dkp: 7939.57
  t6-priority-dkp: 8705.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 2235.98
  t4-priority-dkp: 2235.44
  t5-lottery-dkp: 2910.2
  t5-priority-dkp: 3821.19
  t6-lottery-dkp: 5890.8
  t6-priority-dkp: 6186.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3237.94
  t4-priority-dkp: 3224.11
  t5-lottery-dkp: 3024.94
  t5-priority-dkp: 3172.52
  t6-lottery-dkp: 7938.46
  t6-priority-dkp: 6167.37
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3321.28
  t4-priority-dkp: 3328.56
  t5-lottery-dkp: 2892.46
  t5-priority-dkp: 3875.09
  t6-lottery-dkp: 9160.63
  t6-priority-dkp: 10138.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 7.06
  t4-priority-dkp: 8.33
  t5-lottery-dkp: 5.87
  t5-priority-dkp: 6.94
  t6-lottery-dkp: 3.4
  t6-priority-dkp: 3.95
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demacian:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3332.57
  t4-priority-dkp: 3297.11
  t5-lottery-dkp: 3792.33
  t5-priority-dkp: 3416.91
  t6-lottery-dkp: -1343.46
  t6-priority-dkp: 10465.32
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 337.95
  t4-priority-dkp: 337.95
  t5-lottery-dkp: 14.93
  t5-priority-dkp: 14.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3334.06
  t4-priority-dkp: 3291.19
  t5-lottery-dkp: 1325.84
  t5-priority-dkp: 3088.0
  t6-lottery-dkp: 7050.81
  t6-priority-dkp: 10143.14
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3159.97
  t4-priority-dkp: 3307.41
  t5-lottery-dkp: 3337.47
  t5-priority-dkp: 3844.39
  t6-lottery-dkp: 187.92
  t6-priority-dkp: 10678.41
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hipon:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3332.01
  t4-priority-dkp: 3326.44
  t5-lottery-dkp: 3082.0
  t5-priority-dkp: 3427.95
  t6-lottery-dkp: 1156.62
  t6-priority-dkp: 8564.31
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3334.06
  t4-priority-dkp: 3088.52
  t5-lottery-dkp: 2586.18
  t5-priority-dkp: 3608.18
  t6-lottery-dkp: 8150.61
  t6-priority-dkp: 8742.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 200.08
  t4-priority-dkp: 200.08
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3128.12
  t4-priority-dkp: 3087.01
  t5-lottery-dkp: 3651.49
  t5-priority-dkp: 3686.67
  t6-lottery-dkp: 4996.62
  t6-priority-dkp: 7817.74
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3217.8
  t4-priority-dkp: 3183.13
  t5-lottery-dkp: 3292.72
  t5-priority-dkp: 3501.41
  t6-lottery-dkp: 9798.31
  t6-priority-dkp: 10731.81
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3324.5
  t4-priority-dkp: 3333.61
  t5-lottery-dkp: 2595.01
  t5-priority-dkp: 2704.84
  t6-lottery-dkp: 7905.46
  t6-priority-dkp: 7653.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2962.69
  t4-priority-dkp: 3314.61
  t5-lottery-dkp: 3507.37
  t5-priority-dkp: 2997.92
  t6-lottery-dkp: 5431.21
  t6-priority-dkp: 8648.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3226.77
  t4-priority-dkp: 3332.3
  t5-lottery-dkp: 2923.04
  t5-priority-dkp: 3564.49
  t6-lottery-dkp: 4997.64
  t6-priority-dkp: 6825.7
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1352.53
  t4-priority-dkp: 1352.53
  t5-lottery-dkp: 2174.05
  t5-priority-dkp: 2174.05
  t6-lottery-dkp: 1083.02
  t6-priority-dkp: 1083.02
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3216.02
  t4-priority-dkp: 3126.53
  t5-lottery-dkp: 3767.5
  t5-priority-dkp: 3153.73
  t6-lottery-dkp: 3270.56
  t6-priority-dkp: 8974.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2891.61
  t4-priority-dkp: 2878.1
  t5-lottery-dkp: 1849.1
  t5-priority-dkp: 2850.58
  t6-lottery-dkp: 6535.4
  t6-priority-dkp: 9235.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2332.45
  t4-priority-dkp: 2296.01
  t5-lottery-dkp: 1126.96
  t5-priority-dkp: 2624.8
  t6-lottery-dkp: 4203.94
  t6-priority-dkp: 6832.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3312.18
  t4-priority-dkp: 3330.41
  t5-lottery-dkp: 3663.55
  t5-priority-dkp: 3665.17
  t6-lottery-dkp: 4250.26
  t6-priority-dkp: 10608.25
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 161.19
  t4-priority-dkp: 161.19
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 26.9
  t4-priority-dkp: 26.9
  t5-lottery-dkp: 99.25
  t5-priority-dkp: 99.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  priority-lootconfig:
  - Insidious Bands
  - Shadowmaster's Boots
  rank: Reserve Raider
  t4-lottery-dkp: 3042.79
  t4-priority-dkp: 2117.03
  t5-lottery-dkp: 3482.57
  t5-priority-dkp: 3413.45
  t6-lottery-dkp: 5590.85
  t6-priority-dkp: 8961.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 136.65
  t4-priority-dkp: 136.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 803.39
  t6-priority-dkp: 803.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3137.19
  t4-priority-dkp: 3325.09
  t5-lottery-dkp: 3673.64
  t5-priority-dkp: 3821.69
  t6-lottery-dkp: 3840.22
  t6-priority-dkp: 10708.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2701.31
  t4-priority-dkp: 2723.83
  t5-lottery-dkp: 3225.97
  t5-priority-dkp: 3500.16
  t6-lottery-dkp: 6032.17
  t6-priority-dkp: 5242.55
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3278.06
  t4-priority-dkp: 3200.29
  t5-lottery-dkp: 3725.96
  t5-priority-dkp: 3844.39
  t6-lottery-dkp: 6102.7
  t6-priority-dkp: 7750.56
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 61.59
  t4-priority-dkp: 61.59
  t5-lottery-dkp: 105.99
  t5-priority-dkp: 105.99
  t6-lottery-dkp: 61.51
  t6-priority-dkp: 61.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solljus:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 426.27
  t4-priority-dkp: 426.27
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2828.13
  t4-priority-dkp: 3222.95
  t5-lottery-dkp: 3293.98
  t5-priority-dkp: 2801.28
  t6-lottery-dkp: 2954.29
  t6-priority-dkp: 10118.66
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3320.74
  t4-priority-dkp: 3313.83
  t5-lottery-dkp: 2665.04
  t5-priority-dkp: 3681.19
  t6-lottery-dkp: 9898.35
  t6-priority-dkp: 8695.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1591.11
  t4-priority-dkp: 1591.11
  t5-lottery-dkp: 2646.29
  t5-priority-dkp: 2646.29
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3169.3
  t4-priority-dkp: 3222.95
  t5-lottery-dkp: 1315.29
  t5-priority-dkp: 3649.81
  t6-lottery-dkp: 187.76
  t6-priority-dkp: 10599.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2736.23
  t4-priority-dkp: 3270.95
  t5-lottery-dkp: 459.61
  t5-priority-dkp: 3879.7
  t6-lottery-dkp: 7141.14
  t6-priority-dkp: 8905.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Apostle of Argus
  - Pillar of Ferocity
  - Shadowmoon Insignia
  priority-lootconfig:
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 3129.43
  t4-priority-dkp: 3333.69
  t5-lottery-dkp: 2885.07
  t5-priority-dkp: 3879.06
  t6-lottery-dkp: 2333.01
  t6-priority-dkp: 10229.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
