Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Infamy
  - Boundless Agony
  - Chestguard of the Fallen Protector
  - Choker of Serrated Blades
  - Cursed Vision of Sargeras
  - Don Alejandro's Money Belt
  - Gloves of the Fallen Protector
  - Insidious Bands
  - Leggings of the Fallen Protector
  - Pauldrons of the Fallen Protector
  - Shadowmaster's Boots
  - Stormrage Signet Ring
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Bristleblitz Striker
  - Madness of the Betrayer
  rank: Core Raider
  t4-lottery-dkp: 3834.07
  t4-priority-dkp: 3751.77
  t5-lottery-dkp: 6056.24
  t5-priority-dkp: 4924.63
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3590.62
  t4-priority-dkp: 3942.67
  t5-lottery-dkp: -7072.81
  t5-priority-dkp: 7402.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1016.27
  t4-priority-dkp: 1016.27
  t5-lottery-dkp: 1592.55
  t5-priority-dkp: 1592.55
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 11.09
  t4-priority-dkp: 11.09
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of Devastation
  - Belt of One-Hundred Deaths
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Shadowmoon Destroyer's Drape
  - Torch of the Damned
  priority-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Tsunami Talisman
  rank: Core Raider
  t4-lottery-dkp: 2367.37
  t4-priority-dkp: 3941.87
  t5-lottery-dkp: 3881.27
  t5-priority-dkp: 6755.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3293.74
  t4-priority-dkp: 2744.51
  t5-lottery-dkp: 2915.98
  t5-priority-dkp: 6222.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Dragonspine Trophy
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3129.65
  t4-priority-dkp: 3945.53
  t5-lottery-dkp: 4303.15
  t5-priority-dkp: 7399.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3782.69
  t4-priority-dkp: 3774.08
  t5-lottery-dkp: 6722.56
  t5-priority-dkp: 7255.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 298.29
  t5-priority-dkp: 298.29
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Mindstorm Wristbands
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: -414.65
  t4-priority-dkp: 3640.36
  t5-lottery-dkp: 1503.37
  t5-priority-dkp: 6955.44
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3936.22
  t4-priority-dkp: 3717.03
  t5-lottery-dkp: 3619.09
  t5-priority-dkp: 5957.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Rod of the Sun King
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3746.08
  t4-priority-dkp: 3861.29
  t5-lottery-dkp: 4226.690000000001
  t5-priority-dkp: 7329.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 111.79
  t4-priority-dkp: 132.03
  t5-lottery-dkp: 93.13
  t5-priority-dkp: 110.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3924.85
  t4-priority-dkp: 3362.93
  t5-lottery-dkp: 6018.11
  t5-priority-dkp: 7345.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Leggings of the Vanquished Champion
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3948.64
  t4-priority-dkp: 3269.31
  t5-lottery-dkp: 5410.69
  t5-priority-dkp: 7370.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Magtheridon
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2818.42
  t4-priority-dkp: 3526.29
  t5-lottery-dkp: 1164.24
  t5-priority-dkp: 5932.4
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1895.63
  t4-priority-dkp: 2833.35
  t5-lottery-dkp: 2401.9
  t5-priority-dkp: 3642.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1378.57
  t4-priority-dkp: 969.99
  t5-lottery-dkp: 972.89
  t5-priority-dkp: 3233.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Luminescent Rod of the Naaru
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3915.99
  t4-priority-dkp: 3827.74
  t5-lottery-dkp: 5359.83
  t5-priority-dkp: 7402.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3948.64
  t4-priority-dkp: 3727.97
  t5-lottery-dkp: 5623.57
  t5-priority-dkp: 3100.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 3855.67
  t4-priority-dkp: 3204.45
  t5-lottery-dkp: 3786.94
  t5-priority-dkp: 4344.29
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3883.74
  t4-priority-dkp: 3334.51
  t5-lottery-dkp: 4095.98
  t5-priority-dkp: 7402.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 92.45
  t5-priority-dkp: 92.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Mindstorm Wristbands
  - The Nexus Key
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3797.03
  t4-priority-dkp: 3941.48
  t5-lottery-dkp: 5102.889999999999
  t5-priority-dkp: 7399.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - Hammer of Judgement
  - Kaz'rogal's Hardened Heart
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 3632.58
  t4-priority-dkp: 3920.65
  t5-lottery-dkp: 8.960000000000036
  t5-priority-dkp: 6915.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mekanina:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3855.48
  t4-priority-dkp: 2437.69
  t5-lottery-dkp: 5624.87
  t5-priority-dkp: 6646.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2780.96
  t4-priority-dkp: 2566.8
  t5-lottery-dkp: 1652.57
  t5-priority-dkp: 7361.88
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2883.25
  t4-priority-dkp: 2883.25
  t5-lottery-dkp: 236.38
  t5-priority-dkp: 236.38
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1496.22
  t4-priority-dkp: 1496.22
  t5-lottery-dkp: 1134.06
  t5-priority-dkp: 2203.12
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Sunshower Light Cloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3601.92
  t4-priority-dkp: 3890.62
  t5-lottery-dkp: 3977.86
  t5-priority-dkp: 4003.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 284.48
  t4-priority-dkp: 308.28
  t5-lottery-dkp: 324.48
  t5-priority-dkp: 344.27
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1859.87
  t4-priority-dkp: 1859.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 426.27
  t4-priority-dkp: 426.27
  t5-lottery-dkp: 1572.5
  t5-priority-dkp: 1572.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Don Alejandro's Money Belt
  - Insidious Bands
  - Magtheridon's Head
  priority-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Bristleblitz Striker
  - Dragonspine Trophy
  - Madness of the Betrayer
  - Verdant Sphere
  rank: Reserve Raider
  t4-lottery-dkp: 2350.26
  t4-priority-dkp: 2350.26
  t5-lottery-dkp: 2514.19
  t5-priority-dkp: 3771.9
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2854.84
  t4-priority-dkp: 2733.94
  t5-lottery-dkp: 2514.07
  t5-priority-dkp: 4744.14
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Coral Band of the Revived
  - Crystal Spire of Karabor
  - Memento of Tyrande
  priority-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3271.25
  t4-priority-dkp: 3628.07
  t5-lottery-dkp: 2139.18
  t5-priority-dkp: 5286.83
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shlarred:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3061.23
  t4-priority-dkp: 3744.61
  t5-lottery-dkp: 4966.8
  t5-priority-dkp: 7196.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 975.85
  t4-priority-dkp: 975.85
  t5-lottery-dkp: 1679.41
  t5-priority-dkp: 1679.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1920.58
  t4-priority-dkp: 2032.48
  t5-lottery-dkp: 2877.84
  t5-priority-dkp: 3218.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Eredar Wand of Obliteration
  - Fathomstone
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - The Nexus Key
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Fang of the Leviathan
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2188.08
  t4-priority-dkp: 2188.08
  t5-lottery-dkp: 1953.69
  t5-priority-dkp: 4376.190000000001
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Chestguard of the Vanquished Defender
  - Scepter of Purification
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3737.63
  t4-priority-dkp: 3628.07
  t5-lottery-dkp: 3402.52
  t5-priority-dkp: 4257.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Bracers of Martyrdom
  - Chestguard of the Forgotten Conqueror
  - Chestguard of the Vanquished Defender
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 1338.09
  t4-priority-dkp: 2188.08
  t5-lottery-dkp: -3334.0
  t5-priority-dkp: 3760.22
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3571.49
  t4-priority-dkp: 2948.64
  t5-lottery-dkp: 1170.51
  t5-priority-dkp: 7402.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3293.74
  t4-priority-dkp: 2744.51
  t5-lottery-dkp: 2915.98
  t5-priority-dkp: 6222.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Thalassian Wildercloak
  - Tsunami Talisman
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3825.75
  t4-priority-dkp: 3942.67
  t5-lottery-dkp: 4155.030000000001
  t5-priority-dkp: 7392.55
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3948.64
  t4-priority-dkp: 3806.4
  t5-lottery-dkp: 4137.73
  t5-priority-dkp: 6761.34
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Illidari Shatterer
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 2764.79
  t4-priority-dkp: 2555.22
  t5-lottery-dkp: 7262.85
  t5-priority-dkp: 7402.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
