Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Magtheridon's Head
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2030.33
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Frayed Tether of the Drowned
  - Girdle of the Invulnerable
  - Leggings of the Fallen Defender
  - Mallet of the Tides
  - Pauldrons of the Fallen Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Seventh Ring of the Tirisfalen
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Serpentshrine Shuriken
  rank: Core Raider
  t4-lottery-dkp: 1786.82
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 243.28
  t4-priority-dkp: 243.28
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Bladespire Warbands
  - Chestguard of the Fallen Champion
  - Girdle of the Endless Pit
  - Leggings of the Fallen Champion
  - Pauldrons of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3010.25
  t4-priority-dkp: 3010.25
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2288.48
  t4-priority-dkp: 3090.63
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1684.51
  t4-priority-dkp: 2672.39
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2886.47
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - 'Pattern: Boots of Utter Darkness'
  - Rod of the Sun King
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1835.81
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig:
  - Bladespire Warbands
  - Girdle of the Endless Pit
  priority-lootconfig:
  - Gauntlets of Martial Perfection
  rank: Core Raider
  t4-lottery-dkp: 2117.55
  t4-priority-dkp: 2561.26
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2636.95
  t4-priority-dkp: 2838.38
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 2308.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig:
  - Eye of Gruul
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 2167.68
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  - Fang of the Leviathan
  - Fathomstone
  - Gauntlets of the Sun King
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - Serpent-Coil Braid
  - Velvet Boots of the Guardian
  - Verdant Sphere
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 1871.35
  t4-priority-dkp: 2636.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3199.83
  t4-priority-dkp: 2756.12
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2442.76
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 2636.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2296.46
  t4-priority-dkp: 2544.83
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1735.66
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinasa:
  class: Priest
  lottery-lootconfig:
  - Eye of Magtheridon
  - Soul-Eater's Handwraps
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3090.63
  t4-priority-dkp: 3090.63
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinyonga:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kromlek:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Krumonx:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Aldori Legacy Defender
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 2544.83
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mitchendo:
  class: Shaman
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Pauldrons of the Fallen Champion
  rank: Social Member
  t4-lottery-dkp: 672.16
  t4-priority-dkp: 1006.37
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mlg:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2308.95
  t4-priority-dkp: 2781.81
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Core Raider
  t4-lottery-dkp: 1115.88
  t4-priority-dkp: 2544.83
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  - Gauntlets of Martial Perfection
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1140.99
  t4-priority-dkp: 2090.63
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pikachau:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 136.65
  t4-priority-dkp: 136.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2585.66
  t4-priority-dkp: 1886.47
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2636.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Paladin
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Schroumpf:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1690.31
  t4-priority-dkp: 2067.45
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1333.84
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnackypacky:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2183.61
  t4-priority-dkp: 2183.61
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shran:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 243.28
  t4-priority-dkp: 243.28
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Skypola:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 136.65
  t4-priority-dkp: 136.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Karaborian Talisman
  priority-lootconfig:
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 1090.63
  t4-priority-dkp: 2368.13
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1182.72
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Tenfour:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 160.76
  t4-priority-dkp: 160.76
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thejudge:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 160.76
  t4-priority-dkp: 160.76
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 463.68
  t4-priority-dkp: 2897.16
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3158.95
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1399.72
  t4-priority-dkp: 3158.95
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
