Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boneweave Girdle
  - Chestguard of the Forgotten Protector
  - Choker of Endless Nightmares
  - Insidious Bands
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3495.14
  t4-priority-dkp: 3491.38
  t5-lottery-dkp: 2593.18
  t5-priority-dkp: 2145.11
  t6-lottery-dkp: 3008.28
  t6-priority-dkp: 10451.91
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Borderland Fortress Grips
  - Bulwark of Azzinoth
  - Chestguard of the Forgotten Protector
  - Collar of the Pit Lord
  - Crimson Paragon's Cover
  - Crown of Anasterian
  - Dragonscale-Encrusted Longblade
  - Felfury Legplates
  - Ring of Hardened Resolve
  - Steely Naaru Sliver
  priority-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 3484.05
  t4-priority-dkp: 3500.09
  t5-lottery-dkp: 267.16
  t5-priority-dkp: 2597.52
  t6-lottery-dkp: -11472.0
  t6-priority-dkp: 8639.73
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 121.8
  t4-priority-dkp: 121.8
  t5-lottery-dkp: 197.79
  t5-priority-dkp: 197.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Cursed Vision of Sargeras
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2336.76
  t4-priority-dkp: 2031.41
  t5-lottery-dkp: 2642.51
  t5-priority-dkp: 2773.58
  t6-lottery-dkp: 7805.28
  t6-priority-dkp: 10499.96
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2762.52
  t4-priority-dkp: 2910.09
  t5-lottery-dkp: 2084.46
  t5-priority-dkp: 2802.62
  t6-lottery-dkp: 3185.85
  t6-priority-dkp: 8890.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3463.02
  t4-priority-dkp: 3500.23
  t5-lottery-dkp: 2116.76
  t5-priority-dkp: 2802.96
  t6-lottery-dkp: 9001.59
  t6-priority-dkp: 9555.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1615.49
  t4-priority-dkp: 1615.1
  t5-lottery-dkp: 2102.62
  t5-priority-dkp: 2760.81
  t6-lottery-dkp: 4256.1
  t6-priority-dkp: 4469.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2840.91
  t4-priority-dkp: 2830.92
  t5-lottery-dkp: 2185.52
  t5-priority-dkp: 2292.14
  t6-lottery-dkp: 9000.79
  t6-priority-dkp: 7721.17
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Belt of the Forgotten Protector
  - Blackened Naaru Sliver
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Choker of Endless Nightmares
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Mantle of the Golden Forest
  - Mounting Vengeance
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3491.13
  t4-priority-dkp: 3496.39
  t5-lottery-dkp: 2089.8
  t5-priority-dkp: 2799.76
  t6-lottery-dkp: 9883.81
  t6-priority-dkp: 7590.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 5.1
  t4-priority-dkp: 6.02
  t5-lottery-dkp: 4.24
  t5-priority-dkp: 5.02
  t6-lottery-dkp: 2.46
  t6-priority-dkp: 2.86
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demacian:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1478.7
  t4-priority-dkp: 1478.7
  t5-lottery-dkp: 1570.75
  t5-priority-dkp: 1570.75
  t6-lottery-dkp: 782.48
  t6-priority-dkp: 782.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3499.28
  t4-priority-dkp: 3473.66
  t5-lottery-dkp: 2739.96
  t5-priority-dkp: 2468.71
  t6-lottery-dkp: 2123.31
  t6-priority-dkp: 10826.44
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 244.17
  t4-priority-dkp: 244.17
  t5-lottery-dkp: 10.79
  t5-priority-dkp: 10.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Belt of the Forgotten Vanquisher
  - Boots of the Forgotten Vanquisher
  - Bracers of the Forgotten Vanquisher
  - Cloak of Unforgivable Sin
  - 'Design: Hard Khorium Choker'
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Hand of the Deceiver
  rank: Core Raider
  t4-lottery-dkp: 3500.36
  t4-priority-dkp: 3469.38
  t5-lottery-dkp: 957.92
  t5-priority-dkp: 2231.08
  t6-lottery-dkp: 8359.46
  t6-priority-dkp: 10593.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3374.57
  t4-priority-dkp: 3481.11
  t5-lottery-dkp: 2411.32
  t5-priority-dkp: 2777.57
  t6-lottery-dkp: 3401.02
  t6-priority-dkp: 10980.4
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hipon:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3498.88
  t4-priority-dkp: 3494.85
  t5-lottery-dkp: 2226.74
  t5-priority-dkp: 2476.7
  t6-lottery-dkp: 4100.91
  t6-priority-dkp: 9452.96
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Siphon of the Nathrezim
  - Siphon of the Nathrezim
  priority-lootconfig:
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3500.36
  t4-priority-dkp: 3322.95
  t5-lottery-dkp: 1868.51
  t5-priority-dkp: 2606.91
  t6-lottery-dkp: 9154.07
  t6-priority-dkp: 9581.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 144.56
  t4-priority-dkp: 144.56
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3351.57
  t4-priority-dkp: 3321.87
  t5-lottery-dkp: 2638.2
  t5-priority-dkp: 2663.62
  t6-lottery-dkp: 4325.31
  t6-priority-dkp: 8913.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3416.36
  t4-priority-dkp: 3391.31
  t5-lottery-dkp: 2378.99
  t5-priority-dkp: 2529.77
  t6-lottery-dkp: 10344.53
  t6-priority-dkp: 8468.98
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Ring of Ancient Knowledge
  - Ring of Omnipotence
  - Tattered Cape of Antonidas
  priority-lootconfig:
  - Shifting Naaru Sliver
  - Sunflare
  rank: Core Raider
  t4-lottery-dkp: 3493.45
  t4-priority-dkp: 3500.03
  t5-lottery-dkp: 1874.9
  t5-priority-dkp: 1954.24
  t6-lottery-dkp: 8976.94
  t6-priority-dkp: 8794.81
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3232.05
  t4-priority-dkp: 3486.31
  t5-lottery-dkp: 2534.07
  t5-priority-dkp: 2166.0
  t6-lottery-dkp: 7189.3
  t6-priority-dkp: 9513.71
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Loopfish:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - 'Design: Pendant of Sunfire'
  - Girdle of Mighty Resolve
  - Helm of Burning Righteousness
  - Heroic Judicator's Chestguard
  - Legplates of the Holy Juggernaut
  - Pauldrons of Perseverance
  - Sword Breaker's Bulwark
  priority-lootconfig:
  - Belt of the Forgotten Conqueror
  - Bracers of the Forgotten Conqueror
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3422.84
  t4-priority-dkp: 3499.08
  t5-lottery-dkp: 2111.89
  t5-priority-dkp: 2575.35
  t6-lottery-dkp: 3876.04
  t6-priority-dkp: 8196.810000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Memento of Tyrande
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 2068.7
  t4-priority-dkp: 2068.7
  t5-lottery-dkp: 1570.75
  t5-priority-dkp: 1570.75
  t6-lottery-dkp: 2547.48
  t6-priority-dkp: 2547.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3415.08
  t4-priority-dkp: 3350.42
  t5-lottery-dkp: 2722.02
  t5-priority-dkp: 2278.57
  t6-lottery-dkp: 5628.23
  t6-priority-dkp: 9749.3
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3180.69
  t4-priority-dkp: 2170.92
  t5-lottery-dkp: 1335.97
  t5-priority-dkp: 2059.54
  t6-lottery-dkp: 7987.08
  t6-priority-dkp: 9937.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2473.81
  t4-priority-dkp: 2447.47
  t5-lottery-dkp: 814.23
  t5-priority-dkp: 1896.42
  t6-lottery-dkp: 5605.29
  t6-priority-dkp: 7504.37
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3484.55
  t4-priority-dkp: 3497.72
  t5-lottery-dkp: 2646.92
  t5-priority-dkp: 2648.08
  t6-lottery-dkp: 6336.06
  t6-priority-dkp: 10929.71
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Reminosc:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1091.5
  t4-priority-dkp: 1091.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 116.46
  t4-priority-dkp: 116.46
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 19.43
  t4-priority-dkp: 19.43
  t5-lottery-dkp: 71.71
  t5-priority-dkp: 71.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Black Bow of the Betrayer
  - Cursed Vision of Sargeras
  priority-lootconfig:
  - Shadowmaster's Boots
  rank: Reserve Raider
  t4-lottery-dkp: 3289.91
  t4-priority-dkp: 2621.06
  t5-lottery-dkp: 2516.15
  t5-priority-dkp: 2466.22
  t6-lottery-dkp: 7304.64
  t6-priority-dkp: 6740.24
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 98.73
  t4-priority-dkp: 98.73
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 580.45
  t6-priority-dkp: 580.45
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3358.12
  t4-priority-dkp: 3493.88
  t5-lottery-dkp: 2654.2
  t5-priority-dkp: 2761.17
  t6-lottery-dkp: 6039.81
  t6-priority-dkp: 11002.14
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1951.69
  t4-priority-dkp: 1967.97
  t5-lottery-dkp: 2330.76
  t5-priority-dkp: 2528.87
  t6-lottery-dkp: 7623.49
  t6-priority-dkp: 7052.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3459.9
  t4-priority-dkp: 3403.71
  t5-lottery-dkp: 2692.01
  t5-priority-dkp: 2777.57
  t6-lottery-dkp: 7674.45
  t6-priority-dkp: 8865.03
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 44.5
  t4-priority-dkp: 44.5
  t5-lottery-dkp: 76.58
  t5-priority-dkp: 76.58
  t6-lottery-dkp: 44.44
  t6-priority-dkp: 44.08
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solljus:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2043.32
  t4-priority-dkp: 2328.58
  t5-lottery-dkp: 2379.9
  t5-priority-dkp: 2023.93
  t6-lottery-dkp: -150.27
  t6-priority-dkp: 10575.98
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Book of Highborne Hymns
  - Breeches of Natural Aggression
  - Cover of Ursol the Wise
  - Crystal Spire of Karabor
  - Memento of Tyrande
  - Spaulders of Reclamation
  - Tranquil Majesty Wraps
  priority-lootconfig:
  - Hammer of Sanctification
  rank: Core Raider
  t4-lottery-dkp: 3490.74
  t4-priority-dkp: 3485.75
  t5-lottery-dkp: 1925.49
  t5-priority-dkp: 2659.66
  t6-lottery-dkp: 10416.81
  t6-priority-dkp: 9547.94
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1149.57
  t4-priority-dkp: 1149.57
  t5-lottery-dkp: 1911.95
  t5-priority-dkp: 1911.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3381.32
  t4-priority-dkp: 3420.08
  t5-lottery-dkp: 950.3
  t5-priority-dkp: 2636.99
  t6-lottery-dkp: 3400.91
  t6-priority-dkp: 10923.3
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Venatir:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Murumasa
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3068.43
  t4-priority-dkp: 3454.76
  t5-lottery-dkp: 332.07
  t5-priority-dkp: 2803.08
  t6-lottery-dkp: 8424.720000000001
  t6-priority-dkp: 9699.48
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmoon Insignia
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3352.52
  t4-priority-dkp: 3500.09
  t5-lottery-dkp: 2084.46
  t5-priority-dkp: 2802.62
  t6-lottery-dkp: 1950.85
  t6-priority-dkp: 10655.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
