Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Magtheridon's Head
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 1694.5
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Leggings of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1408.02
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 286.21
  t4-priority-dkp: 286.21
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Bladespire Warbands
  - Chestguard of the Fallen Champion
  - Girdle of the Endless Pit
  - Leggings of the Fallen Champion
  - Pauldrons of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2847.35
  t4-priority-dkp: 2847.35
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1998.21
  t4-priority-dkp: 2941.92
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1287.66
  t4-priority-dkp: 2449.87
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2701.73
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Pauldrons of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1465.66
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig:
  - Bladespire Warbands
  - Girdle of the Endless Pit
  priority-lootconfig:
  - Gauntlets of Martial Perfection
  rank: Core Raider
  t4-lottery-dkp: 2144.18
  t4-priority-dkp: 2666.19
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2408.18
  t4-priority-dkp: 2645.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 2022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 1856.1
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 1507.47
  t4-priority-dkp: 2408.18
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3070.39
  t4-priority-dkp: 2548.38
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Hyolin:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2179.72
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 2408.18
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 2007.6
  t4-priority-dkp: 2299.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 1347.83
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinasa:
  class: Priest
  lottery-lootconfig:
  - Eye of Magtheridon
  - Soul-Eater's Handwraps
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2941.92
  t4-priority-dkp: 2941.92
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinyonga:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kromlek:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Krumonx:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Aldori Legacy Defender
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  - Pauldrons of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 2299.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mitchendo:
  class: Shaman
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Pauldrons of the Fallen Champion
  rank: Social Member
  t4-lottery-dkp: 790.78
  t4-priority-dkp: 1183.96
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mlg:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2022.3
  t4-priority-dkp: 2578.6
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Core Raider
  t4-lottery-dkp: 1795.15
  t4-priority-dkp: 2299.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Gauntlets of Martial Perfection
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 648.22
  t4-priority-dkp: 2941.92
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pikachau:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 160.76
  t4-priority-dkp: 160.76
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 2347.83
  t4-priority-dkp: 2701.73
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2408.18
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Paladin
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Schroumpf:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1988.6
  t4-priority-dkp: 2432.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 875.11
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnackypacky:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2067.45
  t4-priority-dkp: 2067.45
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shran:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 286.21
  t4-priority-dkp: 286.21
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Skypola:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 160.76
  t4-priority-dkp: 160.76
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Belt of Divine Inspiration
  - Magtheridon's Head
  priority-lootconfig:
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 2941.92
  t4-priority-dkp: 2091.92
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 697.3199999999999
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Tenfour:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 189.13
  t4-priority-dkp: 189.13
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thejudge:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 189.13
  t4-priority-dkp: 189.13
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1027.86
  t4-priority-dkp: 2714.31
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3022.3
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 952.61
  t4-priority-dkp: 3022.3
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
