Abjection:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Infamy
  - Boundless Agony
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Cursed Vision of Sargeras
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Leggings of the Forgotten Protector
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  - Stormrage Signet Ring
  - Thalassian Wildercloak
  priority-lootconfig:
  - Bristleblitz Striker
  rank: Core Raider
  t4-lottery-dkp: 3291.52
  t4-priority-dkp: 3248.56
  t5-lottery-dkp: 4041.61
  t5-priority-dkp: 5150.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Band of the Abyssal Lord
  - Bulwark of Azzinoth
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Defender
  - Eternium Shell Bracers
  - Faceplate of the Impenetrable
  - Gauntlets of Enforcement
  - Leggings of the Forgotten Protector
  - Legionkiller
  - Myrmidon's Treads
  - Pauldrons of the Forgotten Protector
  - Pendant of Titans
  - Pepe's Shroud of Pacification
  - Ring of Deceitful Intent
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3164.44
  t4-priority-dkp: 3348.21
  t5-lottery-dkp: -3532.81
  t5-priority-dkp: 6444.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1394.34
  t4-priority-dkp: 1394.34
  t5-lottery-dkp: 2264.21
  t5-priority-dkp: 2264.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of Devastation
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Shadowmoon Destroyer's Drape
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Dreadboots of the Legion
  rank: Core Raider
  t4-lottery-dkp: 2525.89
  t4-priority-dkp: 3347.78
  t5-lottery-dkp: 4606.27
  t5-priority-dkp: 6106.72
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Cataclysm's Edge
  - Chestguard of the Forgotten Protector
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Leggings of Divine Retribution
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2923.8
  t4-priority-dkp: 3349.7
  t5-lottery-dkp: 4826.5
  t5-priority-dkp: 6443.02
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3264.7
  t4-priority-dkp: 3260.2
  t5-lottery-dkp: 6089.43
  t5-priority-dkp: 6367.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 155.71
  t5-priority-dkp: 155.71
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Chestguard of the Forgotten Vanquisher
  - Gloves of the Forgotten Vanquisher
  - Leggings of the Forgotten Vanquisher
  - Pauldrons of the Forgotten Vanquisher
  - Stormrage Signet Ring
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Blade of Infamy
  - Cursed Vision of Sargeras
  - Insidious Bands
  rank: Core Raider
  t4-lottery-dkp: 2556.23
  t4-priority-dkp: 2441.82
  t5-lottery-dkp: 4469.41
  t5-priority-dkp: 5690.07
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Bow-stitched Leggings
  - Fists of Mukoa
  - Madness of the Betrayer
  - Midnight Chestguard
  - Rod of the Sun King
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3245.58
  t4-priority-dkp: 3305.73
  t5-lottery-dkp: 4786.58
  t5-priority-dkp: 6406.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 58.35
  t4-priority-dkp: 68.93
  t5-lottery-dkp: 48.62
  t5-priority-dkp: 57.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Nexus Key
  priority-lootconfig:
  - The Skull of Gul'dan
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 3338.9
  t4-priority-dkp: 3045.58
  t5-lottery-dkp: 5721.71
  t5-priority-dkp: 4969.67
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Leggings of the Forgotten Vanquisher
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3351.32
  t4-priority-dkp: 2996.7
  t5-lottery-dkp: 3959.64
  t5-priority-dkp: 5199.25
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Devastation
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  - Waistwrap of Infinity
  priority-lootconfig:
  - Ring of Ancient Knowledge
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 1911.34
  t4-priority-dkp: 3130.86
  t5-lottery-dkp: 1959.71
  t5-priority-dkp: 5676.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Crystal Spire of Karabor
  - Earring of Soulful Meditation
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Lightfathom Scepter
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3334.28
  t4-priority-dkp: 3288.21
  t5-lottery-dkp: 3678.09
  t5-priority-dkp: 6444.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3351.32
  t4-priority-dkp: 3236.13
  t5-lottery-dkp: 5515.76
  t5-priority-dkp: 4198.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Captured Storms
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 3302.79
  t4-priority-dkp: 2962.84
  t5-lottery-dkp: 4557.02
  t5-priority-dkp: 4847.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2389.67
  t4-priority-dkp: 2102.97
  t5-lottery-dkp: 4718.34
  t5-priority-dkp: 6444.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3272.19
  t4-priority-dkp: 3347.59
  t5-lottery-dkp: 5243.96
  t5-priority-dkp: 6443.02
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cuffs of Devastation
  - Leggings of the Forgotten Vanquisher
  - Slippers of the Seacaller
  - Waistwrap of Infinity
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Mindstorm Wristbands
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 279.69
  t4-priority-dkp: 3190.4
  t5-lottery-dkp: 3364.98
  t5-priority-dkp: 4982.75
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Antonidas's Aegis of Rapt Concentration
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - Hammer of Judgement
  - Phoenix-Wing Cloak
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2463.84
  t4-priority-dkp: 3336.71
  t5-lottery-dkp: 884.9
  t5-priority-dkp: 6190.39
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Mindstorm Wristbands
  - Pauldrons of the Forgotten Conqueror
  - Verdant Sphere
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Vestments of the Sea-Witch
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2374.93
  t4-priority-dkp: 1634.82
  t5-lottery-dkp: 5516.43
  t5-priority-dkp: 6049.6
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Deadly Cuffs
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Leggings of Divine Retribution
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  - Unstoppable Aggressor's Ring
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2741.79
  t4-priority-dkp: 2629.99
  t5-lottery-dkp: 3442.87
  t5-priority-dkp: 6423.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2795.18
  t4-priority-dkp: 2795.18
  t5-lottery-dkp: 123.39
  t5-priority-dkp: 123.39
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Sunshower Light Cloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3170.34
  t4-priority-dkp: 3321.04
  t5-lottery-dkp: 4656.68
  t5-priority-dkp: 4670.14
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1333.2
  t4-priority-dkp: 1333.2
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 222.51
  t4-priority-dkp: 222.51
  t5-lottery-dkp: 820.85
  t5-priority-dkp: 820.85
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  priority-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Dragonspine Trophy
  - Insidious Bands
  - Madness of the Betrayer
  rank: Reserve Raider
  t4-lottery-dkp: 1902.84
  t4-priority-dkp: 2516.96
  t5-lottery-dkp: 3892.63
  t5-priority-dkp: 3320.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Eye of Gruul
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Nadina's Pendant of Purity
  - Pauldrons of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3351.32
  t4-priority-dkp: 3277.07
  t5-lottery-dkp: 4740.14
  t5-priority-dkp: 6109.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Crystal Spire of Karabor
  - Memento of Tyrande
  - Shroud of the Highborne
  priority-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2997.72
  t4-priority-dkp: 3183.98
  t5-lottery-dkp: 3696.89
  t5-priority-dkp: 5339.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Forgotten Vanquisher
  - Helm of the Forgotten Vanquisher
  - Leggings of Channeled Elements
  - Pauldrons of the Forgotten Vanquisher
  - Slippers of the Seacaller
  - The Skull of Gul'dan
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2888.09
  t4-priority-dkp: 3244.82
  t5-lottery-dkp: 5172.91
  t5-priority-dkp: 6337.07
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 509.4
  t4-priority-dkp: 509.4
  t5-lottery-dkp: 876.66
  t5-priority-dkp: 876.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 1818.18
  t4-priority-dkp: 2432.3
  t5-lottery-dkp: 3600.06
  t5-priority-dkp: 4864.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Belt of Primal Majesty
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Crystal Spire of Karabor
  - Leggings of Eternity
  - Memento of Tyrande
  - Scepter of Purification
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3241.18
  t4-priority-dkp: 3183.98
  t5-lottery-dkp: 2911.35
  t5-priority-dkp: 4802.65
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 927.77
  t4-priority-dkp: 927.77
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Bracers of Martyrdom
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 1988.6
  t4-priority-dkp: 2432.3
  t5-lottery-dkp: -1794.0
  t5-priority-dkp: 4543.08
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Infamy
  - Insidious Bands
  - Stormrage Signet Ring
  - Talon of Azshara
  priority-lootconfig:
  - Blade of Savagery
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3154.44
  t4-priority-dkp: 2829.32
  t5-lottery-dkp: 3191.23
  t5-priority-dkp: 6444.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Forgotten Vanquisher
  - Gloves of the Forgotten Vanquisher
  - Leggings of the Forgotten Vanquisher
  - Pauldrons of the Forgotten Vanquisher
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3287.18
  t4-priority-dkp: 3348.21
  t5-lottery-dkp: 3520.92
  t5-priority-dkp: 6439.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Forgotten Protector
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 1443.24
  t4-priority-dkp: 1333.85
  t5-lottery-dkp: 6371.47
  t5-priority-dkp: 6444.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
