Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Infamy
  - Boundless Agony
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Cursed Vision of Sargeras
  - Don Alejandro's Money Belt
  - Gloves of the Forgotten Protector
  - Insidious Bands
  - Leggings of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shadowmaster's Boots
  - Stormrage Signet Ring
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Bristleblitz Striker
  - Madness of the Betrayer
  rank: Core Raider
  t4-lottery-dkp: 3861.62
  t4-priority-dkp: 3802.15
  t5-lottery-dkp: 6558.63
  t5-priority-dkp: 5741.05
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3685.73
  t4-priority-dkp: 3940.08
  t5-lottery-dkp: -4712.81
  t5-priority-dkp: 7531.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1235.76
  t4-priority-dkp: 1235.76
  t5-lottery-dkp: 1745.62
  t5-priority-dkp: 1745.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 8.02
  t4-priority-dkp: 8.02
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of Devastation
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Shadowmoon Destroyer's Drape
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Dreadboots of the Legion
  rank: Core Raider
  t4-lottery-dkp: 2801.92
  t4-priority-dkp: 3939.5
  t5-lottery-dkp: 4987.219999999999
  t5-priority-dkp: 7063.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3307.5
  t4-priority-dkp: 2910.68
  t5-lottery-dkp: 3962.34
  t5-priority-dkp: 6351.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Dragonspine Trophy
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3352.67
  t4-priority-dkp: 3942.14
  t5-lottery-dkp: 5292.03
  t5-priority-dkp: 7529.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3824.5
  t4-priority-dkp: 3818.27
  t5-lottery-dkp: 7040.05
  t5-priority-dkp: 7425.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 215.52
  t5-priority-dkp: 215.52
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: -260.95
  t4-priority-dkp: 3721.66
  t5-lottery-dkp: 3269.18
  t5-priority-dkp: 5508.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2843.92
  t4-priority-dkp: 2685.56
  t5-lottery-dkp: 4797.8
  t5-priority-dkp: 6487.29
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Bow-stitched Leggings
  - Fists of Mukoa
  - Madness of the Betrayer
  - Midnight Chestguard
  - Rod of the Sun King
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3798.04
  t4-priority-dkp: 3881.28
  t5-lottery-dkp: 5236.79
  t5-priority-dkp: 7478.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 80.77
  t4-priority-dkp: 95.4
  t5-lottery-dkp: 67.29
  t5-priority-dkp: 79.47
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Wand of the Forgotten Star
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3927.2
  t4-priority-dkp: 3521.22
  t5-lottery-dkp: 6531.08
  t5-priority-dkp: 5490.2
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3944.39
  t4-priority-dkp: 3453.57
  t5-lottery-dkp: 4092.23
  t5-priority-dkp: 5807.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Eye of Magtheridon
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3127.81
  t4-priority-dkp: 3639.25
  t5-lottery-dkp: 1324.16
  t5-priority-dkp: 6469.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1369.6
  t4-priority-dkp: 2047.1
  t5-lottery-dkp: 1735.38
  t5-priority-dkp: 2632.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 996.01
  t4-priority-dkp: 700.82
  t5-lottery-dkp: 702.92
  t5-priority-dkp: 2335.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2749.32
  t4-priority-dkp: 2744.03
  t5-lottery-dkp: 4981.04
  t5-priority-dkp: 5308.39
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Luminescent Rod of the Naaru
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3920.8
  t4-priority-dkp: 3857.04
  t5-lottery-dkp: 6055.48
  t5-priority-dkp: 7531.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3944.39
  t4-priority-dkp: 3784.95
  t5-lottery-dkp: 6246.03
  t5-priority-dkp: 4423.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 3877.22
  t4-priority-dkp: 3406.71
  t5-lottery-dkp: 4919.06
  t5-priority-dkp: 5321.75
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Choker of Serrated Blades
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3307.5
  t4-priority-dkp: 2910.68
  t5-lottery-dkp: 5142.34
  t5-priority-dkp: 7531.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 66.79
  t5-priority-dkp: 66.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3834.86
  t4-priority-dkp: 3939.22
  t5-lottery-dkp: 5869.84
  t5-priority-dkp: 7529.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 222.51
  t4-priority-dkp: 222.51
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Antonidas's Aegis of Rapt Concentration
  - Boots of the Resilient
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - Hammer of Judgement
  - Phoenix-Wing Cloak
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  - Wristguards of Determination
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2716.04
  t4-priority-dkp: 3924.17
  t5-lottery-dkp: 2189.48
  t5-priority-dkp: 7179.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mekanina:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Verdant Sphere
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3287.09
  t4-priority-dkp: 2262.73
  t5-lottery-dkp: 6246.97
  t5-priority-dkp: 6984.92
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3100.75
  t4-priority-dkp: 2946.01
  t5-lottery-dkp: 3376.98
  t5-priority-dkp: 7501.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3174.65
  t4-priority-dkp: 3174.65
  t5-lottery-dkp: 170.78
  t5-priority-dkp: 170.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1147.13
  t4-priority-dkp: 1869.63
  t5-lottery-dkp: 2396.57
  t5-priority-dkp: 1723.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Sunshower Light Cloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3693.89
  t4-priority-dkp: 3902.48
  t5-lottery-dkp: 5057.0
  t5-priority-dkp: 5075.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 205.54
  t4-priority-dkp: 222.73
  t5-lottery-dkp: 234.44
  t5-priority-dkp: 248.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1845.26
  t4-priority-dkp: 1845.26
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 1136.13
  t5-priority-dkp: 1136.13
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Gloves of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Madness of the Betrayer
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blade of Infamy
  - Blade of Infamy
  - Don Alejandro's Money Belt
  - Dragonspine Trophy
  - Insidious Bands
  rank: Reserve Raider
  t4-lottery-dkp: 1939.56
  t4-priority-dkp: 2789.56
  t5-lottery-dkp: 3999.5
  t5-priority-dkp: 3208.19
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2851.23
  t4-priority-dkp: 2763.88
  t5-lottery-dkp: 3393.63
  t5-priority-dkp: 5004.86
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Coral Band of the Revived
  - Crystal Spire of Karabor
  - Memento of Tyrande
  priority-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3454.98
  t4-priority-dkp: 3712.78
  t5-lottery-dkp: 3728.56
  t5-priority-dkp: 6002.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shlarred:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3303.24
  t4-priority-dkp: 3796.98
  t5-lottery-dkp: 5771.51
  t5-priority-dkp: 7382.8
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 705.05
  t4-priority-dkp: 705.05
  t5-lottery-dkp: 1213.38
  t5-priority-dkp: 1213.38
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1387.62
  t4-priority-dkp: 1468.47
  t5-lottery-dkp: 2079.24
  t5-priority-dkp: 2325.33
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 1822.39
  t4-priority-dkp: 2672.39
  t5-lottery-dkp: 3594.54
  t5-priority-dkp: 5344.8
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Belt of Primal Majesty
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Crystal Spire of Karabor
  - Leggings of Eternity
  - Memento of Tyrande
  - Scepter of Purification
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3791.94
  t4-priority-dkp: 3712.78
  t5-lottery-dkp: 2641.32
  t5-priority-dkp: 5259.04
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 0
  t5-priority-dkp: 0
  t6-lottery-dkp: 0
  t6-priority-dkp: 0
  t6pt5-lottery-dkp: 0
  t6pt5-priority-dkp: 0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Bracers of Martyrdom
  - Chestguard of the Forgotten Conqueror
  - Chestguard of the Vanquished Defender
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2058.27
  t4-priority-dkp: 2672.39
  t5-lottery-dkp: -974.0
  t5-priority-dkp: 4899.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Talon of Azshara
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3671.9
  t4-priority-dkp: 3221.89
  t5-lottery-dkp: 3028.69
  t5-priority-dkp: 7531.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3307.5
  t4-priority-dkp: 2910.68
  t5-lottery-dkp: 3962.34
  t5-priority-dkp: 6351.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Thalassian Wildercloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3855.61
  t4-priority-dkp: 3940.08
  t5-lottery-dkp: 3485.01
  t5-priority-dkp: 7524.12
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3944.39
  t4-priority-dkp: 3841.62
  t5-lottery-dkp: 5172.51
  t5-priority-dkp: 7068.07
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Forgotten Protector
  - Cursed Vision of Sargeras
  - Dreadboots of the Legion
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 1997.56
  t4-priority-dkp: 1846.15
  t5-lottery-dkp: 7430.41
  t5-priority-dkp: 7531.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
