Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boneweave Girdle
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Endless Nightmares
  - Insidious Bands
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3219.81
  t4-priority-dkp: 3213.7
  t5-lottery-dkp: 4222.56
  t5-priority-dkp: 3492.95
  t6-lottery-dkp: 1990.09
  t6-priority-dkp: 9225.810000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3201.74
  t4-priority-dkp: 3227.87
  t5-lottery-dkp: 435.04
  t5-priority-dkp: 4229.64
  t6-lottery-dkp: -14107.0
  t6-priority-dkp: 6274.98
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 198.33
  t4-priority-dkp: 198.33
  t5-lottery-dkp: 322.06
  t5-priority-dkp: 322.06
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3110.91
  t4-priority-dkp: 2613.68
  t5-lottery-dkp: 4302.89
  t5-priority-dkp: 4516.31
  t6-lottery-dkp: 4916.21
  t6-priority-dkp: 9304.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2987.57
  t4-priority-dkp: 3227.87
  t5-lottery-dkp: 3394.2
  t5-priority-dkp: 4563.6
  t6-lottery-dkp: 2432.66
  t6-priority-dkp: 8193.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3167.5
  t4-priority-dkp: 3228.09
  t5-lottery-dkp: 3446.8
  t5-priority-dkp: 4564.15
  t6-lottery-dkp: 6864.2
  t6-priority-dkp: 7765.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 2630.56
  t4-priority-dkp: 2629.93
  t5-lottery-dkp: 3423.76
  t5-priority-dkp: 4495.52
  t6-lottery-dkp: 6930.35
  t6-priority-dkp: 7277.71
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3115.22
  t4-priority-dkp: 3098.95
  t5-lottery-dkp: 3558.75
  t5-priority-dkp: 3732.38
  t6-lottery-dkp: 6862.89
  t6-priority-dkp: 4779.26
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3213.27
  t4-priority-dkp: 3221.83
  t5-lottery-dkp: 3402.89
  t5-priority-dkp: 4558.93
  t6-lottery-dkp: 8300.74
  t6-priority-dkp: 9451.279999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 8.3
  t4-priority-dkp: 9.8
  t5-lottery-dkp: 6.91
  t5-priority-dkp: 8.17
  t6-lottery-dkp: 4.0
  t6-priority-dkp: 4.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3226.55
  t4-priority-dkp: 3184.83
  t5-lottery-dkp: 4461.56
  t5-priority-dkp: 4019.89
  t6-lottery-dkp: 6001.81
  t6-priority-dkp: 9835.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 397.59
  t4-priority-dkp: 397.59
  t5-lottery-dkp: 17.56
  t5-priority-dkp: 17.56
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3228.31
  t4-priority-dkp: 3177.87
  t5-lottery-dkp: 1559.81
  t5-priority-dkp: 3632.94
  t6-lottery-dkp: 5818.6
  t6-priority-dkp: 9456.630000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3023.49
  t4-priority-dkp: 3196.95
  t5-lottery-dkp: 3926.43
  t5-priority-dkp: 4522.81
  t6-lottery-dkp: 1274.02
  t6-priority-dkp: 10086.37
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Scepter of Purification
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3225.89
  t4-priority-dkp: 3219.34
  t5-lottery-dkp: 3625.88
  t5-priority-dkp: 4032.88
  t6-lottery-dkp: 2413.67
  t6-priority-dkp: 7599.19
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3228.31
  t4-priority-dkp: 2939.44
  t5-lottery-dkp: 3042.56
  t5-priority-dkp: 4244.92
  t6-lottery-dkp: 7112.48
  t6-priority-dkp: 7808.63
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 235.39
  t4-priority-dkp: 235.39
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2986.02
  t4-priority-dkp: 2937.66
  t5-lottery-dkp: 4295.87
  t5-priority-dkp: 4337.26
  t6-lottery-dkp: 3401.91
  t6-priority-dkp: 6720.87
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3091.53
  t4-priority-dkp: 3050.74
  t5-lottery-dkp: 3873.79
  t5-priority-dkp: 4119.3
  t6-lottery-dkp: 9050.95
  t6-priority-dkp: 10149.19
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3217.06
  t4-priority-dkp: 3227.78
  t5-lottery-dkp: 3052.95
  t5-priority-dkp: 3182.17
  t6-lottery-dkp: 6824.07
  t6-priority-dkp: 6527.5
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2791.4
  t4-priority-dkp: 3205.42
  t5-lottery-dkp: 4126.32
  t5-priority-dkp: 3526.97
  t6-lottery-dkp: 3913.19
  t6-priority-dkp: 7698.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3102.08
  t4-priority-dkp: 3226.23
  t5-lottery-dkp: 3438.87
  t5-priority-dkp: 4193.52
  t6-lottery-dkp: 6932.52
  t6-priority-dkp: 5553.76
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1591.21
  t4-priority-dkp: 1591.21
  t5-lottery-dkp: 2557.71
  t5-priority-dkp: 2557.71
  t6-lottery-dkp: 1274.14
  t6-priority-dkp: 1274.14
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3089.43
  t4-priority-dkp: 2984.15
  t5-lottery-dkp: 4432.35
  t5-priority-dkp: 3710.27
  t6-lottery-dkp: 4371.25
  t6-priority-dkp: 8081.73
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2707.78
  t4-priority-dkp: 2691.88
  t5-lottery-dkp: 2175.41
  t5-priority-dkp: 3353.62
  t6-lottery-dkp: 5212.24
  t6-priority-dkp: 8388.71
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2744.06
  t4-priority-dkp: 2701.19
  t5-lottery-dkp: 1325.84
  t5-priority-dkp: 3088.0
  t6-lottery-dkp: 6335.56
  t6-priority-dkp: 6877.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3202.57
  t4-priority-dkp: 3224.01
  t5-lottery-dkp: 4310.06
  t5-priority-dkp: 4311.96
  t6-lottery-dkp: 2523.84
  t6-priority-dkp: 10003.82
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 189.64
  t4-priority-dkp: 189.64
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 31.65
  t4-priority-dkp: 31.65
  t5-lottery-dkp: 116.76
  t5-priority-dkp: 116.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Dragonspine Trophy
  - Shadowmaster's Boots
  rank: Reserve Raider
  t4-lottery-dkp: 2885.63
  t4-priority-dkp: 2972.98
  t5-lottery-dkp: 4097.14
  t5-priority-dkp: 4015.82
  t6-lottery-dkp: 7101.0
  t6-priority-dkp: 8066.98
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 160.76
  t4-priority-dkp: 160.76
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 945.16
  t6-priority-dkp: 945.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2996.7
  t4-priority-dkp: 3217.75
  t5-lottery-dkp: 4321.93
  t5-priority-dkp: 4496.11
  t6-lottery-dkp: 2041.43
  t6-priority-dkp: 10121.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  priority-lootconfig:
  - Shroud of the Highborne
  rank: Core Raider
  t4-lottery-dkp: 3178.01
  t4-priority-dkp: 3204.51
  t5-lottery-dkp: 3795.26
  t5-priority-dkp: 4117.83
  t6-lottery-dkp: 4620.2
  t6-priority-dkp: 6691.24
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3162.42
  t4-priority-dkp: 3070.93
  t5-lottery-dkp: 4383.48
  t5-priority-dkp: 4522.81
  t6-lottery-dkp: 4703.18
  t6-priority-dkp: 6641.84
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 72.46
  t4-priority-dkp: 72.46
  t5-lottery-dkp: 124.69
  t5-priority-dkp: 124.69
  t6-lottery-dkp: 72.37
  t6-priority-dkp: 71.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solljus:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2633.1
  t4-priority-dkp: 3097.59
  t5-lottery-dkp: 3875.27
  t5-priority-dkp: 3295.62
  t6-lottery-dkp: 999.1700000000001
  t6-priority-dkp: 9427.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3212.64
  t4-priority-dkp: 3204.51
  t5-lottery-dkp: 3135.34
  t5-priority-dkp: 4330.81
  t6-lottery-dkp: 9168.65
  t6-priority-dkp: 7753.85
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1871.89
  t4-priority-dkp: 1871.89
  t5-lottery-dkp: 3113.28
  t5-priority-dkp: 3113.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3034.47
  t4-priority-dkp: 3097.59
  t5-lottery-dkp: 1547.4
  t5-priority-dkp: 4293.89
  t6-lottery-dkp: 1273.84
  t6-priority-dkp: 9993.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2524.98
  t4-priority-dkp: 3154.06
  t5-lottery-dkp: 540.72
  t5-priority-dkp: 4564.35
  t6-lottery-dkp: 5924.87
  t6-priority-dkp: 8000.6
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Pillar of Ferocity
  - Shadowmoon Insignia
  priority-lootconfig:
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 2987.57
  t4-priority-dkp: 3227.87
  t5-lottery-dkp: 3394.2
  t5-priority-dkp: 4563.6
  t6-lottery-dkp: 3797.66
  t6-priority-dkp: 9558.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
