Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2192.11
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 3237.44
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 178.57
  t4-priority-dkp: 3090.4
  t5-lottery-dkp: -4412.81
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 91.75
  t4-priority-dkp: 91.75
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Leggings of the Fallen Champion
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 1839.18
  t4-priority-dkp: 3083.69
  t5-lottery-dkp: -745.4300000000001
  t5-priority-dkp: 3980.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Fallen Defender
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2289.47
  t4-priority-dkp: 3114.01
  t5-lottery-dkp: 1618.93
  t5-priority-dkp: 4006.24
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2583.69
  t4-priority-dkp: 2512.56
  t5-lottery-dkp: 1864.1
  t5-priority-dkp: 3504.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 330.0
  t5-priority-dkp: 330.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Bloodsea Brigand's Vest
  - Chestguard of the Fallen Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3037.01
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 3941.76
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Shoulderpads of the Stranger
  - Thalassian Wildercloak
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2640.75
  t4-priority-dkp: 2417.27
  t5-lottery-dkp: 1911.57
  t5-priority-dkp: 3425.22
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 924.7
  t4-priority-dkp: 1092.05
  t5-lottery-dkp: 770.22
  t5-priority-dkp: 909.81
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2942.9
  t4-priority-dkp: 2575.17
  t5-lottery-dkp: 3863.82
  t5-priority-dkp: 3557.01
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Chestguard of the Fallen Champion
  - Gronn-Stitched Girdle
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 2819.2
  t5-lottery-dkp: 4027.5
  t5-priority-dkp: 3760.37
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Fallen Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 2765.91
  t5-lottery-dkp: 2027.5
  t5-priority-dkp: 3715.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 1425.91
  t4-priority-dkp: 2942.9
  t5-lottery-dkp: -1150.56
  t5-priority-dkp: 3863.82
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - Eredar Wand of Obliteration
  - Verdant Sphere
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 2541.06
  t4-priority-dkp: 3080.54
  t5-lottery-dkp: 1828.67
  t5-priority-dkp: 3900.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2869.67
  t4-priority-dkp: 2139.77
  t5-lottery-dkp: -197.83
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  priority-lootconfig:
  - Mindstorm Wristbands
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 2942.9
  t5-lottery-dkp: 2027.5
  t5-priority-dkp: 2163.82
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2370.78
  t4-priority-dkp: 2908.16
  t5-lottery-dkp: 3386.96
  t5-priority-dkp: 3834.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Bracers of Eradication
  - Fang of Vashj
  - Leggings of the Vanquished Defender
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2602.98
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 1580.39
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Endless Coils
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1885.76
  t4-priority-dkp: 3080.54
  t5-lottery-dkp: 982.36
  t5-priority-dkp: 4006.24
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Royal Gauntlets of Silvermoon
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Leggings of the Fallen Champion
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 525.65
  t4-priority-dkp: 2908.16
  t5-lottery-dkp: -484.09
  t5-priority-dkp: 3834.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Belt of Divine Inspiration
  - Eredar Wand of Obliteration
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2369.23
  t4-priority-dkp: 2185.66
  t5-lottery-dkp: 3385.54
  t5-priority-dkp: 3232.49
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Pauldrons of the Vanquished Defender
  - Pendant of the Perilous
  - Rod of the Sun King
  - Serpent Spine Longbow
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 1856.7
  t4-priority-dkp: 2736.86
  t5-lottery-dkp: 2958.27
  t5-priority-dkp: 3691.64
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Phoenix-Ring of Rebirth
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2923.56
  t4-priority-dkp: 2659.86
  t5-lottery-dkp: 3847.52
  t5-priority-dkp: 1927.86
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 2352.9
  t4-priority-dkp: 2549.77
  t5-lottery-dkp: 2683.82
  t5-priority-dkp: 2847.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 590.0
  t4-priority-dkp: 590.0
  t5-lottery-dkp: 330.0
  t5-priority-dkp: 330.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Aegis of the Vindicator
  - Sunhawk Leggings
  - Verdant Sphere
  priority-lootconfig:
  - Eye of Gruul
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1206.93
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 416.21
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig:
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 3080.54
  t5-lottery-dkp: 2327.5
  t5-priority-dkp: 2327.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 4027.5
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Band of Al'ar
  - Pendant of the Lost Ages
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 1916.0
  t4-priority-dkp: 2841.51
  t5-lottery-dkp: 3007.87
  t5-priority-dkp: 3778.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 1394.44
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 1406.08
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Bloodsea Brigand's Vest
  - Chestguard of the Fallen Champion
  - Magtheridon's Head
  - Pauldrons of the Vanquished Champion
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 2027.5
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2123.26
  t4-priority-dkp: 3090.4
  t5-lottery-dkp: 3180.05
  t5-priority-dkp: 3945.31
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3139.77
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 4027.5
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1753.78
  t4-priority-dkp: 3139.77
  t5-lottery-dkp: 2872.53
  t5-priority-dkp: 4027.5
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
