Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig:
  - Helm of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 3160.75
  t4-priority-dkp: 2858.72
  t5-lottery-dkp: 342.65
  t5-priority-dkp: 1310.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - Royal Gauntlets of Silvermoon
  - Verdant Sphere
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2267.32
  t4-priority-dkp: 3559.31
  t5-lottery-dkp: -7392.81
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 40.71
  t4-priority-dkp: 40.71
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 2281.64
  t4-priority-dkp: 3556.35
  t5-lottery-dkp: 3107.06
  t5-priority-dkp: 5262.46
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2753.05
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 1408.4
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2203.94
  t4-priority-dkp: 3569.79
  t5-lottery-dkp: 2769.51
  t5-priority-dkp: 5273.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 2972.16
  t4-priority-dkp: 2940.6
  t5-lottery-dkp: 2787.98
  t5-priority-dkp: 4744.11
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  - Pit Lord's Satchel
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Reserve Raider
  t4-lottery-dkp: 1727.38
  t4-priority-dkp: 2449.87
  t5-lottery-dkp: 3642.61
  t5-priority-dkp: 3642.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Gloves of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3535.63
  t4-priority-dkp: 2731.22
  t5-lottery-dkp: 1056.15
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2837.8
  t4-priority-dkp: 3260.65
  t5-lottery-dkp: 224.11
  t5-priority-dkp: 5015.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 410.29
  t4-priority-dkp: 484.54
  t5-lottery-dkp: 341.76
  t5-priority-dkp: 403.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3493.88
  t4-priority-dkp: 2608.21
  t5-lottery-dkp: 5210.59
  t5-priority-dkp: 5074.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Magtheridon's Head
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Gronn-Stitched Girdle
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 2716.48
  t5-lottery-dkp: 3583.21
  t5-priority-dkp: 5164.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 1687.21
  t4-priority-dkp: 3415.34
  t5-lottery-dkp: -2281.41
  t5-priority-dkp: 5144.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Pit Lord's Satchel
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Mindstorm Wristbands
  rank: Core Raider
  t4-lottery-dkp: 2820.77
  t4-priority-dkp: 3493.88
  t5-lottery-dkp: 1450.59
  t5-priority-dkp: 2754.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  priority-lootconfig:
  - Pit Lord's Satchel
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 2179.44
  t4-priority-dkp: 3032.93
  t5-lottery-dkp: 2607.57
  t5-priority-dkp: 3781.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3461.38
  t4-priority-dkp: 3137.52
  t5-lottery-dkp: 555.14
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  - The Nexus Key
  rank: Core Raider
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 2771.38
  t5-lottery-dkp: 4395.8
  t5-priority-dkp: 3412.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Helm of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 3240.02
  t4-priority-dkp: 2478.46
  t5-lottery-dkp: 3299.0
  t5-priority-dkp: 3752.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Fang of Vashj
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3343.05
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: 1708.4
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 339.3
  t5-priority-dkp: 339.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Vanquished Champion
  - Mindstorm Wristbands
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3024.82
  t4-priority-dkp: 3554.94
  t5-lottery-dkp: 3932.07
  t5-priority-dkp: 5273.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 2421.33
  t4-priority-dkp: 3478.46
  t5-lottery-dkp: -1464.09
  t5-priority-dkp: 3497.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Pit Lord's Satchel
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3239.33
  t4-priority-dkp: 2543.75
  t5-lottery-dkp: 4998.37
  t5-priority-dkp: 2507.96
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Leggings of the Vanquished Defender
  - Rod of the Sun King
  - Serpent Spine Longbow
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 2421.92
  t4-priority-dkp: 2812.45
  t5-lottery-dkp: 536.52
  t5-priority-dkp: 5134.19
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1235.76
  t4-priority-dkp: 1235.76
  t5-lottery-dkp: 410.69
  t5-priority-dkp: 410.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 1400.93
  t5-priority-dkp: 1400.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3485.3
  t4-priority-dkp: 3368.28
  t5-lottery-dkp: 1803.35
  t5-priority-dkp: 4351.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1043.99
  t4-priority-dkp: 1131.35
  t5-lottery-dkp: 1190.82
  t5-priority-dkp: 1263.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Vambraces of Ending
  priority-lootconfig:
  - Dragonspine Trophy
  - Serpent Spine Longbow
  rank: Reserve Raider
  t4-lottery-dkp: 2449.87
  t4-priority-dkp: 2449.87
  t5-lottery-dkp: 3642.61
  t5-priority-dkp: 3642.61
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 202.66
  t5-priority-dkp: 202.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Helm of the Vanquished Champion
  - Lightfathom Scepter
  - Verdant Sphere
  priority-lootconfig:
  - Aegis of the Vindicator
  - Eye of Gruul
  rank: Core Raider
  t4-lottery-dkp: 2723.61
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: 277.49
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 2832.44
  t5-lottery-dkp: 4528.91
  t5-priority-dkp: 4528.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: 5283.21
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 3038.23
  t4-priority-dkp: 3448.89
  t5-lottery-dkp: 4830.8
  t5-priority-dkp: 3727.85
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2806.81
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: 4120.07
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Band of the Ranger-General
  - Leggings of the Vanquished Champion
  - Magtheridon's Head
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: -26.41000000000003
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2753.05
  t4-priority-dkp: 2991.22
  t5-lottery-dkp: 1408.4
  t5-priority-dkp: 4983.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3130.19
  t4-priority-dkp: 3559.31
  t5-lottery-dkp: 4907.19
  t5-priority-dkp: 5246.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Gruul
  - Helm of the Vanquished Defender
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 3581.22
  t4-priority-dkp: 3059.22
  t5-lottery-dkp: 6.100000000000023
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2966.25
  t4-priority-dkp: 3581.22
  t5-lottery-dkp: 4770.74
  t5-priority-dkp: 5283.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
