Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 1984.83
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2020.52
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Ancestral Ring of Conquest
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Serpentshrine Shuriken
  - Seventh Ring of the Tirisfalen
  - Shuriken of Negation
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1968.91
  t4-priority-dkp: 3041.65
  t5-lottery-dkp: 7.19
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 107.94
  t4-priority-dkp: 107.94
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Gloves of the Searing Grip
  - Leggings of the Fallen Champion
  - Pendant of the Perilous
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 1569.62
  t4-priority-dkp: 3033.75
  t5-lottery-dkp: -2325.43
  t5-priority-dkp: 2894.98
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Chestguard of the Fallen Defender
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2099.38
  t4-priority-dkp: 3069.42
  t5-lottery-dkp: 116.39
  t5-priority-dkp: 2924.99
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Gloves of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2445.52
  t4-priority-dkp: 2361.84
  t5-lottery-dkp: 2404.82
  t5-priority-dkp: 2334.79
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2978.83
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2849.13
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Shoulderpads of the Stranger
  - Thalassian Wildercloak
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 2512.65
  t4-priority-dkp: 2249.73
  t5-lottery-dkp: 460.67
  t5-priority-dkp: 2241.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1087.88
  t4-priority-dkp: 1284.76
  t5-lottery-dkp: 906.14
  t5-priority-dkp: 1070.36
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2868.12
  t4-priority-dkp: 2435.49
  t5-lottery-dkp: 2757.44
  t5-priority-dkp: 2396.48
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 2722.59
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 2635.73
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Soul-Strider Boots
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Eye of Gruul
  - Lightfathom Scepter
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 2659.9
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 2583.21
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Gauntlets of the Sun King
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - Serpent-Coil Braid
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 1083.42
  t4-priority-dkp: 2868.12
  t5-lottery-dkp: -730.56
  t5-priority-dkp: 2757.44
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mantle of the Elven Kings
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Verdant Sphere
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 2395.37
  t4-priority-dkp: 3030.05
  t5-lottery-dkp: 2363.14
  t5-priority-dkp: 2800.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2781.96
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2684.91
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Ring of Endless Coils
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 2868.12
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 757.44
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Pauldrons of the Vanquished Hero
  - Ring of Endless Coils
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2195.04
  t4-priority-dkp: 2827.25
  t5-lottery-dkp: 2196.42
  t5-priority-dkp: 2723.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Bracers of Eradication
  - Fang of Vashj
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2468.21
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2423.99
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Sextant of Unstable Currents
  - The Nexus Key
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1624.42
  t4-priority-dkp: 3030.05
  t5-lottery-dkp: 1720.42
  t5-priority-dkp: 2924.99
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 2377.23
  t4-priority-dkp: 2827.25
  t5-lottery-dkp: 2348.13
  t5-priority-dkp: 2723.26
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - 'Pattern: Boots of Blasting'
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2193.21
  t4-priority-dkp: 1977.25
  t5-lottery-dkp: 2194.75
  t5-priority-dkp: 2014.69
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bracers of Eradication
  - Chestguard of the Vanquished Defender
  - Girdle of the Endless Pit
  - Helm of the Vanquished Defender
  - Leggings of Murderous Intent
  - Pauldrons of the Vanquished Defender
  - Pendant of the Perilous
  - Serpent Spine Longbow
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Rod of the Sun King
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 1590.23
  t4-priority-dkp: 2625.72
  t5-lottery-dkp: 1692.08
  t5-priority-dkp: 2554.87
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Blackfathom Warbands
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Phoenix-Ring of Rebirth
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Worldstorm Gauntlets
  rank: Core Raider
  t4-lottery-dkp: 2845.36
  t4-priority-dkp: 2535.13
  t5-lottery-dkp: 2738.26
  t5-priority-dkp: 2479.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2868.12
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2757.44
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Girdle of Fallen Stars
  - Sunhawk Leggings
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 825.8
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 1054.37
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Cord of Screaming Terrors
  - Helm of the Vanquished Defender
  - Magtheridon's Head
  - Verdant Sphere
  priority-lootconfig:
  - Pauldrons of the Vanquished Defender
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 3030.05
  t5-lottery-dkp: 950.0
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig:
  - Band of Al'ar
  - Pendant of the Lost Ages
  - Royal Cloak of the Sunstriders
  - The Nexus Key
  priority-lootconfig:
  - Soul-Eater's Handwraps
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 1660.0
  t4-priority-dkp: 2748.84
  t5-lottery-dkp: 1750.43
  t5-priority-dkp: 2657.4
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Helm of the Vanquished Defender
  - Leggings of the Fallen Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  - Magtheridon's Head
  rank: Core Raider
  t4-lottery-dkp: 2222.87
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2218.92
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Chestguard of the Fallen Champion
  - Gloves of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - 'Pattern: Boots of Natural Grace'
  - Pauldrons of the Vanquished Defender
  - Tsunami Talisman
  - Wildfury Greatstaff
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1553.83
  t4-priority-dkp: 2691.65
  t5-lottery-dkp: 2303.0
  t5-priority-dkp: 3203.3
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Gloves of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Sunshower Light Cloak
  rank: Core Raider
  t4-lottery-dkp: 3099.73
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 2950.0
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Girdle of the Endless Pit
  - Leggings of Murderous Intent
  - Shoulderpads of the Stranger
  - Talon of Azshara
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1469.15
  t4-priority-dkp: 3099.73
  t5-lottery-dkp: 1591.21
  t5-priority-dkp: 2950.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
