Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Choker of Serrated Blades
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3106.7
  t4-priority-dkp: 3094.99
  t5-lottery-dkp: 5520.87
  t5-priority-dkp: 4123.15
  t6-lottery-dkp: 120.73
  t6-priority-dkp: 5900.46
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  - Eternium Shell Bracers
  - Leggings of the Vanquished Defender
  - Praetorian's Legguards
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3072.07
  t4-priority-dkp: 3122.14
  t5-lottery-dkp: 618.11
  t5-priority-dkp: 5534.44
  t6-lottery-dkp: -16532.0
  t6-priority-dkp: 5132.6
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 379.94
  t4-priority-dkp: 379.94
  t5-lottery-dkp: 616.97
  t5-priority-dkp: 616.97
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2898.07
  t4-priority-dkp: 3122.02
  t5-lottery-dkp: 5674.74
  t5-priority-dkp: 6083.59
  t6-lottery-dkp: 6059.02
  t6-priority-dkp: 6050.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2661.81
  t4-priority-dkp: 3122.14
  t5-lottery-dkp: 3933.99
  t5-priority-dkp: 6174.19
  t6-lottery-dkp: 3183.48
  t6-priority-dkp: 6537.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3006.49
  t4-priority-dkp: 3122.55
  t5-lottery-dkp: 4034.75
  t5-priority-dkp: 6175.24
  t6-lottery-dkp: 1376.35
  t6-priority-dkp: 6103.13
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 2938.61
  t4-priority-dkp: 2937.39
  t5-lottery-dkp: 3990.6
  t5-priority-dkp: 6043.78
  t6-lottery-dkp: 6992.0
  t6-priority-dkp: 7657.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 42.43
  t5-priority-dkp: 42.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 2906.34
  t4-priority-dkp: 2875.16
  t5-lottery-dkp: 5637.45
  t5-priority-dkp: 5970.07
  t6-lottery-dkp: 5526.09
  t6-priority-dkp: 6419.53
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Madness of the Betrayer
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3094.18
  t4-priority-dkp: 3110.57
  t5-lottery-dkp: 3950.64
  t5-priority-dkp: 6165.25
  t6-lottery-dkp: 4128.33
  t6-priority-dkp: 6332.39
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 15.9
  t4-priority-dkp: 18.78
  t5-lottery-dkp: 13.24
  t5-priority-dkp: 15.65
  t6-lottery-dkp: 7.67
  t6-priority-dkp: 8.9
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Helm of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3119.61
  t4-priority-dkp: 3039.68
  t5-lottery-dkp: 5978.69
  t5-priority-dkp: 5132.61
  t6-lottery-dkp: 5724.28
  t6-priority-dkp: 7068.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 761.66
  t4-priority-dkp: 761.66
  t5-lottery-dkp: 33.63
  t5-priority-dkp: 33.63
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Arcanite Steam-Pistol
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3122.99
  t4-priority-dkp: 3026.37
  t5-lottery-dkp: 2772.8
  t5-priority-dkp: 4391.33
  t6-lottery-dkp: 5120.37
  t6-priority-dkp: 6342.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Royal Cloak of the Sunstriders
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2730.62
  t4-priority-dkp: 3062.92
  t5-lottery-dkp: 4953.58
  t5-priority-dkp: 6096.03
  t6-lottery-dkp: -805.1
  t6-priority-dkp: 7549.03
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3118.34
  t4-priority-dkp: 3105.8
  t5-lottery-dkp: 4377.81
  t5-priority-dkp: 5157.49
  t6-lottery-dkp: 1284.8
  t6-priority-dkp: 7669.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Leggings of the Vanquished Champion
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Ring of Ancient Knowledge
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3122.99
  t4-priority-dkp: 2569.6
  t5-lottery-dkp: 3260.34
  t5-priority-dkp: 5563.69
  t6-lottery-dkp: 1851.98
  t6-priority-dkp: 6185.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 450.93
  t4-priority-dkp: 450.93
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  rank: Core Raider
  t4-lottery-dkp: 2658.84
  t4-priority-dkp: 2566.2
  t5-lottery-dkp: 5661.32
  t5-priority-dkp: 5740.6
  t6-lottery-dkp: 4485.34
  t6-priority-dkp: 6287.46
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2860.95
  t4-priority-dkp: 2782.82
  t5-lottery-dkp: 4852.73
  t5-priority-dkp: 5323.06
  t6-lottery-dkp: 5565.49
  t6-priority-dkp: 7669.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Pauldrons of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 3101.43
  t4-priority-dkp: 3121.98
  t5-lottery-dkp: 5848.5
  t5-priority-dkp: 6096.03
  t6-lottery-dkp: 4828.88
  t6-priority-dkp: 4260.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2286.0
  t4-priority-dkp: 3079.14
  t5-lottery-dkp: 5336.5
  t5-priority-dkp: 4188.33
  t6-lottery-dkp: 1470.2
  t6-priority-dkp: 7126.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Chestguard of the Forgotten Conqueror
  rank: Core Raider
  t4-lottery-dkp: 2881.16
  t4-priority-dkp: 3119.01
  t5-lottery-dkp: 4019.55
  t5-priority-dkp: 5465.24
  t6-lottery-dkp: 1507.22
  t6-priority-dkp: 2395.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1497.54
  t4-priority-dkp: 1497.54
  t5-lottery-dkp: 3719.76
  t5-priority-dkp: 3719.76
  t6-lottery-dkp: 352.75
  t6-priority-dkp: 352.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 2856.93
  t4-priority-dkp: 2655.26
  t5-lottery-dkp: 5922.75
  t5-priority-dkp: 4539.47
  t6-lottery-dkp: 1485.62
  t6-priority-dkp: 7238.18
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Choker of Serrated Blades
  - Dreadboots of the Legion
  - Gloves of the Forgotten Protector
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Leggings of Divine Retribution
  rank: Core Raider
  t4-lottery-dkp: 2125.81
  t4-priority-dkp: 2095.35
  t5-lottery-dkp: 2293.27
  t5-priority-dkp: 4550.37
  t6-lottery-dkp: 1215.22
  t6-priority-dkp: 7296.83
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2654.54
  t4-priority-dkp: 2572.41
  t5-lottery-dkp: 2356.88
  t5-priority-dkp: 3732.63
  t6-lottery-dkp: 4352.31
  t6-priority-dkp: 5391.24
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pudsey:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Shroud of the Highborne
  - Sunshower Light Cloak
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3073.68
  t4-priority-dkp: 3114.74
  t5-lottery-dkp: 5688.48
  t5-priority-dkp: 5692.14
  t6-lottery-dkp: 3989.85
  t6-priority-dkp: 7390.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 363.29
  t4-priority-dkp: 363.29
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 60.63
  t4-priority-dkp: 60.63
  t5-lottery-dkp: 223.68
  t5-priority-dkp: 223.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 2466.5
  t4-priority-dkp: 2633.85
  t5-lottery-dkp: 5280.61
  t5-priority-dkp: 5124.83
  t6-lottery-dkp: 1830.0
  t6-priority-dkp: 3680.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 307.98
  t4-priority-dkp: 307.98
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 287.1
  t6-priority-dkp: 287.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2679.28
  t4-priority-dkp: 3102.76
  t5-lottery-dkp: 5711.22
  t5-priority-dkp: 6044.89
  t6-lottery-dkp: 1174.7
  t6-priority-dkp: 7616.8
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3026.64
  t4-priority-dkp: 3077.39
  t5-lottery-dkp: 4702.28
  t5-priority-dkp: 5320.23
  t6-lottery-dkp: 6114.81
  t6-priority-dkp: 5930.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 2996.77
  t4-priority-dkp: 2821.48
  t5-lottery-dkp: 5829.14
  t5-priority-dkp: 6096.03
  t6-lottery-dkp: 2983.57
  t6-priority-dkp: 5102.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 138.81
  t4-priority-dkp: 138.81
  t5-lottery-dkp: 238.88
  t5-priority-dkp: 238.88
  t6-lottery-dkp: 138.63
  t6-priority-dkp: 137.5
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of Channeled Elements
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  - Tempest of Chaos
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 1982.73
  t4-priority-dkp: 2872.57
  t5-lottery-dkp: 4855.57
  t5-priority-dkp: 5745.13
  t6-lottery-dkp: 1814.47
  t6-priority-dkp: 5254.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Botanist's Gloves of Growth
  rank: Core Raider
  t4-lottery-dkp: 3092.98
  t4-priority-dkp: 3077.39
  t5-lottery-dkp: 3438.07
  t5-priority-dkp: 5728.24
  t6-lottery-dkp: 5790.96
  t6-priority-dkp: 6080.63
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2301.83
  t4-priority-dkp: 2301.83
  t5-lottery-dkp: 3395.84
  t5-priority-dkp: 3395.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Leggings of Eternity
  - Pauldrons of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2751.66
  t4-priority-dkp: 2872.57
  t5-lottery-dkp: 396.1
  t5-priority-dkp: 5657.52
  t6-lottery-dkp: 4848.84
  t6-priority-dkp: 7370.91
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Leggings of the Vanquished Champion
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1775.63
  t4-priority-dkp: 2980.75
  t5-lottery-dkp: 3173.5
  t5-priority-dkp: 6175.61
  t6-lottery-dkp: 5323.94
  t6-priority-dkp: 3553.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Ring of Deceitful Intent
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 2661.81
  t4-priority-dkp: 3122.14
  t5-lottery-dkp: 3933.99
  t5-priority-dkp: 6174.19
  t6-lottery-dkp: 3183.48
  t6-priority-dkp: 6537.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2413.91
  t4-priority-dkp: 2384.11
  t5-lottery-dkp: 6155.75
  t5-priority-dkp: 4947.36
  t6-lottery-dkp: 3659.49
  t6-priority-dkp: 4370.42
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
