Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boneweave Girdle
  - Chestguard of the Forgotten Protector
  - Choker of Endless Nightmares
  - Insidious Bands
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 2970.87
  t4-priority-dkp: 2967.67
  t5-lottery-dkp: 2204.2
  t5-priority-dkp: 1823.34
  t6-lottery-dkp: 2557.04
  t6-priority-dkp: 8884.12
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Borderland Fortress Grips
  - Bulwark of Azzinoth
  - Chestguard of the Forgotten Protector
  - Collar of the Pit Lord
  - Crimson Paragon's Cover
  - Crown of Anasterian
  - Dragonscale-Encrusted Longblade
  - Felfury Legplates
  - Ring of Hardened Resolve
  - Steely Naaru Sliver
  priority-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  rank: Core Raider
  t4-lottery-dkp: 2961.44
  t4-priority-dkp: 2975.08
  t5-lottery-dkp: 227.09
  t5-priority-dkp: 2207.89
  t6-lottery-dkp: -11472.0
  t6-priority-dkp: 7343.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 103.53
  t4-priority-dkp: 103.53
  t5-lottery-dkp: 168.12
  t5-priority-dkp: 168.12
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Cursed Vision of Sargeras
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 1986.25
  t4-priority-dkp: 1726.7
  t5-lottery-dkp: 2246.13
  t5-priority-dkp: 2357.54
  t6-lottery-dkp: 6634.49
  t6-priority-dkp: 8924.97
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2849.64
  t4-priority-dkp: 2975.08
  t5-lottery-dkp: 1771.79
  t5-priority-dkp: 2382.23
  t6-lottery-dkp: 1658.22
  t6-priority-dkp: 9057.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2943.57
  t4-priority-dkp: 2975.2
  t5-lottery-dkp: 1799.25
  t5-priority-dkp: 2382.52
  t6-lottery-dkp: 7651.35
  t6-priority-dkp: 8121.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1373.17
  t4-priority-dkp: 1372.83
  t5-lottery-dkp: 1787.23
  t5-priority-dkp: 2346.69
  t6-lottery-dkp: 3617.69
  t6-priority-dkp: 3799.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2414.77
  t4-priority-dkp: 2406.28
  t5-lottery-dkp: 1857.69
  t5-priority-dkp: 1948.32
  t6-lottery-dkp: 7650.67
  t6-priority-dkp: 6562.99
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Band of Ruinous Delight
  - Belt of the Forgotten Protector
  - Blackened Naaru Sliver
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Choker of Endless Nightmares
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Mantle of the Golden Forest
  - Mounting Vengeance
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2967.46
  t4-priority-dkp: 2971.93
  t5-lottery-dkp: 1776.33
  t5-priority-dkp: 2379.8
  t6-lottery-dkp: 8401.24
  t6-priority-dkp: 6451.82
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 4.33
  t4-priority-dkp: 5.12
  t5-lottery-dkp: 3.6
  t5-priority-dkp: 4.27
  t6-lottery-dkp: 2.09
  t6-priority-dkp: 2.43
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demacian:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1758.39
  t4-priority-dkp: 1758.39
  t5-lottery-dkp: 1335.14
  t5-priority-dkp: 1335.14
  t6-lottery-dkp: 2165.36
  t6-priority-dkp: 2165.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2974.39
  t4-priority-dkp: 2952.61
  t5-lottery-dkp: 2328.97
  t5-priority-dkp: 2098.4
  t6-lottery-dkp: 1804.81
  t6-priority-dkp: 9202.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 207.54
  t4-priority-dkp: 207.54
  t5-lottery-dkp: 9.17
  t5-priority-dkp: 9.17
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Belt of the Forgotten Vanquisher
  - Boots of the Forgotten Vanquisher
  - Bracers of the Forgotten Vanquisher
  - Cloak of Unforgivable Sin
  - 'Design: Hard Khorium Choker'
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Hand of the Deceiver
  rank: Core Raider
  t4-lottery-dkp: 2975.31
  t4-priority-dkp: 2948.97
  t5-lottery-dkp: 814.23
  t5-priority-dkp: 1896.42
  t6-lottery-dkp: 7105.54
  t6-priority-dkp: 9004.62
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2868.38
  t4-priority-dkp: 2958.94
  t5-lottery-dkp: 2049.62
  t5-priority-dkp: 2360.93
  t6-lottery-dkp: 2890.87
  t6-priority-dkp: 9333.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hipon:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2974.05
  t4-priority-dkp: 2970.62
  t5-lottery-dkp: 1892.73
  t5-priority-dkp: 2105.19
  t6-lottery-dkp: 3485.77
  t6-priority-dkp: 8035.02
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Bow-stitched Leggings
  - Madness of the Betrayer
  - Siphon of the Nathrezim
  - Siphon of the Nathrezim
  priority-lootconfig:
  - Dragonspine Trophy
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2975.31
  t4-priority-dkp: 2824.51
  t5-lottery-dkp: 1588.23
  t5-priority-dkp: 2215.87
  t6-lottery-dkp: 7780.96
  t6-priority-dkp: 8144.35
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 122.88
  t4-priority-dkp: 122.88
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2848.83
  t4-priority-dkp: 2823.59
  t5-lottery-dkp: 2242.47
  t5-priority-dkp: 2264.08
  t6-lottery-dkp: 3676.51
  t6-priority-dkp: 7576.53
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2903.91
  t4-priority-dkp: 2882.61
  t5-lottery-dkp: 2022.14
  t5-priority-dkp: 2150.3
  t6-lottery-dkp: 8792.85
  t6-priority-dkp: 7198.63
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Ring of Ancient Knowledge
  - Ring of Omnipotence
  - Tattered Cape of Antonidas
  priority-lootconfig:
  - Shifting Naaru Sliver
  - Sunflare
  rank: Core Raider
  t4-lottery-dkp: 2969.43
  t4-priority-dkp: 2975.03
  t5-lottery-dkp: 1593.66
  t5-priority-dkp: 1661.1
  t6-lottery-dkp: 7630.4
  t6-priority-dkp: 7475.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2747.24
  t4-priority-dkp: 2963.36
  t5-lottery-dkp: 2153.96
  t5-priority-dkp: 1841.1
  t6-lottery-dkp: 6110.9
  t6-priority-dkp: 8086.65
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Loopfish:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - 'Design: Pendant of Sunfire'
  - Girdle of Mighty Resolve
  - Helm of Burning Righteousness
  - Heroic Judicator's Chestguard
  - Legplates of the Holy Juggernaut
  - Pauldrons of Perseverance
  - Sword Breaker's Bulwark
  priority-lootconfig:
  - Belt of the Forgotten Conqueror
  - Bracers of the Forgotten Conqueror
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 2909.41
  t4-priority-dkp: 2974.22
  t5-lottery-dkp: 1795.11
  t5-priority-dkp: 2189.05
  t6-lottery-dkp: 3294.63
  t6-priority-dkp: 6967.29
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Memento of Tyrande
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 1758.39
  t4-priority-dkp: 1758.39
  t5-lottery-dkp: 1335.14
  t5-priority-dkp: 1335.14
  t6-lottery-dkp: 2165.36
  t6-priority-dkp: 2165.36
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 2902.82
  t4-priority-dkp: 2847.86
  t5-lottery-dkp: 2313.72
  t5-priority-dkp: 1936.78
  t6-lottery-dkp: 4784.0
  t6-priority-dkp: 8286.9
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2703.59
  t4-priority-dkp: 1845.28
  t5-lottery-dkp: 1135.57
  t5-priority-dkp: 1750.61
  t6-lottery-dkp: 6789.02
  t6-priority-dkp: 8447.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2529.01
  t4-priority-dkp: 2506.62
  t5-lottery-dkp: 692.1
  t5-priority-dkp: 1611.96
  t6-lottery-dkp: 6039.71
  t6-priority-dkp: 7653.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2961.87
  t4-priority-dkp: 2973.06
  t5-lottery-dkp: 2249.88
  t5-priority-dkp: 2250.87
  t6-lottery-dkp: 5385.65
  t6-priority-dkp: 9290.25
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Reminosc:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 927.77
  t4-priority-dkp: 927.77
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 98.99
  t4-priority-dkp: 98.99
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 16.52
  t4-priority-dkp: 16.52
  t5-lottery-dkp: 60.95
  t5-priority-dkp: 60.95
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Black Bow of the Betrayer
  - Cursed Vision of Sargeras
  priority-lootconfig:
  - Shadowmaster's Boots
  rank: Reserve Raider
  t4-lottery-dkp: 2796.42
  t4-priority-dkp: 2227.9
  t5-lottery-dkp: 2138.73
  t5-priority-dkp: 2096.29
  t6-lottery-dkp: 6208.94
  t6-priority-dkp: 5729.2
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 83.92
  t4-priority-dkp: 83.92
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 493.38
  t6-priority-dkp: 493.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2854.4
  t4-priority-dkp: 2969.8
  t5-lottery-dkp: 2256.07
  t5-priority-dkp: 2346.99
  t6-lottery-dkp: 5133.84
  t6-priority-dkp: 9351.82
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Archon's Gavel
  - Belt of the Forgotten Protector
  - Boots of the Forgotten Protector
  - Bracers of the Forgotten Protector
  - Chestguard of the Forgotten Protector
  - 'Pattern: Sun-Drenched Scale Chestguard'
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1658.94
  t4-priority-dkp: 1672.77
  t5-lottery-dkp: 1981.15
  t5-priority-dkp: 2149.54
  t6-lottery-dkp: 6479.97
  t6-priority-dkp: 5995.04
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2940.91
  t4-priority-dkp: 2893.15
  t5-lottery-dkp: 2288.21
  t5-priority-dkp: 2360.93
  t6-lottery-dkp: 6523.28
  t6-priority-dkp: 7535.28
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 37.82
  t4-priority-dkp: 37.82
  t5-lottery-dkp: 65.09
  t5-priority-dkp: 65.09
  t6-lottery-dkp: 37.77
  t6-priority-dkp: 37.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solljus:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 261.78
  t4-priority-dkp: 261.78
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 1736.82
  t4-priority-dkp: 1979.29
  t5-lottery-dkp: 2022.91
  t5-priority-dkp: 1720.34
  t6-lottery-dkp: -150.27
  t6-priority-dkp: 8989.58
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Book of Highborne Hymns
  - Breeches of Natural Aggression
  - Cover of Ursol the Wise
  - Crystal Spire of Karabor
  - Memento of Tyrande
  - Spaulders of Reclamation
  - Tranquil Majesty Wraps
  priority-lootconfig:
  - Hammer of Sanctification
  rank: Core Raider
  t4-lottery-dkp: 2967.13
  t4-priority-dkp: 2962.89
  t5-lottery-dkp: 1636.67
  t5-priority-dkp: 2260.71
  t6-lottery-dkp: 8854.29
  t6-priority-dkp: 8115.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 977.13
  t4-priority-dkp: 977.13
  t5-lottery-dkp: 1625.16
  t5-priority-dkp: 1625.16
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2874.12
  t4-priority-dkp: 2907.07
  t5-lottery-dkp: 807.75
  t5-priority-dkp: 2241.44
  t6-lottery-dkp: 2890.77
  t6-priority-dkp: 9284.8
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Venatir:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 426.27
  t4-priority-dkp: 426.27
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blackened Naaru Sliver
  - Cloak of Unforgivable Sin
  - Duplicitous Guise
  - Golden Bow of Quel'Thalas
  - Hand of the Deceiver
  - Harness of Carnal Instinct
  - Leggings of the Immortal Night
  - Murumasa
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 2608.17
  t4-priority-dkp: 2936.55
  t5-lottery-dkp: 282.26
  t5-priority-dkp: 2382.62
  t6-lottery-dkp: 7161.01
  t6-priority-dkp: 8244.56
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Shadowmoon Insignia
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2849.64
  t4-priority-dkp: 2975.08
  t5-lottery-dkp: 1771.79
  t5-priority-dkp: 2382.23
  t6-lottery-dkp: 1658.22
  t6-priority-dkp: 9057.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
