Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Magtheridon's Head
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2315.78
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Ancestral Ring of Conquest
  - Boots of the Resilient
  - Chestguard of the Vanquished Defender
  - Frayed Tether of the Drowned
  - Girdle of the Invulnerable
  - Gloves of the Vanquished Defender
  - Leggings of the Vanquished Defender
  - Mallet of the Tides
  - Pauldrons of the Fallen Defender
  - Pauldrons of the Vanquished Defender
  - Phoenix-Wing Cloak
  - 'Plans: Red Havoc Boots'
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - Serpentshrine Shuriken
  - Seventh Ring of the Tirisfalen
  - Spyglass of the Hidden Fleet
  - Verdant Sphere
  - Wristguards of Determination
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 1108.8
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 206.79
  t4-priority-dkp: 206.79
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Band of the Ranger-General
  - Belt of One-Hundred Deaths
  - Bladespire Warbands
  - Bracers of Eradication
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Girdle of the Endless Pit
  - Gloves of the Searing Grip
  - Helm of the Vanquished Champion
  - Leggings of Murderous Intent
  - Leggings of the Fallen Champion
  - Pauldrons of the Fallen Champion
  - Pendant of the Perilous
  - Razor-Scale Battlecloak
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Dragonspine Trophy
  - Shoulderpads of the Stranger
  rank: Core Raider
  t4-lottery-dkp: 3148.71
  t4-priority-dkp: 3148.71
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Fallen Defender
  - Pauldrons of the Fallen Defender
  priority-lootconfig:
  - Dragonspine Trophy
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 2535.21
  t4-priority-dkp: 3217.04
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Leggings of the Fallen Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 2021.83
  t4-priority-dkp: 1861.53
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3043.5
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - 'Pattern: Boots of Utter Darkness'
  - Rod of the Sun King
  - Shoulderpads of the Stranger
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2150.44
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig:
  - Girdle of the Endless Pit
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1389.92
  t4-priority-dkp: 1767.07
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2831.41
  t4-priority-dkp: 2002.62
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 2552.61
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig:
  - Eye of Gruul
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 2432.53
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig:
  - Chestguard of the Fallen Hero
  - Fang of the Leviathan
  - Fathomstone
  - Gauntlets of the Sun King
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  - Serpent-Coil Braid
  - Velvet Boots of the Guardian
  - Verdant Sphere
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Leggings of the Vanquished Hero
  - Pauldrons of the Fallen Hero
  - Pauldrons of the Vanquished Hero
  rank: Core Raider
  t4-lottery-dkp: 2180.65
  t4-priority-dkp: 2831.41
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3309.86
  t4-priority-dkp: 2932.7
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2666.35
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig:
  - Soul-Eater's Handwraps
  priority-lootconfig:
  - Leggings of the Fallen Champion
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 2831.41
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig:
  - Pauldrons of the Fallen Hero
  rank: Core Raider
  t4-lottery-dkp: 1541.99
  t4-priority-dkp: 2753.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2065.31
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinasa:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3217.04
  t4-priority-dkp: 3217.04
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinyonga:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2627.04
  t4-priority-dkp: 2627.04
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kromlek:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Krumonx:
  class: Warlock
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Aldori Legacy Defender
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Girdle of the Invulnerable
  - Leggings of the Vanquished Champion
  - Pauldrons of the Fallen Champion
  - Pauldrons of the Vanquished Champion
  - Phoenix-Wing Cloak
  - Ring of Sundered Souls
  - Royal Gauntlets of Silvermoon
  - The Seal of Danzalar
  - Wristguards of Determination
  priority-lootconfig:
  - Verdant Sphere
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 2753.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mitchendo:
  class: Shaman
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Pauldrons of the Fallen Champion
  rank: Social Member
  t4-lottery-dkp: 571.34
  t4-priority-dkp: 855.41
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mlg:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2552.61
  t4-priority-dkp: 2954.54
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  rank: Core Raider
  t4-lottery-dkp: 1538.5
  t4-priority-dkp: 2753.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig:
  - Dragonspine Trophy
  - Gauntlets of Martial Perfection
  - Girdle of the Endless Pit
  rank: Core Raider
  t4-lottery-dkp: 1559.84
  t4-priority-dkp: 2367.04
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Pikachau:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 116.15
  t4-priority-dkp: 116.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2787.81
  t4-priority-dkp: 2193.5
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig:
  - Claw of the Phoenix
  - Leggings of Murderous Intent
  - Talon of the Phoenix
  - Thalassian Wildercloak
  priority-lootconfig:
  - Chestguard of the Vanquished Hero
  - Dragonspine Trophy
  - Gloves of the Vanquished Hero
  - Helm of the Vanquished Hero
  - Pauldrons of the Vanquished Hero
  - Serpent Spine Longbow
  rank: Core Raider
  t4-lottery-dkp: 2831.41
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Paladin
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Schroumpf:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1436.76
  t4-priority-dkp: 1757.33
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1723.76
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnackypacky:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2282.34
  t4-priority-dkp: 2282.34
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shran:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 206.79
  t4-priority-dkp: 206.79
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Skypola:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 116.15
  t4-priority-dkp: 116.15
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig:
  - Soul-Eater's Handwraps
  rank: Core Raider
  t4-lottery-dkp: 517.04
  t4-priority-dkp: 2602.91
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Coral Band of the Revived
  - Girdle of Zaetar
  - Grove-Bands of Remulos
  - Helm of the Vanquished Defender
  - Orca-Hide Boots
  - Pauldrons of the Vanquished Defender
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Core Raider
  t4-lottery-dkp: 1595.31
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Tenfour:
  class: Rogue
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 136.65
  t4-priority-dkp: 136.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thejudge:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 136.65
  t4-priority-dkp: 136.65
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  priority-lootconfig:
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 984.13
  t4-priority-dkp: 3052.59
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3275.11
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 1779.76
  t4-priority-dkp: 3275.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
