Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3732.19
  t4-priority-dkp: 3722.24
  t5-lottery-dkp: 6875.74
  t5-priority-dkp: 5687.68
  t6-lottery-dkp: 650.73
  t6-priority-dkp: 8280.64
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  - Eternium Shell Bracers
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3702.76
  t4-priority-dkp: 3745.32
  t5-lottery-dkp: 708.39
  t5-priority-dkp: 6887.27
  t6-lottery-dkp: -16002.0
  t6-priority-dkp: 7627.96
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 322.95
  t4-priority-dkp: 322.95
  t5-lottery-dkp: 524.42
  t5-priority-dkp: 524.42
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3554.86
  t4-priority-dkp: 2745.22
  t5-lottery-dkp: 7006.53
  t5-priority-dkp: 7354.05
  t6-lottery-dkp: 5415.42
  t6-priority-dkp: 8408.04
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2764.04
  t4-priority-dkp: 3155.32
  t5-lottery-dkp: 4346.89
  t5-priority-dkp: 6251.06
  t6-lottery-dkp: 4206.21
  t6-priority-dkp: 7056.74
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3647.02
  t4-priority-dkp: 3745.67
  t5-lottery-dkp: 5612.54
  t5-priority-dkp: 7431.95
  t6-lottery-dkp: 4435.15
  t6-priority-dkp: 5902.91
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Reserve Raider
  t4-lottery-dkp: 3589.32
  t4-priority-dkp: 3588.28
  t5-lottery-dkp: 5575.01
  t5-priority-dkp: 7320.21
  t6-lottery-dkp: 9208.45
  t6-priority-dkp: 9774.060000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 36.07
  t5-priority-dkp: 36.07
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Blade of Savagery
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3561.89
  t4-priority-dkp: 3535.39
  t5-lottery-dkp: 5794.83
  t5-priority-dkp: 6077.56
  t6-lottery-dkp: 7962.43
  t6-priority-dkp: 8721.85
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3721.55
  t4-priority-dkp: 3735.48
  t5-lottery-dkp: 5541.04
  t5-priority-dkp: 7423.46
  t6-lottery-dkp: 6774.33
  t6-priority-dkp: 8647.779999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 13.52
  t4-priority-dkp: 15.96
  t5-lottery-dkp: 11.25
  t5-priority-dkp: 13.3
  t6-lottery-dkp: 6.52
  t6-priority-dkp: 7.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - The Skull of Gul'dan
  priority-lootconfig:
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3743.17
  t4-priority-dkp: 3675.23
  t5-lottery-dkp: 7264.89
  t5-priority-dkp: 6545.72
  t6-lottery-dkp: 3030.89
  t6-priority-dkp: 9273.689999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 647.41
  t4-priority-dkp: 647.41
  t5-lottery-dkp: 28.59
  t5-priority-dkp: 28.59
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3746.04
  t4-priority-dkp: 3663.91
  t5-lottery-dkp: 2539.88
  t5-priority-dkp: 5915.63
  t6-lottery-dkp: 7617.56
  t6-priority-dkp: 8656.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Helm of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3412.53
  t4-priority-dkp: 3694.98
  t5-lottery-dkp: 6393.54
  t5-priority-dkp: 7364.63
  t6-lottery-dkp: -419.0899999999999
  t6-priority-dkp: 9681.93
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Conqueror
  - Helm of the Forgotten Conqueror
  - Luminescent Rod of the Naaru
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3742.09
  t4-priority-dkp: 3731.43
  t5-lottery-dkp: 5904.14
  t5-priority-dkp: 6566.87
  t6-lottery-dkp: 4357.33
  t6-priority-dkp: 9784.21
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig:
  - Leggings of Channeled Elements
  - Slippers of the Seacaller
  priority-lootconfig:
  - Flashfire Girdle
  - Sextant of Unstable Currents
  rank: Core Raider
  t4-lottery-dkp: 3746.04
  t4-priority-dkp: 3275.66
  t5-lottery-dkp: 4954.29
  t5-priority-dkp: 6912.14
  t6-lottery-dkp: 4839.43
  t6-priority-dkp: 5973.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 383.29
  t4-priority-dkp: 383.29
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3351.51
  t4-priority-dkp: 3272.77
  t5-lottery-dkp: 6995.12
  t5-priority-dkp: 7062.51
  t6-lottery-dkp: -1022.21
  t6-priority-dkp: 8609.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3523.31
  t4-priority-dkp: 3456.9
  t5-lottery-dkp: 6307.82
  t5-priority-dkp: 6707.6
  t6-lottery-dkp: 7995.92
  t6-priority-dkp: 9784.21
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kines:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 2183.0
  t5-priority-dkp: 2183.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3727.72
  t4-priority-dkp: 3745.18
  t5-lottery-dkp: 4971.22
  t5-priority-dkp: 5181.63
  t6-lottery-dkp: 4369.8
  t6-priority-dkp: 3886.89
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3034.6
  t4-priority-dkp: 3708.77
  t5-lottery-dkp: 6719.02
  t5-priority-dkp: 5743.08
  t6-lottery-dkp: 4514.92
  t6-priority-dkp: 9322.439999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3540.49
  t4-priority-dkp: 3742.66
  t5-lottery-dkp: 5599.62
  t5-priority-dkp: 6828.45
  t6-lottery-dkp: 4546.389999999999
  t6-priority-dkp: 2301.32
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1774.41
  t4-priority-dkp: 1774.41
  t5-lottery-dkp: 4164.8
  t5-priority-dkp: 4164.8
  t6-lottery-dkp: 299.84
  t6-priority-dkp: 299.84
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3519.89
  t4-priority-dkp: 3348.47
  t5-lottery-dkp: 7217.34
  t5-priority-dkp: 6041.55
  t6-lottery-dkp: 4528.030000000001
  t6-priority-dkp: 6417.7
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2898.44
  t4-priority-dkp: 2872.55
  t5-lottery-dkp: 3542.28
  t5-priority-dkp: 5460.81
  t6-lottery-dkp: 1745.22
  t6-priority-dkp: 6917.56
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2682.63
  t4-priority-dkp: 2612.82
  t5-lottery-dkp: 2855.9
  t5-priority-dkp: 4025.29
  t6-lottery-dkp: 4974.68
  t6-priority-dkp: 5857.77
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Botanist's Gloves of Growth
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3704.13
  t4-priority-dkp: 3739.03
  t5-lottery-dkp: 7018.21
  t5-priority-dkp: 7021.32
  t6-lottery-dkp: 1519.85
  t6-priority-dkp: 9547.51
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 308.8
  t4-priority-dkp: 308.8
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 51.54
  t4-priority-dkp: 51.54
  t5-lottery-dkp: 190.13
  t5-priority-dkp: 190.13
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 3188.03
  t4-priority-dkp: 3330.27
  t5-lottery-dkp: 6671.52
  t5-priority-dkp: 6539.11
  t6-lottery-dkp: 4820.75
  t6-priority-dkp: 6393.67
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 261.78
  t4-priority-dkp: 261.78
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 1539.03
  t6-priority-dkp: 1539.03
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Gloves of the Forgotten Conqueror
  - Memento of Tyrande
  - Pauldrons of the Forgotten Conqueror
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3368.89
  t4-priority-dkp: 3728.85
  t5-lottery-dkp: 7037.54
  t5-priority-dkp: 7321.16
  t6-lottery-dkp: 4263.74
  t6-priority-dkp: 9739.529999999999
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Helm of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  priority-lootconfig:
  - Blessed Band of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3664.14
  t4-priority-dkp: 3707.28
  t5-lottery-dkp: 6179.94
  t5-priority-dkp: 6705.2
  t6-lottery-dkp: 8462.84
  t6-priority-dkp: 8305.75
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3638.75
  t4-priority-dkp: 3489.76
  t5-lottery-dkp: 7137.77
  t5-priority-dkp: 7364.63
  t6-lottery-dkp: 5801.280000000001
  t6-priority-dkp: 7602.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 117.99
  t4-priority-dkp: 117.99
  t5-lottery-dkp: 203.05
  t5-priority-dkp: 203.05
  t6-lottery-dkp: 117.84
  t6-priority-dkp: 116.88
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Gloves of the Forgotten Conqueror
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2776.82
  t4-priority-dkp: 3533.18
  t5-lottery-dkp: 6310.23
  t5-priority-dkp: 5366.36
  t6-lottery-dkp: -742.45
  t6-priority-dkp: 7731.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3720.53
  t4-priority-dkp: 3707.28
  t5-lottery-dkp: 5105.360000000001
  t5-priority-dkp: 7052.0
  t6-lottery-dkp: 8187.57
  t6-priority-dkp: 5883.79
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3048.06
  t4-priority-dkp: 3048.06
  t5-lottery-dkp: 5069.46
  t5-priority-dkp: 5069.46
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Tongsta:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 165.0
  t6-priority-dkp: 165.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Conqueror
  - Gloves of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3430.41
  t4-priority-dkp: 3533.18
  t5-lottery-dkp: 2519.68
  t5-priority-dkp: 6991.89
  t6-lottery-dkp: -621.16
  t6-priority-dkp: 9530.52
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Gloves of the Vanquished Champion
  - Insidious Bands
  - Pauldrons of the Vanquished Champion
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 2600.79
  t4-priority-dkp: 3625.14
  t5-lottery-dkp: 880.47
  t5-priority-dkp: 7432.27
  t6-lottery-dkp: 7790.6
  t6-priority-dkp: 6285.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Ring of Deceitful Intent
  - Shadowmoon Insignia
  - Thalassian Wildercloak
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 3354.04
  t4-priority-dkp: 3745.32
  t5-lottery-dkp: 5526.89
  t5-priority-dkp: 7431.06
  t6-lottery-dkp: 2971.21
  t6-priority-dkp: 8821.74
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Dreadboots of the Legion
  - Tsunami Talisman
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2553.32
  t4-priority-dkp: 2527.99
  t5-lottery-dkp: 6913.89
  t5-priority-dkp: 5886.76
  t6-lottery-dkp: 6375.82
  t6-priority-dkp: 6980.11
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
