Abstinence:
  class: Hunter
  lottery-lootconfig:
  - Band of the Ranger-General
  - Thalassian Wildercloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3816.55
  t4-priority-dkp: 3719.73
  t5-lottery-dkp: 5736.75
  t5-priority-dkp: 4405.45
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Cloak of the Pit Stalker
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3530.14
  t4-priority-dkp: 3944.32
  t5-lottery-dkp: -8252.81
  t5-priority-dkp: 7320.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 603.0
  t5-priority-dkp: 603.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Aro:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 13.05
  t4-priority-dkp: 13.05
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  priority-lootconfig:
  - Dragonspine Trophy
  - Tsunami Talisman
  rank: Core Raider
  t4-lottery-dkp: 2091.02
  t4-priority-dkp: 3943.38
  t5-lottery-dkp: 3177.96
  t5-priority-dkp: 6559.62
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Bankdude:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3284.99
  t4-priority-dkp: 2638.84
  t5-lottery-dkp: 2250.56
  t5-priority-dkp: 6140.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Tsunami Talisman
  - Warboots of Obliteration
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2987.82
  t4-priority-dkp: 3947.68
  t5-lottery-dkp: 3674.29
  t5-priority-dkp: 7317.54
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabris:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Fallen Champion
  - Chestguard of the Vanquished Champion
  - Helm of the Vanquished Champion
  - Leggings of the Fallen Champion
  - Leggings of the Vanquished Champion
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 3166.11
  t4-priority-dkp: 3155.98
  t5-lottery-dkp: 5890.66
  t5-priority-dkp: 6517.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Brittany:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 350.93
  t5-priority-dkp: 350.93
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chubrock:
  class: Mage
  lottery-lootconfig:
  - Eredar Wand of Obliteration
  - Eye of Magtheridon
  - Fang of the Leviathan
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Mindstorm Wristbands
  - The Nexus Key
  rank: Reserve Raider
  t4-lottery-dkp: -4.649999999999977
  t4-priority-dkp: 3588.66
  t5-lottery-dkp: 380.44
  t5-priority-dkp: 6794.64
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Band of the Ranger-General
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3936.73
  t4-priority-dkp: 3678.86
  t5-lottery-dkp: 2689.52
  t5-priority-dkp: 5440.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  priority-lootconfig:
  - Rod of the Sun King
  rank: Core Raider
  t4-lottery-dkp: 3713.03
  t4-priority-dkp: 3848.58
  t5-lottery-dkp: 3584.34
  t5-priority-dkp: 7234.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 131.52
  t4-priority-dkp: 155.33
  t5-lottery-dkp: 109.56
  t5-priority-dkp: 129.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Mindstorm Wristbands
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3923.35
  t4-priority-dkp: 3262.27
  t5-lottery-dkp: 5691.9
  t5-priority-dkp: 7253.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digie:
  class: Rogue
  lottery-lootconfig:
  - Leggings of the Vanquished Champion
  - Rod of the Sun King
  - Verdant Sphere
  priority-lootconfig:
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3951.34
  t4-priority-dkp: 3152.13
  t5-lottery-dkp: 4977.280000000001
  t5-priority-dkp: 7282.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Eye of Magtheridon
  - Mindstorm Wristbands
  - Royal Cloak of the Sunstriders
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2621.67
  t4-priority-dkp: 3454.46
  t5-lottery-dkp: -15.75999999999999
  t5-priority-dkp: 5591.06
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Galm:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2230.15
  t4-priority-dkp: 3333.35
  t5-lottery-dkp: 2825.77
  t5-priority-dkp: 4285.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Goodjorb:
  class: Mage
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 1621.85
  t4-priority-dkp: 1141.17
  t5-lottery-dkp: 1144.58
  t5-priority-dkp: 3803.74
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hulkhigginz:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Earring of Soulful Meditation
  - Lightfathom Scepter
  - Luminescent Rod of the Naaru
  - Sunshower Light Cloak
  - Verdant Sphere
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3912.93
  t4-priority-dkp: 3809.11
  t5-lottery-dkp: 4917.45
  t5-priority-dkp: 7320.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jahmee:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Ring of Endless Coils
  rank: Core Raider
  t4-lottery-dkp: 3951.34
  t4-priority-dkp: 3691.73
  t5-lottery-dkp: 5227.73
  t5-priority-dkp: 4612.43
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  priority-lootconfig:
  - Mindstorm Wristbands
  - Wand of the Forgotten Star
  rank: Core Raider
  t4-lottery-dkp: 3841.97
  t4-priority-dkp: 3075.82
  t5-lottery-dkp: 5419.93
  t5-priority-dkp: 6075.63
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kang:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3874.99
  t4-priority-dkp: 3228.84
  t5-lottery-dkp: 3430.56
  t5-priority-dkp: 7320.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangbuff:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 108.77
  t5-priority-dkp: 108.77
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinastra:
  class: Shaman
  lottery-lootconfig:
  - Mindstorm Wristbands
  - The Nexus Key
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3772.98
  t4-priority-dkp: 3942.92
  t5-lottery-dkp: 4615.17
  t5-priority-dkp: 7317.54
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kurister:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 362.33
  t4-priority-dkp: 362.33
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bloodmaw Magus-Blade
  - Boots of the Resilient
  - Leggings of the Vanquished Champion
  - Wristguards of Determination
  priority-lootconfig:
  - Royal Cloak of the Sunstriders
  rank: Core Raider
  t4-lottery-dkp: 3579.51
  t4-priority-dkp: 3918.41
  t5-lottery-dkp: 975.25
  t5-priority-dkp: 6748.18
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Mekanina:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Fang of the Leviathan
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - Royal Cloak of the Sunstriders
  - Verdant Sphere
  priority-lootconfig:
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 3841.74
  t4-priority-dkp: 2173.75
  t5-lottery-dkp: 5229.26
  t5-priority-dkp: 6430.89
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashy:
  class: Warrior
  lottery-lootconfig:
  - Belt of One-Hundred Deaths
  - Chestguard of the Vanquished Defender
  - Rod of the Sun King
  - Tsunami Talisman
  priority-lootconfig:
  - Dragonspine Trophy
  - Talon of Azshara
  rank: Core Raider
  t4-lottery-dkp: 3271.72
  t4-priority-dkp: 3019.77
  t5-lottery-dkp: 2908.9
  t5-priority-dkp: 7272.8
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nynisa:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2697.94
  t4-priority-dkp: 2697.94
  t5-lottery-dkp: 278.09
  t5-priority-dkp: 278.09
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Onetotemman:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1740.29
  t4-priority-dkp: 1740.29
  t5-lottery-dkp: 2104.84
  t5-priority-dkp: 2104.84
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayas:
  class: Shaman
  lottery-lootconfig:
  - Sunshower Light Cloak
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3543.44
  t4-priority-dkp: 3883.08
  t5-lottery-dkp: 3291.6
  t5-priority-dkp: 3321.91
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Roodolph:
  class: Hunter
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 334.68
  t4-priority-dkp: 362.68
  t5-lottery-dkp: 381.74
  t5-priority-dkp: 405.02
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2188.08
  t4-priority-dkp: 2188.08
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 501.5
  t4-priority-dkp: 501.5
  t5-lottery-dkp: 850.0
  t5-priority-dkp: 850.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Magtheridon's Head
  priority-lootconfig:
  - Dragonspine Trophy
  - Verdant Sphere
  rank: Reserve Raider
  t4-lottery-dkp: 2070.89
  t4-priority-dkp: 2070.89
  t5-lottery-dkp: 1569.63
  t5-priority-dkp: 3049.29
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2857.14
  t4-priority-dkp: 2714.9
  t5-lottery-dkp: 1954.73
  t5-priority-dkp: 4578.34
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Coral Band of the Revived
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3154.41
  t4-priority-dkp: 3574.2
  t5-lottery-dkp: 1128.45
  t5-priority-dkp: 4831.57
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shlarred:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 0.0
  t4-priority-dkp: 0.0
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig: []
  priority-lootconfig:
  - Brute Cloak of the Ogre-Magi
  - Vestments of the Sea-Witch
  rank: Core Raider
  t4-lottery-dkp: 2907.33
  t4-priority-dkp: 3711.3
  t5-lottery-dkp: 4455.06
  t5-priority-dkp: 7078.76
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 1148.06
  t4-priority-dkp: 1148.06
  t5-lottery-dkp: 1975.78
  t5-priority-dkp: 1975.78
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Solzar:
  class: Priest
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 2259.5
  t4-priority-dkp: 2391.15
  t5-lottery-dkp: 3385.69
  t5-priority-dkp: 3786.41
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Fathomstone
  - Mindstorm Wristbands
  - Ring of Endless Coils
  - The Nexus Key
  - Verdant Sphere
  - Wand of the Forgotten Star
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Fang of the Leviathan
  - Vestments of the Sea-Witch
  rank: Reserve Raider
  t4-lottery-dkp: 1880.1
  t4-priority-dkp: 1880.1
  t5-lottery-dkp: 910.22
  t5-priority-dkp: 3760.22
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3703.09
  t4-priority-dkp: 3574.2
  t5-lottery-dkp: 4967.67
  t5-priority-dkp: 3620.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Chestguard of the Vanquished Defender
  - Helm of the Vanquished Defender
  - Sunshower Light Cloak
  priority-lootconfig:
  - Lightfathom Scepter
  rank: Reserve Raider
  t4-lottery-dkp: 880.1
  t4-priority-dkp: 1880.1
  t5-lottery-dkp: -2514.0
  t5-priority-dkp: 3035.55
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Talon of Azshara
  - Vambraces of Ending
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 3507.64
  t4-priority-dkp: 3951.34
  t5-lottery-dkp: 2341.78
  t5-priority-dkp: 7320.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Weedster:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 3284.99
  t4-priority-dkp: 2638.84
  t5-lottery-dkp: 2250.56
  t5-priority-dkp: 6140.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Thalassian Wildercloak
  - Tsunami Talisman
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3806.76
  t4-priority-dkp: 3944.32
  t5-lottery-dkp: 3500.03
  t5-priority-dkp: 7308.88
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zeion:
  class: Priest
  lottery-lootconfig:
  - Eye of Gruul
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3361.34
  t4-priority-dkp: 3194.0
  t5-lottery-dkp: 2849.68
  t5-priority-dkp: 5936.28
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3252.69
  t4-priority-dkp: 3006.14
  t5-lottery-dkp: 7156.29
  t5-priority-dkp: 7320.58
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
