Abjection:
  class: Hunter
  lottery-lootconfig:
  - Boundless Agony
  - Bristleblitz Striker
  - Chestguard of the Forgotten Protector
  - Insidious Bands
  - Pauldrons of the Forgotten Protector
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  priority-lootconfig:
  - Cursed Vision of Sargeras
  - Thalassian Wildercloak
  rank: Core Raider
  t4-lottery-dkp: 3198.01
  t4-priority-dkp: 3190.82
  t5-lottery-dkp: 4967.72
  t5-priority-dkp: 4109.35
  t6-lottery-dkp: 3335.4
  t6-priority-dkp: 8848.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Akaran:
  class: Warrior
  lottery-lootconfig:
  - Cataclysm's Edge
  priority-lootconfig:
  - Blade of Savagery
  rank: Core Raider
  t4-lottery-dkp: 3176.75
  t4-priority-dkp: 3207.49
  t5-lottery-dkp: 511.81
  t5-priority-dkp: 4976.05
  t6-lottery-dkp: -15872.0
  t6-priority-dkp: 8376.45
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Albynonurse:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 233.33
  t4-priority-dkp: 233.33
  t5-lottery-dkp: 378.9
  t5-priority-dkp: 378.9
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ashori:
  class: Paladin
  lottery-lootconfig:
  - Chestguard of the Forgotten Conqueror
  - Torch of the Damned
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 3069.89
  t4-priority-dkp: 2484.92
  t5-lottery-dkp: 5062.22
  t5-priority-dkp: 5313.3
  t6-lottery-dkp: 6777.89
  t6-priority-dkp: 8940.060000000001
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Babyshrimp:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2924.79
  t4-priority-dkp: 3207.49
  t5-lottery-dkp: 3993.18
  t5-priority-dkp: 5368.94
  t6-lottery-dkp: 1096.95
  t6-priority-dkp: 7873.96
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Baopi:
  class: Warrior
  lottery-lootconfig:
  - Dragonspine Trophy
  - Dreadboots of the Legion
  - Gloves of the Vanquished Defender
  - Grips of Silent Justice
  - Pauldrons of the Vanquished Defender
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  rank: Core Raider
  t4-lottery-dkp: 3136.47
  t4-priority-dkp: 3207.75
  t5-lottery-dkp: 4055.06
  t5-priority-dkp: 5369.59
  t6-lottery-dkp: 6069.65
  t6-priority-dkp: 7130.1
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Barnabae:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Forgotten Protector
  - Chestguard of the Vanquished Champion
  - Chestguard of the Vanquished Champion
  - Crystal Spire of Karabor
  - Gloves of the Forgotten Protector
  - Gloves of the Vanquished Champion
  - Helm of the Forgotten Protector
  - Leggings of the Forgotten Protector
  - Leggings of the Vanquished Champion
  - Leggings of the Vanquished Champion
  - Memento of Tyrande
  - Pauldrons of the Forgotten Protector
  - Pauldrons of the Vanquished Champion
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 3094.78
  t4-priority-dkp: 3094.03
  t5-lottery-dkp: 4027.95
  t5-priority-dkp: 5288.85
  t6-lottery-dkp: 8153.35
  t6-priority-dkp: 8562.01
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Chuunin:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 3074.97
  t4-priority-dkp: 3055.82
  t5-lottery-dkp: 4186.77
  t5-priority-dkp: 4391.04
  t6-lottery-dkp: 6068.11
  t6-priority-dkp: 6616.78
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Crazydaisy:
  class: Shaman
  lottery-lootconfig:
  - Choker of Endless Nightmares
  - Shadowmaster's Boots
  - Shadowmoon Destroyer's Drape
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3190.32
  t4-priority-dkp: 3200.39
  t5-lottery-dkp: 4003.4
  t5-priority-dkp: 5363.45
  t6-lottery-dkp: 7759.7
  t6-priority-dkp: 9113.27
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Dalran:
  class: Warrior
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Social Member
  t4-lottery-dkp: 9.77
  t4-priority-dkp: 11.53
  t5-lottery-dkp: 8.13
  t5-priority-dkp: 9.61
  t6-lottery-dkp: 4.71
  t6-priority-dkp: 5.47
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Demeker:
  class: Warlock
  lottery-lootconfig:
  - Chronicle of Dark Secrets
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  - The Skull of Gul'dan
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 3205.94
  t4-priority-dkp: 3156.86
  t5-lottery-dkp: 5248.89
  t5-priority-dkp: 4729.28
  t6-lottery-dkp: 5055.07
  t6-priority-dkp: 9565.49
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Despia:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 467.75
  t4-priority-dkp: 467.75
  t5-lottery-dkp: 20.66
  t5-priority-dkp: 20.66
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Digitalz:
  class: Rogue
  lottery-lootconfig:
  - Don Alejandro's Money Belt
  - Rod of the Sun King
  - Shadowmaster's Boots
  priority-lootconfig:
  - Cursed Vision of Sargeras
  rank: Core Raider
  t4-lottery-dkp: 3208.01
  t4-priority-dkp: 3148.67
  t5-lottery-dkp: 1835.07
  t5-priority-dkp: 4274.05
  t6-lottery-dkp: 8368.939999999999
  t6-priority-dkp: 9119.57
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Ellievyra:
  class: Priest
  lottery-lootconfig:
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2967.05
  t4-priority-dkp: 3171.12
  t5-lottery-dkp: 4619.33
  t5-priority-dkp: 5320.95
  t6-lottery-dkp: -490.98
  t6-priority-dkp: 9860.44
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Hyolin:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Crystal Spire of Karabor
  - Luminescent Rod of the Naaru
  - Naaru-Blessed Life Rod
  - Scepter of Purification
  priority-lootconfig:
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 3205.16
  t4-priority-dkp: 3197.46
  t5-lottery-dkp: 4265.74
  t5-priority-dkp: 4744.56
  t6-lottery-dkp: 833.73
  t6-priority-dkp: 9934.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Jaamii:
  class: Shaman
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3208.01
  t4-priority-dkp: 2868.16
  t5-lottery-dkp: 3579.48
  t5-priority-dkp: 4994.02
  t6-lottery-dkp: 6361.74
  t6-priority-dkp: 7180.74
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justin:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 276.93
  t4-priority-dkp: 276.93
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Justinjr:
  class: Warlock
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  - The Nexus Key
  priority-lootconfig:
  - Fang of the Leviathan
  - Tempest of Chaos
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2922.96
  t4-priority-dkp: 2866.07
  t5-lottery-dkp: 5053.97
  t5-priority-dkp: 5102.66
  t6-lottery-dkp: 1996.37
  t6-priority-dkp: 5901.02
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kangdude:
  class: Warrior
  lottery-lootconfig:
  - Band of the Ranger-General
  - Madness of the Betrayer
  - Stormrage Signet Ring
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3047.09
  t4-priority-dkp: 2999.11
  t5-lottery-dkp: 4557.4
  t5-priority-dkp: 4846.24
  t6-lottery-dkp: 8642.3
  t6-priority-dkp: 9934.34
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Kinestra:
  class: Shaman
  lottery-lootconfig:
  - Ring of Ancient Knowledge
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3194.78
  t4-priority-dkp: 3207.39
  t5-lottery-dkp: 3591.71
  t5-priority-dkp: 3743.73
  t6-lottery-dkp: 6022.43
  t6-priority-dkp: 5673.53
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Lilchub:
  class: Mage
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Cuffs of Devastation
  - Ring of Ancient Knowledge
  - Slippers of the Seacaller
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 2694.0
  t4-priority-dkp: 3181.08
  t5-lottery-dkp: 4854.49
  t5-priority-dkp: 4149.38
  t6-lottery-dkp: 6127.28
  t6-priority-dkp: 7050.71
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Malchazor:
  class: Paladin
  lottery-lootconfig:
  - Bulwark of Azzinoth
  - Girdle of Mighty Resolve
  - The Seeker's Wristguards
  - Tide-stomper's Greaves
  priority-lootconfig:
  - Tempest of Chaos
  rank: Core Raider
  t4-lottery-dkp: 3059.51
  t4-priority-dkp: 3205.57
  t5-lottery-dkp: 4045.73
  t5-priority-dkp: 4933.55
  t6-lottery-dkp: 6150.02
  t6-priority-dkp: 4527.95
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Metasyn:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 1282.01
  t4-priority-dkp: 1282.01
  t5-lottery-dkp: 3009.07
  t5-priority-dkp: 3009.07
  t6-lottery-dkp: 316.63
  t6-priority-dkp: 316.63
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Murduc:
  class: Warlock
  lottery-lootconfig:
  - Leggings of the Forgotten Conqueror
  - Pauldrons of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  priority-lootconfig:
  - The Skull of Gul'dan
  rank: Core Raider
  t4-lottery-dkp: 3044.62
  t4-priority-dkp: 2920.77
  t5-lottery-dkp: 5214.53
  t5-priority-dkp: 4365.02
  t6-lottery-dkp: 6136.76
  t6-priority-dkp: 7502.04
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nashborne:
  class: Warrior
  lottery-lootconfig:
  - Dreadboots of the Legion
  - Grips of Silent Justice
  - Helm of the Forgotten Protector
  - Serpent Spine Longbow
  - Shadowmoon Destroyer's Drape
  - Stormrage Signet Ring
  - Tsunami Talisman
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Dragonspine Trophy
  rank: Core Raider
  t4-lottery-dkp: 2595.62
  t4-priority-dkp: 2576.92
  t5-lottery-dkp: 2559.3
  t5-priority-dkp: 3945.44
  t6-lottery-dkp: 4126.17
  t6-priority-dkp: 7863.19
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Nekryss:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2726.81
  t4-priority-dkp: 2676.37
  t5-lottery-dkp: 1559.81
  t5-priority-dkp: 3632.94
  t6-lottery-dkp: 5953.35
  t6-priority-dkp: 6591.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rayashaman:
  class: Shaman
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Helm of the Forgotten Protector
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 3177.73
  t4-priority-dkp: 3202.95
  t5-lottery-dkp: 5070.66
  t5-priority-dkp: 5072.9
  t6-lottery-dkp: 963.34
  t6-priority-dkp: 9763.32
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Rotheart:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 223.11
  t4-priority-dkp: 223.11
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Salchant:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 37.24
  t4-priority-dkp: 37.24
  t5-lottery-dkp: 137.37
  t5-priority-dkp: 137.37
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searious:
  class: Hunter
  lottery-lootconfig:
  - Blade of Infamy
  - Shadowmaster's Boots
  priority-lootconfig:
  - Dragonspine Trophy
  - Pauldrons of the Forgotten Protector
  rank: Reserve Raider
  t4-lottery-dkp: 2804.86
  t4-priority-dkp: 2907.62
  t5-lottery-dkp: 4820.17
  t5-priority-dkp: 4724.5
  t6-lottery-dkp: 6348.24
  t6-priority-dkp: 7484.68
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Searusdots:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 189.13
  t4-priority-dkp: 189.13
  t5-lottery-dkp: 0.0
  t5-priority-dkp: 0.0
  t6-lottery-dkp: 1111.95
  t6-priority-dkp: 1111.95
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Seion:
  class: Priest
  lottery-lootconfig:
  - Memento of Tyrande
  priority-lootconfig:
  - Crystal Spire of Karabor
  rank: Core Raider
  t4-lottery-dkp: 2935.53
  t4-priority-dkp: 3195.59
  t5-lottery-dkp: 5084.62
  t5-priority-dkp: 5289.54
  t6-lottery-dkp: 395.8
  t6-priority-dkp: 9902.06
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sekkondary:
  class: Shaman
  lottery-lootconfig:
  - Chestguard of the Forgotten Protector
  - Pauldrons of the Forgotten Protector
  - Shroud of the Highborne
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3148.84
  t4-priority-dkp: 3180.01
  t5-lottery-dkp: 4465.01
  t5-priority-dkp: 4844.51
  t6-lottery-dkp: 6429.65
  t6-priority-dkp: 5866.16
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Shnacks:
  class: Druid
  lottery-lootconfig:
  - Anetheron's Noose
  - Leggings of Channeled Elements
  - Ring of Ancient Knowledge
  - Ring of Ancient Knowledge
  - Vestments of the Sea-Witch
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3130.5
  t4-priority-dkp: 3022.86
  t5-lottery-dkp: 5157.03
  t5-priority-dkp: 5320.95
  t6-lottery-dkp: 7056.68
  t6-priority-dkp: 5808.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sizzle√±ips:
  class: Mage
  lottery-lootconfig:
  - Magtheridon's Head
  - Pauldrons of the Fallen Hero
  priority-lootconfig:
  - Bloodmaw Magus-Blade
  - Eye of Magtheridon
  rank: Social Member
  t4-lottery-dkp: 85.25
  t4-priority-dkp: 85.25
  t5-lottery-dkp: 146.7
  t5-priority-dkp: 146.7
  t6-lottery-dkp: 85.14
  t6-priority-dkp: 84.45
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Spookyremi:
  class: Warlock
  lottery-lootconfig:
  - Cloak of the Illidari Council
  - Leggings of the Forgotten Conqueror
  - Ring of Ancient Knowledge
  - Tempest of Chaos
  priority-lootconfig:
  - Wand of the Forgotten Star
  - Zhar'doom, Greatstaff of the Devourer
  rank: Core Raider
  t4-lottery-dkp: 2507.76
  t4-priority-dkp: 3054.22
  t5-lottery-dkp: 4559.14
  t5-priority-dkp: 3877.2
  t6-lottery-dkp: -765.8299999999999
  t6-priority-dkp: 9085.68
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Sylador:
  class: Druid
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Chestguard of the Vanquished Defender
  - Crystal Spire of Karabor
  - Leggings of the Vanquished Defender
  - Memento of Tyrande
  - Pauldrons of the Vanquished Defender
  priority-lootconfig: []
  rank: Core Raider
  t4-lottery-dkp: 3189.58
  t4-priority-dkp: 3180.01
  t5-lottery-dkp: 3688.63
  t5-priority-dkp: 5095.07
  t6-lottery-dkp: 8780.77
  t6-priority-dkp: 7116.29
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Thorinix:
  class: Not Set
  lottery-lootconfig: []
  priority-lootconfig: []
  rank: Not Set
  t4-lottery-dkp: 2202.22
  t4-priority-dkp: 2202.22
  t5-lottery-dkp: 3662.68
  t5-priority-dkp: 3662.68
  t6-lottery-dkp: 0.0
  t6-priority-dkp: 0.0
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Velyris:
  class: Priest
  lottery-lootconfig:
  - Blessed Band of Karabor
  - Blessed Band of Karabor
  - Gloves of the Forgotten Conqueror
  - Shroud of the Highborne
  priority-lootconfig:
  - Crystal Spire of Karabor
  - Lightfathom Scepter
  - Memento of Tyrande
  rank: Core Raider
  t4-lottery-dkp: 2979.97
  t4-priority-dkp: 3054.22
  t5-lottery-dkp: 1820.47
  t5-priority-dkp: 5051.64
  t6-lottery-dkp: -491.1600000000001
  t6-priority-dkp: 9751.05
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Vermora:
  class: Rogue
  lottery-lootconfig:
  - Blade of Savagery
  - Insidious Bands
  priority-lootconfig:
  - Belt of One-Hundred Deaths
  - Shadowmoon Destroyer's Drape
  rank: Core Raider
  t4-lottery-dkp: 2380.57
  t4-priority-dkp: 3120.66
  t5-lottery-dkp: 636.14
  t5-priority-dkp: 5369.82
  t6-lottery-dkp: 8493.96
  t6-priority-dkp: 7406.59
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Wildshrimp:
  class: Druid
  lottery-lootconfig:
  - Pillar of Ferocity
  - Shadowmoon Insignia
  priority-lootconfig:
  - Shadowmaster's Boots
  rank: Core Raider
  t4-lottery-dkp: 2924.79
  t4-priority-dkp: 3207.49
  t5-lottery-dkp: 3993.18
  t5-priority-dkp: 5368.94
  t6-lottery-dkp: 2461.95
  t6-priority-dkp: 9238.96
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
Zerxx:
  class: Warrior
  lottery-lootconfig:
  - Tsunami Talisman
  priority-lootconfig:
  - Band of the Ranger-General
  - Stormrage Signet Ring
  rank: Core Raider
  t4-lottery-dkp: 2346.27
  t4-priority-dkp: 2327.97
  t5-lottery-dkp: 4995.29
  t5-priority-dkp: 4253.19
  t6-lottery-dkp: 3556.78
  t6-priority-dkp: 3993.38
  t6pt5-lottery-dkp: 0.0
  t6pt5-priority-dkp: 0.0
